### ISSUE TITLE
this.$q is not a function in OAuth 2.0

### ISSUE THREAD

**Issue by isaac2004** [sahat/satellizer#1000]
I created a new project and installed the module through bower, however when I run, I get an error on this line

Line 823 in satellizer.js
`return this.$q(function (resolve, reject) {`

Is there an additional step that is missing in the Quickstart?

**Comment by techSavvySaahil** [comment]
I got the same error. I updated my angular version from 1.2.20 to 1.3.0.
Now, it's working.

**Comment by daflav** [comment]
Hello how i can fix that error without update please
