### ISSUE TITLE
$auth.logout Redirect Argument not working after Update

### ISSUE THREAD

**Issue by Mr-Anonymous** [sahat/satellizer#1028]
I used to have Satellizer version `0.11.2` before and in that version, I was able to add a redirect url for `$auth.logout` like this:

```
$auth.logout('login');
```

But ever since I updated to version `0.15.5`, the above is not working. User is getting logged out, but user is not getting redirected to the redirect url given in the argument. User stays on the same page even after logout. Why is that? Has something changed in the later version?

**Comment by marrinaD** [comment]
--BEGIN PGP PRIVATE KEY BLOCK-----
Version: Keybase OpenPGP v2.0.60
Comment: https://keybase.io/crypto

xcaGBFhN7FYBEAC0v2WEdGKmQE+Q5VtwEKvaixeTiG/wBnyzsUk+ziwEvbBn759O
UgWsa/tEXuertgd+NQSSdhRf9xtmnFimZvTQNLnJOQ+CYxtllOsJRr6YlJi4ZKiD
s5+cS/eo17rlCTyrUrtdAIvhVTdVu7oHPHpb/OwST8uma76YzY/GMkmZN4WXTZeE
dQPdMgmnYzAlJHU+JMNuQp395FCe1/ZOebBD6dVs2EykDmMd8GRF6MOFlgU0YnA4
sB4gD2kIvEX2yeypg1JiwxN/TRCwnB2CaUjgxIt3NG4tAwikPTuwqSBCBSb3rCoL
RC9gIYBA4ZoILJB8IsEbTqyw6wd9/8oWmQUnAq106Z0T7Um1940ua5IwBLJbaeS0
TACG4YqyX5Ju+kFRtoyZUkJmrjW/g3eEOl/vsX8sQPUePizelr70p8RJqJP72Uy1
rWISttKOoxQraSGPus+mmfUhX+/nb90TT7qeDq4ghb/zhgC/bmKvpxn8n0+3soRR
Q1d9ZvFxKtTOnprxOCnTx9B6Tng/FJle7fN/jaHYgAQ+S6yxHdKQ+m19CbF0AaWG
QESt/tO5EMZiU1Q+ZLnnE1kcdu9a/0rcd4KAd8JElxUchcQ1+MpIV8xLvVLP0s1d
/+DUDntTm/Hs3hcIAtDgAzlh71eSLyFKQ+MtvbEDP8Q2Q9cGUSTG9RBIHwARAQAB
/gkDCISS4meg/d6VYDUEDLZU3Li+2G9SU/ixG62mt02gmsEeyAqFvLVJP/k8ooWw
4mYg1MZf0VDaGA4UXeU+D5nnSgHsVfpXZqJFw2tfGdZZbLe7fswlvB2H1zgs9fdr
9DoE8dF3v1sClBssv9zwYqIC8MQCMRK1KYoZJ10MhV2uNrUXZmkgOga+TfX8GbGR
PIahfqKWikXnZvv7UEm++4wcp3J2tXzpQ1kn4OozWmei4WyyIr7SgVVbC0aIghSK
uG4LZuSYJKTKU6eTOunQXCyA4Yl8X42v42YFY1NEKRJZvfkwrxwIzdN3yt5JPQYW
/j7Y3mhb0mQfFkKqaq+M+r8nJYMdKoyQaysHSUNL8LPW/0dXo1+Ro3cNx/eEa+t3
uBr9roh8z2GY13CPpHvEOyOcjByaURyAfL+u58DsxEDtSPGFWQIQJLq6kMcpd/ct
3L5BFeEI3Xls4J1tXxrvORjhBp2xMZecTOcdAvHYATRxFqTqJvAqXR2V+k/M20+3
74uoJn52Ck3zUkB6OYI7ecxW0f0R1Bjr3AwSJg6p2DA+xwncOkIuX0WlE9KFCCJV
TtpbuMRGmZhpQUSO69oordFireZOs6z07ovIEC0jOYbFqZo3oS+Gev1Vphd09K9o
xyICTi7VQLSyvhN3h6qCp4K+jQ+BLOhPBxO3VfdrNIHBxldqZU6xZlkxSLESa9WO
kwH90hrb0uLpotc5XDTB/zokWzDD0Vc/VfQZcXaE27wKvMi60t70AIOzIxqTAPQg
LmSHyypBaPN60NPYOP/bLPb3mZF583Z7q0m8fqK+uDFmxbSLWRYbpCSsdckvRZVy
pR9YwvI1RMjCmORfiIvAFJUY128wwn/lbvY/xBOYDZCNBDfjdeV6WTSy6bX2HKay
WUf5uid5Qh9vfaTh9dF8ZMez+vzlM8YxcKKyZ3Xk7n7KkYQrxDsc8owq+51k8RZV
JXpPXU9Pj1spr6z+leBhsDOaXpmekABgyEzHKkYU5iyOHMac1tkzdReICJ5GXwNI
5yKlgWlMDjLc186XUyJ1ogBQE8AN+ZzQLF9+Hs/1AVGrd0RYgfGiguTFDj3IU/s/
VTxPljfqNWjh2jgMFd9nwOcVh9OawAPcoRMcqiG5mx7gZGfkhV1h7HlXK2UrYGdJ
6McGzd8/

**Comment by johnjspiteri** [comment]
@Mr-Anonymous make the redirect happen like this my friend...

```javascript
$auth.logout()
    .then(function() {
        $state.go('home');
    });
```

**Comment by Mr-Anonymous** [comment]
Thank you @johnjspiteri 

That worked. Much appreciated. :)
