### ISSUE TITLE
No POST to provider.url after successful social login

### ISSUE THREAD

**Issue by TheSplashX** [sahat/satellizer#1038]
satellizer version 0.15.5
in conjunction with working asp.net core 1.1.0 web api [https://github.com/williamhallatt/aspnet-core-webapi-jwt-auth-example](https://github.com/williamhallatt/aspnet-core-webapi-jwt-auth-example)
manual login flow (email/password) perfectly working (API is receiving a POST with user info) and user is receiving an access_token

I'm unable to receive a POST to provider.url (/auth/facebook for example) after successful social login so I can't ask for facebook the user's profile information with the received acces_token
I'm positively receiving an access_token from facebook

$authProvider.facebook({
            clientId: '------------------',
            responseType: 'token',
            url: 'http://localhost:63338/api/auth/facebook'
        });

**Comment by TheSplashX** [comment]
found the solution 👍 
remove the responseType: 'token', for the implicit grant.
the default responseType: 'code' (omitted) sends back a POST to provider.url

**Comment by scutler19** [comment]
I'm currently having the same issue. 

In OAuth2 I have:
responseType: 'code',
responseParams: {
    code: 'code',
    clientId: 'clientId',
    redirectUri: 'redirectUri'
}
...

I have a successful FB login, and I can pull profile info (id, email, first name, last name, link, friends) as the login is being executed, but I can't figure out how to do it once the login is complete.
