### ISSUE TITLE
POPUP does not close

### ISSUE THREAD

**Issue by aliasav** [sahat/satellizer#1086]
Hi, I am using Satellizer with `Angular 1.6.4` & `Django 1.9 with DRF`. 

I run the SPA using grunt at http://loalhost:9000/
My backend runs at http://localhost:8000/
CORS headers have been set in my backend API.

Having followed the docs for LinkedIn and Google authenticate, I am facing the following problem:
- After `$authenticate(provider)` is called, a GET request to my API backend is initiated: 
`"GET /auth/linkedin/?code=<code>&state=<state> HTTP/1.1"`
- In my API I fetch the code, make a request to provider's OAuth servers and obtain an `access_token`. The API returns the access_token with a 200 Response. 
- The popup remains open after a 200 Response. No POST request is made to my backend API.

What am I missing here?

Following are my app.js settings
```
$authProvider.linkedin({
            url: '/auth/linkedin/',
            clientId: '',
            authorizationEndpoint: 'https://www.linkedin.com/uas/oauth2/authorization',
            redirectUri: "http://localhost:8000/auth/linkedin/",
            requiredUrlParams: ['state'],
            scope: ['r_emailaddress'],
            scopeDelimiter: ' ',
            state: 'whysoserious',
            oauthType: '2.0',
            popupOptions: { width: 527, height: 582 }
        });
```

**Comment by stephengardner** [comment]
Hey @aliasav what ended up being the issue here? Having a similar issue
