### ISSUE TITLE
Twitter API gives an error "Callback URL not approved for this client application"

### ISSUE THREAD

**Issue by cimplival** [sahat/satellizer#1128]
Attempts to resolve this error by using the various solutions provided in other websites such as including:
`twittersdk://` or `twitterkit-yourConsumerKey` or even including 'https://www.mywebsite.com/auth/twitter/callback' and 'http://localhost:8000/auth/twitter/callback' in the call back url field at https://apps.twitter.com/ have not worked.

The satellizer documentation does not also seem to address this recent twitter change.

Some insights on this would help.

**Comment by cimplival** [comment]
Found the solution  [(here)](https://developer.twitter.com/en/docs/basics/callback_url):

I simply had to check that the URL that I was using with the callback_url parameter in my oauth/request_token call had been whitelisted in my app settings on [apps.twitter.com](https://apps.twitter.com).

Simply putting `http://localhost:8000` in the callback url field on twitter, resolved the issue, since that was the callback_url in my oauth/request_token call for my development environment.

For production, `https://www.example.com` should work well if thats the callback in the production oauth/request_token call.

**Comment by stevendaye** [comment]
hey @cimplival, how can I whitelist the callbackURL in my apps.twitter.com. Im facing the "Callback url not accepted for this application" issue since a while and can't know how to solve it.

I put in the callback url field on twitter : **http://localhost:3000**. and the same in my development app. But still getting the same error over and over agin.

Can you help please?

**Comment by ijajmulani** [comment]
instead of **localhost** use **127.0.0.1** 
So use [http://127.0.0.1:3000](url)

**Comment by ijajmulani** [comment]
Try [](http://127.0.0.1:3000)
