### ISSUE TITLE
request Authorization header

### ISSUE THREAD

**Issue by connor11528** [sahat/satellizer#120]
I have a setup following your node.js example. Creating users, logging in and logging out all works fine. When I try to go to the "Protected" page though I get rejected by the `ensureAuthenticated` middleware.

The request to `/api/me` does not have an `authorization` header. Instead the `req.headers.authorization` looks like this: 

```
{ host: 'localhost:3000',
  connection: 'keep-alive',
  accept: 'application/json, text/plain, */*',
  'user-agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.94 Safari/537.36',
  referer: 'http://localhost:3000/',
  'accept-encoding': 'gzip,deflate,sdch',
  'accept-language': 'en-US,en;q=0.8,fr;q=0.6' }
```

So how do I make sure my request has an authorization header when hitting /api/me?

It looks like this part of angular sends the request:

```
angular.module('MyApp')
  .factory('Account', function($http) {
    return {
      getUserInfo: function() {
        return $http.get('/api/me');
      }
    };
  });
```

After login the server successfully sends a token, but when trying to access protected resources my requests don't have a `req.body.authorization` header, so they don't pass the ensureAuthenticated middleware:

![screen shot 2014-09-17 at 12 24 58 pm](https://cloud.githubusercontent.com/assets/3578908/4309804/6b5fb0e2-3ea0-11e4-868c-ba5265c8eff4.png)

**Comment by umasgn** [comment]
I'm getting the same problem as jgentes, in my client local storage i can see token, but req object on server has no authorization header.

**Comment by mbejda** [comment]
same...

**Comment by sahat** [comment]
Have you used `$authProvider.httpInterceptor` flag at all?

Default value: `httpInterceptor: function() { return true; }` which means it will use HTTP interceptor that adds this authorization header to every request.

Here is the source code:
```js
.factory('SatellizerInterceptor', [
      '$q',
      'SatellizerConfig',
      'SatellizerStorage',
      'SatellizerShared',
      function($q, config, storage, shared) {
        return {
          request: function(request) {
            if (request.skipAuthorization) {
              return request;
            }

            if (shared.isAuthenticated() && config.httpInterceptor(request)) {
              var tokenName = config.tokenPrefix ? config.tokenPrefix + '_' + config.tokenName : config.tokenName;
              var token = storage.get(tokenName);

              if (config.authHeader && config.authToken) {
                token = config.authToken + ' ' + token;
              }

              request.headers[config.authHeader] = token;
            }

            return request;
          },
          responseError: function(response) {
            return $q.reject(response);
          }
        };
      }])
    .config(['$httpProvider', function($httpProvider) {
      $httpProvider.interceptors.push('SatellizerInterceptor');
    }]);
```

I am not sure why it doesn't work for you, but you can easily add this at the application level in your app's config.

**Comment by cleechtech** [comment]
@umasgn you're talking express server? Here are some express tips on accessing headers: http://stackoverflow.com/questions/13147693/how-to-extract-request-http-headers-from-a-request-using-nodejs-connect

You using passport for authentication on server side?

**Comment by samarhaider** [comment]
@umasgn @mbejda 
I have commit below line and my problem solved

> // $authProvider.httpInterceptor = false;
