### ISSUE TITLE
Token displays in popup - popup doesn't close

### ISSUE THREAD

**Issue by quipu** [sahat/satellizer#123]
I have a situation where on the client it seems to get stuck parsing the JWT token passed to it by the server. On the server, provider authorisation has completed, the token has been generated and is now being passed to the client. But the token displays in the popup (replacing the provider login screen there previously) and the popup just stays open, displaying the token in the body of the popup.

My setup is like this: server running node/express v4 on api.test.com, and the client being served from a standard webserver on app.test.com (nginx). I'm pretty much using the code from the repo examples, just adding changes to support express v4 routes and support CORS.

I've been testing with providers Facebook, Google, and Twitter.

Facebook is working fine - like a dream.

The problem occurs with Google and Twitter. The token displays in the popup, described above, e.g. - Google: 

```
{"token":"eyJ0eXA---HEAPS_OF_OTHER_CHARS_THEN---sqBw"}
```

If it helps, the URL of the popup when the token shows is:

   http://app.test.com/auth/google?code=4/vSPKEt---HEAPS_OF_OTHER_CHARS_THEN---Ao30vkQI&authuser=0&num_sessions=1&session_state=6b0592510---YADA-YADA-YADA---a928d04..9feb&prompt=none

Google does the same, but the URL is http://app.test.com/auth/twitter?code=4/v-etc-etc-etc

Any help would be appreciated.

**Comment by murindwaz** [comment]
I having exactly the same problem as @quipu! I don't want to switch on something else, but would like to know how I can handle that case, I also accept a hack! basically, Twitter returns http://127.0.0.1:8080/?oauth_token=[a valid token here], but the popup window is not closed, and authentication key is not set! I found out it works perfect if I test with your setup at https://satellizer.herokuapp.com/#/! Any help will be appreciated!

**Comment by alex-fernandez** [comment]
Any development on this?

**Comment by oleksiv** [comment]
I have the same issue. Also it appears in https://satellizer.herokuapp.com
![](http://i.imgur.com/R1Q3fbA.png)

**Comment by Walid-Shouman** [comment]
I'm having the same issue, how could it be solved?

**Comment by mcblum** [comment]
We are also experiencing the same issue intermittently. Any ideas what might be causing this?

**Comment by weshouman** [comment]
For me the main page was redirecting to /user/login, thus there's a probability the connection is slow enough that our website's redirection succeeds and  therefore the provider smoothly hands over to the main page.  
Fix included modifying the redirectUri.

**Comment by dadair-ca** [comment]
@Walid-Shouman can you provide more information for your fix? I'm experiencing the same issue
