### ISSUE TITLE
x-origin issue

### ISSUE THREAD

**Issue by etiennemarais** [sahat/satellizer#128]
Hi, 

How do I add a header for "Access-Control-Allow-Origin", my Angular front and API is on different domains.

admin.domain.app calls  ---> api.domain.app

XMLHttpRequest cannot load http://api.domain.app/auth. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://admin.domain.app' is therefore not allowed access.

**Comment by mtangoo** [comment]
which package did you use. I face same issue with Yii2 and I will be interested of your solution
