### ISSUE TITLE
How would I re-configure provider's callback link?

### ISSUE THREAD

**Issue by helxsz** [sahat/satellizer#147]
I am using github for authentication, but  
the default satellizer the github 's callback is like : window.location.origin || window.location.protocol + '//' + window.location.host, but my callback in the github application is like : redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host +"auth/github/callback"
so my question is how would I declare the new github callback in my angular.js application.

I did this by
  $authProvider.github({
    clientId: '536f1716d3af629c69c4',
    redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host+'/auth/github/callback',
  });

but doesn't seem to be successful
Moreover, when I still used the default redirectURL, and make my github application redirectURL to 127.0.0.1:8080/, I thought it should be ok, but when the popup starts out, it shows the page 127.0.0.1:8080 but also shows the url with a error message
http://127.0.0.1:8080/?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch

**Comment by eswarreddy43** [comment]
Hi @helxsz @sahat , I am also getting same error. 

```
{
error: "redirect_uri_mismatch", error_description: "The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.", error_uri: "https://developer.github.com/v3/oauth/#redirect-uri-mismatch"
}
```

I have provided Authorization callback URL as `https://myappurl.com/auth/github`.

Do I need to create any new route for this?
