### ISSUE TITLE
On login sends OPTIONS method instead of POST

### ISSUE THREAD

**Issue by piernik** [sahat/satellizer#168]
Hi,

I'm using `http://root.system.local` url for APP and `http://api.system.local` for API.
With settings like this on `$auth.login()` it sends data in OPTIONS method - not in POST.
When I put both platforms on localhost `http://localhost/system_root` and `http://localhost/system_api` all is ok - send POST request.
Why is that?

**Comment by esayli** [comment]
I have the same problem sahat, When I check request it shows the request method "options", but I am using Angularjs, above code for php.

**Comment by mtangoo** [comment]
+1 I have same Issue with Yii2
Could someone point out the solution? Why would it send Options instead of POST?

**Comment by conradob** [comment]
Same here. 
only happens to me when I set the `$authProvider.baseUrl = API_URL;`

**Comment by conradob** [comment]
In fact, seems not to be a Satellizer bug as explained in this link

http://stackoverflow.com/questions/12111936/angularjs-performs-an-options-http-request-for-a-cross-origin-resource?answertab=active#tab-top
