### ISSUE TITLE
Google+ sign in using nodejs not passing any info in profile.sub and profile.name

### ISSUE THREAD

**Issue by pgregovic** [sahat/satellizer#187]
Hi,

First of all, great job on Satellizer, really love it.

I have a problem regarding google+ sign in.
profile variable on serverside (like in your nodejs example) is not passing any values in profile.sub or profile.name.

when i log it, profile is an object, but sub and name are undefined.

Thank you, and great work

**Comment by GlennGeenen** [comment]
It is possible that google returns an error instead of the expected profile. I've made a pull request to handle the error in the nodejs example: https://github.com/GlennGeenen/satellizer/commit/752d2a0a838287672119aa779b47d0414ba50b3e
