### ISSUE TITLE
401 response deletes satellizer token in local storage

### ISSUE THREAD

**Issue by jgentes** [sahat/satellizer#188]
This is more of a question.. I've noticed that _sometimes_ when the server returns a 401, the local token is deleted and I have to login again. It usually happens when something has gone wrong, and I fix it in my server-side code, but I've noticed I can sometimes return 401 with a proper 'unauthorized' request and the local token remains valid.

For example, with Express and Node, this response reset my local token:

```
} else { 
      res.status(401).send({ message: 'You do not have permission to change this role.'}); 
    }
```

Should I reserve 401 for the case where I want to blow away their token, and use a different response code, or is there something I'm missing?

Thanks!

**Comment by anatoly314** [comment]
@sahat, is there any discussion why have this done and possible workaround? It caused a lot of problem to users, for example here: http://stackoverflow.com/questions/35672707/how-to-delete-token-on-api-error-401
