### ISSUE TITLE
Dynamic callback URL?

### ISSUE THREAD

**Issue by bhousman** [sahat/satellizer#192]
My app does not have a consistent login page such as `http://example.com/login`. Rather my app's URLs are dynamic and token based, for example: `http://example.com/XH12aT1771`. My login box consists of a modal overlaid on top of this dynamic-type page.

Is it possible for me to avoid redirecting a user to a static callback url upon authenticating, such as `http://example.com/success`? The problem with redirecting a user to a static callback url is it's a poor user experience as it takes the user away from the page they're on.

Are there any other solutions to avoid redirecting the user such as presenting a popup window?

**Comment by bhousman** [comment]
@sahat Excellent solution. Works great. Thank you.

**Comment by sahat** [comment]
Cheers. Closing this issue.

**Comment by jgentes** [comment]
Thanks, this config setting solved a problem for me too.
