### ISSUE TITLE
Is there a way to disable the interceptor for attaching the token to the request?

### ISSUE THREAD

**Issue by paulvanbladel** [sahat/satellizer#201]
Since I have an own implementation of the above interceptor (which is code generated), I would like to disable the interceptor. 
Is this possible?
Thanks a lot.
-paul.

**Comment by herrerodani** [comment]
Not working for me, I think it's because it doesn't have a setter method like:

httpInterceptor : {
  set: function(value) { config.httpInterceptor = value; },
  get: function() { return config.httpInterceptor; }
},

**Comment by sahat** [comment]
Fixed in #256.
