### ISSUE TITLE
Offline User Access

### ISSUE THREAD

**Issue by cinjon** [sahat/satellizer#205]
Hi there. Great library, I appreciate the detail and the docs a lot.

How do I use the access token for offline access? I am using the google auth flow and need to manage a 
user's email.

Thanks.

**Comment by asmerkin** [comment]
But then you can't ask for offline access, so then you can use the refresh token to get a new token when the token has expired and the user is not online.

**Comment by GilbertChan** [comment]
@sahat @asmerkin In the explicit grant flow in Satellizer, how would one get the refresh token and refresh the token on expiry? I would like to make server side offline calls pull Google user data.

**Comment by dgrubelic** [comment]
Hi there. I just had that problem and i solved it using optional request url params.

```javascript
$authProvider.google({
  optionalUrlParams: ['access_type'],
  accessType: 'offline'
});
```

Once your account has been authorised, you can store refresh_token to database and use it in your app.

**Comment by cinjon** [comment]
This is what I did too.

**Comment by GilbertChan** [comment]
Thanks! Got it working now.

**Comment by MaximShoustin** [comment]
+1

**Comment by sabrehagen** [comment]
@sahat this should be added to the docs. spent three hours researching this only to have google eventually turn up this issue!
