### ISSUE TITLE
FaceBook Login displaying warning message

### ISSUE THREAD

**Issue by runtimeZero** [sahat/satellizer#217]
while attempting Facebook login, I came across this error.

In order to replicate, hit login button twice (which will open two pops asking facebook for permissions). the second popup will have this message (see image)
![screen shot 2014-12-14 at 11 20 53 am](https://cloud.githubusercontent.com/assets/4563991/5428055/72b49808-8383-11e4-9c5d-eac0cc1a8dfb.png)

**Comment by artmees** [comment]
I'm still getting this error with every login
I'm using the 

        display: 'popup',
        popupOptions: { width: 481, height: 269 }

first I get the following
![screen shot 2015-05-27 at 11 49 25 pm](https://cloud.githubusercontent.com/assets/347712/7848332/8f8957f8-04d3-11e5-829e-df8489fae10e.png)

then when I enlarge the popup, I get the following

![screen shot 2015-05-27 at 11 46 07 pm](https://cloud.githubusercontent.com/assets/347712/7848274/0a87652c-04d3-11e5-8a6b-9fe128ab425a.png)

**Comment by artmees** [comment]
my bad :blush:
I forgot to add the `display` to the `requiredUrlParams`

so that 

    requiredUrlParams: ['scope'],
    // would be
   requiredUrlParams: ['display', 'scope']
