### ISSUE TITLE
c# webapi is officialy supported ?

### ISSUE THREAD

**Issue by JanickRoss** [sahat/satellizer#219]
c# webapi is officialy supported ? Or not finished ?

**Comment by hasanaydogar** [comment]
My I use satellizer with v5 now?
Is there any sample for angular  client with .net web api server side?
Thanks

**Comment by niemyjski** [comment]
@hasanaydogar I have a fully working and deployed solution using angular and satellizer.

Please see:
1. https://github.com/exceptionless/Exceptionless/blob/master/Source/Api/Controllers/AuthController.cs
2. https://github.com/exceptionless/Exceptionless.ui

**Comment by hasanaydogar** [comment]
Thanks.

**Comment by carl09** [comment]
Hi, i started trying to write a simple demo for this in web api 2 using owin and JWT, any feedback would be good
https://github.com/carl09/satellizer/tree/master/examples/server/c%23-webapi2

Thanks
Carl

**Comment by sahat** [comment]
Closing this issue. Will use another issue to track the progress of C# api example.
