### ISSUE TITLE
Node server module

### ISSUE THREAD

**Issue by stevenceuppens** [sahat/satellizer#22]
Sahat, 

I was thinking that it's maybe a good idea to develop a node-satellizer & express-satellizer middleware module, that hooks up most of the boilerplate code.
- node-satellizer -> basic library with methods to exchange authorization codes etc.. this if someone wants to use satellizer with his own http derived framework like restify etc...
- express-satellizer -> library on top of node-satelizer that hooks into express as middleware, and in which you just register your callback functions like signup user, find user, link, unlink, etc...

(for link, unlink -> see my previous issue)

If you like, i want to help on this.

**Comment by danivek** [comment]
Has anyone ever tried to use [authom](https://github.com/jed/authom) with satellizer for server auth ?
