### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by rahil471** [sahat/satellizer#222]
Hello!
I don't know if I'm doing anything wrong here.
But i downloaded the js file and setup my config and call authenticate function.
It opens a popup window and asks for user permission the it closes
and in firebug i see this request failing .

Can you guide me what is this request supposed to mean ?
https://<host>/auth/facebook
404:Not found
or what can i use for URL

Do I also need to setup the node.js backend server?

**Comment by sahat** [comment]
@rahil471 this is not a pure client-side authentication library. It has already been discussed and argued over during initial stages of Satellizer's development. Ultimately, what you see right now was the best trade off between doing auth entirely on the server versus doing auth entirely on the client.
