### ISSUE TITLE
Route State for different level of authorization

### ISSUE THREAD

**Issue by nicolabortignon** [sahat/satellizer#231]
In my User table I added a boolean field (isAdmin).

Now, on angular side, I want to create a new state in /admin. But I'd like to check not just isAuthenticated() but also isAdmin().  I can fetch that date via api/me but I'm wondering how secure it can be.
A malicious user, can edit the object client, and when trying to access the /admin, it would be granted authentication.
What's the best approach for this?

**Comment by sahat** [comment]
@nicolabortignon, it would be as secure as you can make it on the back-end.
Create a new middleware `isAdmin` or `ensureAdmin`, assuming you are using Node.js and Express. 

Then add it to those back-end routes that handle display / create / update / delete actions of administrator. In AngularJS you could make a request to **/api/me** using ui-router's `resolve: function() { ... }` that would tell you if it's an admin or not.

Generally with single-page apps, if a malicious user decides to access unauthorized routes, it's fine to display the page template, just as long as you don't display the actual potential sensitive data. And the way you protect it is on the the back-end.
