### ISSUE TITLE
Problems with angular-file-upload

### ISSUE THREAD

**Issue by daver182** [sahat/satellizer#235]
Hi, I'm trying to use satellizer and angular-file-upload, the files are uploaded to S3 but I'm getting the error "Unsupported Authorization Type", I discovered that is caused because Satellizer change the Authorization header to the request, so it sends the JWT token to S3.
There is any solution that I can prevent Satellizer to add the auth header?

**Comment by sahat** [comment]
Hey @daver182,

There was a similar request recently, so I have made it so that you can disable HTTP request authorization header. I really need to update the README.

```js
if (config.httpInterceptor) {
        $httpProvider.interceptors.push(['$q', function($q) {
          var tokenName = config.tokenPrefix ? config.tokenPrefix + '_' + config.tokenName : config.tokenName;
          return {
            request: function(httpConfig) {
              var token = localStorage.getItem(tokenName);
              if (token) {
                token = config.authHeader === 'Authorization' ? 'Bearer ' + token : token;
                httpConfig.headers[config.authHeader] = token;
              }
              return httpConfig;
            },
            responseError: function(response) {
              return $q.reject(response);
            }
          };
        }]);
      }
```

So this is how you would disable it:

$authProvider.httpInterceptor = null; (or false)

**Comment by sahat** [comment]
README is now updated.
```js
$authProvider.httpInterceptor = true, // Add Authorization header to HTTP request
...
other config options
...
```

**Comment by daver182** [comment]
Hi @sahat, if I understand your answer, with that option I can disable the addition of the header to all request?, or I can disable it only for some requests? Because I only need that for the request to AWS not for everything.
I was thinking that would a be good option to create an exclude list, a list of url or domains that the interceptor doesn't have to add the header, for example:
```
   $authProvider.excludeList = ['*.s3.amazonaws.com']
```

Then in the interceptor check if the url is not in the excludeList.

**Comment by sahat** [comment]
@daver182 It will disable HTTP interceptor for all requests. The idea is that you if choose to do that, you will have to create your own HTTP interceptor and append `Authorization` header yourself when you need to, and that's where you would handle `401` or `403` requests as well, e.g. redirect to `/login` if server returns `401` error. 

There are no plans to add `excludeList` at the moment. Perhaps at some later time. The top priority right now is to implement all server-side examples and close as many open issues as possible before 1.0 release.

**Comment by daver182** [comment]
Ok @sahat, I understand the last part, so is there any easy way to just override de satellizer interceptor?

**Comment by sahat** [comment]
@daver182 I am not sure how AngularJS handles config overrides. My guess is that if you create another HTTP inteceptor it will augment it, or maybe replace it completely. I don't know to be honest. The easiest solution in your case is set `httpInterceptor` to false, then copy and paste above http interceptor and modify it to your needs.

**Comment by daver182** [comment]
I'm doing something like that, for now I think is the only solution, thanks.

**Comment by sahat** [comment]
I am going to close this issue for now. I will consider adding whitelist, blacklist or excludelist or something along those lines  for HTTP interceptor  in the future.

**Comment by bhousman** [comment]
@daver182 @sahat I am having the same exact issue as I am trying to use https://github.com/danialfarid/ng-file-upload. Can you please report more of your findings or how you resolved the issue?

**Comment by farantesrodrigues** [comment]
Hi, I was facing the same problem and just wanted to drop a note saying that you can overcome incompatibility of and ng-file-upload by setting `{skipAuthorization: true}` in the upload request as [documented](https://github.com/sahat/satellizer#how-can-i-avoid-sending-authorization-header-on-all-http-requests).

**Comment by lulzimfazlija2** [comment]
Have you tried to add satellizer_token into the uploader obj like this:

var uploader = $scope.uploader = new FileUploader({
            url: 'http://localhost:81/venture-backend/public/file',
            //method: 'PUT',
            headers: {
                Authorization: 'Bearer ' + localStorage.getItem('satellizer_token')
            }
        });

**Comment by mcblum** [comment]
@farantesrodrigues Where did you put {skipAuthorization: true}? Did you modify ng-file-upload?

**Comment by farantesrodrigues** [comment]
@mcblum Here follows a sample of a POST request uploading a file to AWS:

```javascript
Upload.upload({
    url: aws_url_with_bucket (or whatever),
    method: 'POST',
    data: {
        key: ...,
        AWSAccessKeyId: ...,
        acl: ...,
        policy: ...,
        signature: ...,
         "Content-Type": ...,
        filename: ...
    },
    skipAuthorization: true,
    file: ...
}).then(...)
```

**Comment by mcblum** [comment]
thank you @farantesrodrigues! Works great.

**Comment by TD-Stanley** [comment]
thank you! I thought i was losing my mind.
