### ISSUE TITLE
Support of OAuth2 state parameter

### ISSUE THREAD

**Issue by akkie** [sahat/satellizer#238]
From: http://docs.silhouette.mohiva.com/en/latest/how-it-works/providers.html#oauth2-state

> The OAuth2 protocol supports the [state parameter](http://tools.ietf.org/html/rfc6749#section-4.1.1), a value the client can include in the request and that the server returns as a parameter unmodified in the response. This parameter [should be used mainly](http://www.thread-safe.com/2014/05/the-correct-use-of-state-parameter-in.html) to protect an application against [CSRF attacks](http://www.oauthsecurity.com/#authorization-code-flow). But it can also be used to remember some state about the user.

Satellizer should support a method which allows to support a dynamically created state. Maybe the best method would be to allow to define a function as parameter which gets executed every time a request will be sent to the OAuth2 provider.

```js
$authProvider.facebook({
    clientId: 'xxxxxxxxxxxxxxxxx',
    url: '/authenticate/facebook',
    authorizationEndpoint: 'https://www.facebook.com/dialog/oauth',
    redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host + '/',
    scope: 'email',
    scopeDelimiter: ',',
    requiredUrlParams: ['display', 'scope', 'state'],
    display: 'popup',
    type: '2.0',
    state: function() {
      return 'STATE'
    },
    popupOptions: { width: 481, height: 269 }
  });
```
So in this function we could create the state and set a cookie to store the state client side. One problem I see here is that it isn't easy to inject services into the config. Maybe an interceptor or an additional parameter to the authenticate function would be another option.

After the provider has redirected back to the app, the state parameter must also be posted to the server.

What do you think?

**Comment by sahat** [comment]
I wanted to add this feature way back before public announcement of Satellizer but at the time there were other higher priority tasks and since then I have been working on trying to maintain this project by closing issues and merging pull requests. 

It shouldn't be too difficult to add this to the `Oauth2` service.

**Comment by akkie** [comment]
This would be nice. Can you say if this has a high or low priority to you? Thanks

**Comment by sahat** [comment]
Using approach similar to what you have above here are the changes required in Satellizer:

1. Check if `state` is present in the first place:
```js
oauth2.open = function(options, userData) {
            angular.extend(defaults, options);

            if (defaults.state) {
              // since state is a function, invoke it, then save it into LocalStorage.
              $window.localStorage.state = defaults.state();
            }
...
...
```

2. When building a popup URL + query string, `state` is a special case parameter and needs to be handled separately :

```js
if (paramName === 'state') {
  paramValue = $window.localStorage.state;
}
```

3. After authorization is complete, and right when popup closes, check if state values match:
```js
if (oauthData.state && oauthData.state !== $window.localStorage.state) {
  return $q.reject({ data: 'Invalid state parameter' });
}

I don't like the idea of passing `state` via **authenticate()** function because there is already a second argument `userData` that is designed so you could pass additional data back to the server. And if I were to add state as a third argument it would be just really confusing, not to mention can be ugly too, e.g.
`$auth.authenticate('facebook', null, { state: stateFunc });`.

**Comment by akkie** [comment]
Thanks for your work on that! After thinking a bit around the issue I come to the conclusion that the proposed solution isn't the best way to handle the state because it isn't flexible enough. The first issue I mentioned above is that you cannot inject a dependency into the function. The function could require as example a base64 lib, a cookie service to store the state in cookie instead of the local storage, a lib to generate secure random numbers and so forth. The second issue is that this doesn't work for backend frameworks which tries to validate the state server side or which use the state also to remember some state about the user.

An other solution would be to define a state provider, which a user can extend to fit its needs. This provider should have a `build` and `validate` function. The default provider could use your current implemented logic. And if a user needs another logic he could override the default behaviour.

**Comment by akkie** [comment]
> Would the behaviour be similar to resolve in ngRoute?

Yes, I think this could work.

> I don't see a point of creating and/or validating state value on the server when it can be done just as well on the client. Unless the spec explicitly states otherwise I will keep it as is.

The spec is completely open here. The functionality you've implemented is only a protection against CSRF attacks. But the `state` param isn't bound only to this scenario. This means that the `state` parameter should definitely be passed to the backend server in conjunction with the code.

If you follow my proposal then you could use the default build function as follow:

```js
function(some, dependencies) {
  var state = 'STATE'
  $window.localStorage.state = state;

  return state;
}
```

And the validate function:
```js
function(state, some, dependencies) {
  if (state !== $window.localStorage.state) {
    return $q.reject({ data: 'Invalid state parameter' });
  }
}
```

So a user can implement his own state behavior by overriding the both methods. I think this is a very flexible solution.

**Comment by sahat** [comment]
@akkie You can take a look now at the latest commits to `master` branch.

- Here is how you would set up a provider:
```js
$authProvider.google({
      clientId: '836215426053-98eos0a7yoss4p4oaeahdi2q5c3ocvnp8s.apps.googleusercontent.com',
      optionalUrlParams: ['display', 'state'],
      state: function() {
        return Math.random(); // this just an example
      }
    });
```

- When calling `authenticate()` it checks if state parameter exists and is of a function type (as specified above).
- If it does not, the behavior is the same as before.
- Otherwise, invoke that function and save the value to local storage as  `google_state` (generally `providername_state`).
- When constructing a popup URL, use that state value from localstorage to create `state=ASDF` query param.
- Google (in this case) will return the same `state` parameter on redirect, which is then used it to compare it with state stored in local storage.
- If it does not match: `return $q.reject('OAuth 2.0 state parameter mismatch.');`.
- If it does, however, the `state` is passed in to the server along with other parameters like so:
![screenshot 2015-01-20 20 01 55](https://cloud.githubusercontent.com/assets/544954/5831060/3a6c840a-a0df-11e4-9a94-5ac169173376.png)

I chose to keep it simple and not introduce any extra *state* providers or additional methods `build` and `validate` into the library.

**Comment by akkie** [comment]
Looks good to me. Thanks!

**Comment by RKushnir** [comment]
When using auth token is this necessary? As we are already passing auth token in the request headers, it seems to me another identifier doesn't make it more secure. What am I missing?

**Comment by akkie** [comment]
@RKushnir Do you have read the pages I've linked in my initial post?

**Comment by RKushnir** [comment]
@akkie Do you mean all, including 75 pages of *RFC 6749*? No. If you have read all of them, maybe you could just give me a quick answer :)

BTW, the first link is not valid anymore.
