### ISSUE TITLE
Problem with Facebook Auth on Android Chrome

### ISSUE THREAD

**Issue by carlosazaustre** [sahat/satellizer#240]
Hi all!

I've a problem with facebook authentication on an AngularJS WebApp (with Satellizer) + API Node.js on another server.

The Flow works fine on Desktop (Chrome, Firefox and Safari) on iOS (Safari and Chrome) but on Android (Chrome and Firefox) the Oauth flow stops on the URI: `http://localhost:9000/?code=AQAjwhatever..... and the POST request never reach the API server, and the user never is authenticated.

Anybody knows? Thanks a lot!

FYI: I've tried on Android 4.2.1. On Android 5.0 seems like works.... :S

**Comment by jicasada** [comment]
I'm having the same issue. Have you solved it? With Android 5.1.0
