### ISSUE TITLE
c# example useless

### ISSUE THREAD

**Issue by mika76** [sahat/satellizer#246]
The C# server example at the moment is useless - you have to install a CTP version of Visual Studio to even open the project. How about something which is at least runnable in a currently valid version of Visual Studio?

**Comment by varmint09** [comment]
Why not attempt one? Its an Open Source project.

In any event, if I was wanting to get someone to make something for me (Like an example), I would be much more polite! This is a free, open-source library.

The Angular side of Satellizer is pretty solid, so it should be easy enough to try and write a client-side example against if you have some knowledge of the .NET space.

**Comment by mika76** [comment]
I don't think I was being impolite - I just meant it's useless for the majority of people who would be interested in seeing a working example of this project.

**Comment by sahat** [comment]
You have to understand @mika76 that I don't know enough C# or ASP.NET to quickly create a Satellizer example in a day.

I have other languages on TODO list: Go, Ruby, Scala, Elixir. So, by the time I get to the C# example, Visual Studio 2015 will likely be officially released.

Also, by staying on the bleeding edge I won't have a headache with upgrades in the future.
