### ISSUE TITLE
chrome.storage.local

### ISSUE THREAD

**Issue by bannostookaylo** [sahat/satellizer#247]
So I was pretty excited to find this project and was going to use it in conjunction with  https://github.com/MobileChromeApps/mobile-chrome-apps/blob/master/README.md. I got the log in working in the browser however when I go to run it as a chrome app I get the following error "window.localStorage is not available in packaged apps. Use chrome.storage.local instead."... is there a quick solution to this problem or do I need to find another solution?

**Comment by sahat** [comment]
There is no quick fix at the moment. To do what you want to do I would need to refactor the code and implement something like:

```js
$authProvider.storageType = 'localStorage';
$authProvider.storageType = 'document.cookie';
$authProvider.storageType = 'chrome.storage.local';
```

**Comment by bannostookaylo** [comment]
Ic ... well thank you for responding so quickly. Maybe if I can get something working on my end I'll do a pull request :)

**Comment by bannostookaylo** [comment]
Bah, I hard coded a fix for this but it doesn't look like it will work with the Mobile Chrome Apps project

**Comment by sahat** [comment]
@bannostookaylo did you get it to work with your Chrome app?

**Comment by bannostookaylo** [comment]
@sahat  Half way, right now I have it hard coded trying to get it to work and it seems to work fine doing chrome.storage.local however now I am running into a redirect_uri issue which would be another ticket all together and don't want to take this ticket off course lol.
