### ISSUE TITLE
how can i send additional data to header

### ISSUE THREAD

**Issue by sanamk** [sahat/satellizer#252]
I am using laravel for the server side, in the route for security purpose I am checking for two parameters  api key and a token in header, only if these key  is present the route will allow the further actions. I have done the normal signin and signup with satellizer itself and there i added my header at the place of userData in satellizer.js but while using facebook and google its not possible an error occurred as 401 (unauthorized) . But when I removed the line checking for my api key and token the signin was successful. How can I add these two parameters in the header as this is related to security of my website.

Screen shot of my error : http://prntscr.com/5t4lm9

**Comment by sahat** [comment]
If I understand your intention correctly, you would like to override HTTP interceptor that adds token to the header? And you wish to add an additional piece of information - api key?

```js
.config(['$httpProvider', 'satellizer.config', function($httpProvider, config) {
      if (config.httpInterceptor) {
        $httpProvider.interceptors.push(['$q', function($q) {
          var tokenName = config.tokenPrefix ? config.tokenPrefix + '_' + config.tokenName : config.tokenName;
          return {
            request: function(httpConfig) {
              var token = localStorage.getItem(tokenName);
              if (token) {
                token = config.authHeader === 'Authorization' ? 'Bearer ' + token : token;
                httpConfig.headers[config.authHeader] = token;
              }
              return httpConfig;
            },
            responseError: function(response) {
              return $q.reject(response);
            }
          };
        }]);
      }
    }]);
```

**Comment by sanamk** [comment]
Thank you for your reply. I need to send two piece of data X-Api-Key and csrf token to the header. I don't  know  how to append these two data to the header I don't need to append Authorization to the header.For normal signup I have appended the keys as below:

local.signup = function(user) {
          var deferred = $q.defer();
           
           var headers = {                            
                              'X-Api-Key' : 'jjhjdhjdhfvhf8485jdhfjdhjfdhjfdrgr',
                              'X-Csrf-Token':user.csrf                                      
                             };   
          $http.post(config.signupUrl, user, {headers:headers})
            .then(function(response) {
              if (config.loginOnSignup) {
                shared.saveToken(response, deferred);
              } else {
                $location.path(config.signupRedirect);
                deferred.resolve(response);
              }
            })
            .catch(function(response) {
              deferred.reject(response);
            });

          return deferred.promise;
        };

This function is working perfect but when signin with fb and google its not getting appended.

**Comment by sahat** [comment]
`local.signup` is for email and password login. For OAuth providers you will have to modify this code:

```js
oauth2.exchangeForToken = function(oauthData, userData) {
            var data = angular.extend({}, userData, {
              code: oauthData.code,
              clientId: defaults.clientId,
              redirectUri: defaults.redirectUri
            });
            
            if (oauthData.state) { 
              data.state = oauthData.state; 
            }

            angular.forEach(defaults.responseParams, function(param) {
              data[param] = oauthData[param];
            });

            return $http.post(defaults.url, data, { withCredentials: true });
          };
```

**Comment by sahat** [comment]
Did you get it to work @sanamk ?

**Comment by sanamk** [comment]
Sorry for the delay reply I was on travel so I couldn't reply . Now its
working thank you for your great support.



Best regards,

*Sanam Nath | Account Manager*

Office: *Tamilnadu, Kerala*  | *Ph: 9567966670*

Email: *sanam@qbics.in <http://qbics.in>*  |  Skype: *sanamnath.k*

*www.estia.co.in <http://www.estia.co.in/>*   /   *Software Development*
 /   *Server & Tele-service*
This message is private and confidential. Any views or opinions expressed
are solely those of the author and do not necessarily represent those of
Estia Technologies LLP. If you have received this message in error, please
notify us immediately via email to i <customer.support@infobip.com>
nfo@qbics.in.

**Comment by sahat** [comment]
Great! :+1:
