### ISSUE TITLE
How to use with a fully decoupled app

### ISSUE THREAD

**Issue by amitaibu** [sahat/satellizer#260]
I'd like to use satellizer on a fully decoupled Angular app (i.e. an app that is not served by the server, but runs on Github-pages/ Heroku).

So my problem is that the return callback URI cannot be on the API server - but on the actual app, which in turn should send the Profile info to the server.

Is there an example for such a thing? (I know it's possible to do it with OAuth.io, just looking for a non 3rd party tool to do it)

**Comment by sahat** [comment]
I have a built an app like that using Satellizer here: https://hackhands.com/building-instagram-clone-angularjs-satellizer-nodejs-mongodb/

It uses Dropbox for serving static files (Angular.JS app + Satellizer) and Heroku for serving Node.js back-end.

**Comment by amitaibu** [comment]
Awesome, I'll check it out. Thanks!
