### ISSUE TITLE
npm shows 0.8.8 as latest

### ISSUE THREAD

**Issue by jgentes** [sahat/satellizer#265]
Trying to update to 0.9.0 but npm shows 0.8.8 as the latest available.

**Comment by sahat** [comment]
Thanks, I must have forgotten to do npm publish. Will do that tonight. And better yet a gulp task to update the version and create a new Git tag  would probably be even better.

**Comment by jgentes** [comment]
No biggie, I've downloaded .9 in the meantime :)
