### ISSUE TITLE
Linkedin Login SSl certificate

### ISSUE THREAD

**Issue by aditigoel** [sahat/satellizer#268]
I tried to login with all social networks, i get successful login through facebook , google but when i tried to login through linkedin by followin all same steps , it shows me error "invalid redirect_uri . This value must match a URL registered with the API Key." Is ssl certificate is necessary for linkedin login or for oauth2 authorization.

**Comment by sahat** [comment]
Works fine locally here.

When you create a new API key with LinkedIn the URL you use for **Redirect URL** must match the URL where your app is running. For example, on Heroku these are the settings I had to use:

![screenshot 2015-01-31 16 37 45](https://cloud.githubusercontent.com/assets/544954/5990464/a4b3173a-a967-11e4-8d68-9f7891510c4f.png)
