### ISSUE TITLE
Ability to configure unlink()

### ISSUE THREAD

**Issue by niemyjski** [sahat/satellizer#269]
Currently unlink() does get to a url and nothing else (this may change in the future in the case where you unlink the current account that you logged in with??) 

The issue I'm running into is that I have multiple google accounts linked to my account and I want to unlink a specific account. So I do something like this:

     $auth.unlink(providerName + '/' + providerUserId)

This works great for most providers but when it comes to google it chokes because providerUrserId is a long url that still doesn't work as a parameter in .NET even after escaping it... So I need to do a Post and set the provider user id as the body..

**Comment by sahat** [comment]
This issue is somewhat related to #257. I may provide this as an additional `$authProvider` option to avoid breaking existing server-side implementations of `unlink()`.

**Comment by sahat** [comment]
Added an option to change unlink method to POST. Once you do that, here is how you would send a provider name and potentially some other information.
```js
$scope.unlink = function(provider) {
      $auth.unlink({ provider: provider })
        .then(function() {
        
        });
};
```

**Comment by niemyjski** [comment]
That still doesn't solve the issue for me. You're just posting to the same url as before. I need to post to /unlink/google with a body of http://google.com/really.long.google.provider.user.id and it must go into the body or my api can't handle it (.NET). I think we need an overload of params that sticks what ever we pass it into the body of the post.

**Comment by niemyjski** [comment]
That code above would do two requests because the unlink with provider would do a post/get without all of the information to remove the specific oauth account. So I'd get a http 500 on the first and I'd do the same request in the promise (then), with a body

**Comment by sahat** [comment]
@niemyjski Could you not a make an HTTP request yourself and pass that data to `unlink()` after the promise is resolved?
```js
$scope.unlink = function(provider) {
   // 1. make a request to google.
   //  2. call `$auth.unlink` and pass it an object like `{ provider: 'google', additionalData: data }`, where `data` is an object from the first request to google.

If you look at the source code, when sending a POST request, it expects an object, but it doesn't matter what you put there since it's up to your backend's `POST /unlink` route to handle that.

```js
oauth.unlink = function(provider) {
          if (config.unlinkMethod === 'get') {
            return $http.get(config.unlinkUrl + provider);
          } else if (config.unlinkMethod === 'post') {
            return $http.post(config.unlinkUrl, provider);
          }
};
``` 

So, when making a POST request, `provider` param first of all cannot be a string, and it does not have to be an object containing only the `provider` property.

**Comment by niemyjski** [comment]
My apologies, I missed that :+1: Yeah, that will work, I'll just need to update my route to take an object :). When I looked at it quickly, I thought it was doing the post to the unlinkurl + provider.
