### ISSUE TITLE
Redirect to login if not logged in

### ISSUE THREAD

**Issue by artmees** [sahat/satellizer#271]
Is there an option to require login for certain URLs (or all of them)?

the scenario is as follows, User have a link on the app, when he clicks it and he is not logged in, he should be redirected to login. and after successful login he should be redirected back to where he was going. is that supported ? and If not... how do I achieve this functionality ?

a much simpler description... if a user tries to access `/his_profile` while he is not login... he will go to that template page (but of course without data displayed)...

**Comment by ribomation** [comment]
I was too, looking for a config sample of to lock down a site (or part of).
Preferable, configuartion of using ui-router.

**Comment by artmees** [comment]
I found this module which solved my issue https://github.com/Narzerus/angular-permission

**Comment by ribomation** [comment]
Looks promising. Thanks for the tip and for putting it here for others to find as well.
