### ISSUE TITLE
PHP Example: Update to Laravel 5

### ISSUE THREAD

**Issue by sahat** [sahat/satellizer#272]
http://laravel.com/

**Comment by sahat** [comment]
Too many new changes. If someone would like to create a PR for migrating from Laravel 4.2 to Laravel 5.0 that would great!

**Comment by lozadaOmr** [comment]
Created a [fork](https://github.com/lozadaOmr/satellizer/tree/migrate-to-laravel5.0/examples/server/php) to try and migrate to Laravel 5.0 will create a PR if I manage to get it working sooner.

**Comment by sahat** [comment]
@lozadaOmr Laravel 5 is now live in **examples** directory.

**Comment by lozadaOmr** [comment]
@sahat I see so you just moved Satellizer inside the public directory. Thanks for the heads-up.

**Comment by sahat** [comment]
@lozadaOmr I have tried just about every solution to use a different `public` path but without any luck. Since I am pretty sure I will run into the same problem with Ruby on Rails I have decided to just put everything into `public` folder. I could have used CORS and serve client-side on a different port but that would involve more work across all back-end examples.
