### ISSUE TITLE
API base url

### ISSUE THREAD

**Issue by sabrehagen** [sahat/satellizer#276]
Hi,

Feature request: Is it possible to add a base url for all transactions with the server? Our API is located at /api/v1/, so for example our facebook auth is located at /api/v1/auth/facebook. Rather than setting the url config for every provider with the /api/v1/ prefix, it would be better if we could set it in a global place. Is this doable?

Cheers

**Comment by sahat** [comment]
Doable but unnecessary to keep it in Satellizer.

**Comment by ribomation** [comment]
I also thinks this is a good idea.

**Comment by rliebi** [comment]
Where would you keep it instead?

**Comment by sabrehagen** [comment]
@rliebi we just prefix every url in our provider config with the prefix of our api e.g. https://gist.github.com/sabrehagen/9266a272b460bff33749

**Comment by philippeluickx** [comment]
+1 as well, more DRY.

**Comment by sahat** [comment]
I have added this new feature in https://github.com/sahat/satellizer/commit/6e1ecfee9c16877746536f20d7cdd2f8fb1646c6 and it is currently on the `master` branch.

A new version should be out soon, until then please check it out and let me know if you run into any issues.

**Comment by philippeluickx** [comment]
Very cool, thanks!

**Comment by sahat** [comment]
Added in `0.10.0`

**Comment by sabrehagen** [comment]
Thanks, a logical addition.
