### ISSUE TITLE
Blocked popups causes infinite loop error 

### ISSUE THREAD

**Issue by sabrehagen** [sahat/satellizer#277]
If no popup window is shown because popups are blocked by the browser, the following error will be produced:

 {
    "errorUrl": "http://localhost:3000/landing",
    "errorMessage": "TypeError: Cannot read property 'closed' of undefined",
    "stackTrace": [
        "{anonymous}()@http://localhost:3000/assets/js/satellizer.js:588:28",
        "Array.wrappedProgressback@http://localhost:3000/js/angular/angular.js:11591:88",
        "{anonymous}()@http://localhost:3000/js/angular/angular.js:11559:28",
        "{anonymous}() (Scope.)$eval@http://localhost:3000/js/angular/angular.js:12702:28",
        "{anonymous}() (Scope.)$digest@http://localhost:3000/js/angular/angular.js:12514:31",
        "{anonymous}() (Scope.)$apply@http://localhost:3000/js/angular/angular.js:12806:24",
        "tick@http://localhost:3000/js/angular/angular.js:9048:36"
    ],
    "cause": ""
}

This error will be generated repeatedly and infinitely; I don't know why that is so. See http://i.imgur.com/hLixE1B.png

**Comment by sabrehagen** [comment]
Had a look into it a bit more; if the popups is blocked, the library will try and reference properties of the nonexistent object. I've put in a pull request to fix it. The 'infinite loop' style behaviour was from the 35ms timeout to poll the window.

**Comment by sahat** [comment]
Thanks, I will review your PR over the weekend. Things have been a bit crazy at work with the hard deadline by next week for the upcoming website launch.
