### ISSUE TITLE
support for 'Basic' Authorization header

### ISSUE THREAD

**Issue by vincentbriglia** [sahat/satellizer#285]
Right now to achieve login with a Basic Authorization header I would need to do something like

    $http.defaults.headers.common['Authorization'] = 'Basic ' + btoa($scope.email + ':' + $scope.password);
    $auth.login()

It would be nice if this functionality was embedded into satellizer as a configurable option

**Comment by sahat** [comment]
Don't remember if it was part of the spec or not, but most JWT implementations and examples use Bearer authorization.

**Comment by sahat** [comment]
I am going to close this issue since I've decided to not modify that part of the code. There are so many configuration options in Satellizer now that I am having a hard time to keep track of them myself.

[express-jwt](https://github.com/auth0/express-jwt/blob/master/lib/index.js#L49) enforces `Authorization: Bearer <token>` format as well.

**Comment by KidA001** [comment]
I just want to update this for anyone who comes here looking for the solution. In your satellizer/$authProvider config you can set the following
```
$authProvider.authHeader = 'Authorization'
$authProvider.authToken = 'Basic '
```

Then when you set the token, it will use basic auth. Here is my full config:
```
.config(['$authProvider', function($authProvider) {
    $authProvider.httpInterceptor = true;
    $authProvider.authHeader = 'Authorization'
    $authProvider.authToken = 'Basic '
    $authProvider.google({
      clientId: ...,
      redirectUri: ...,
      url: ...
    });
  }]);
```

**Comment by sahat** [comment]
@KidA001 Yeah this is issue is quite old, support to change "Bearer" was added in https://github.com/sahat/satellizer/pull/333

**Comment by KidA001** [comment]
This is the first result in google if you search `Satellizer Basic Auth` so figured it might be useful to note the update you've made/solution :) - Thank you!
