### ISSUE TITLE
Allow local.login request to be configured as a 'get' or 'post' request

### ISSUE THREAD

**Issue by vincentbriglia** [sahat/satellizer#286]
currently local.login does post requests to the loginUrl, tied to the request from #285 it would be good for that request to be a $http.get

**Comment by sahat** [comment]
Sending loin data in query params using GET request seems just so wrong. I have never seen a single login system that uses GET for login or signup. 

Also see this: http://stackoverflow.com/questions/19794590/http-why-is-wrong-sending-username-and-password-in-get-request

If you really want to get it work with your Basic Aurhentication, the only thing I would recommend is to fork the project and modify it to your needs. It is free and open source work after all. You can do whatever you want with the code.
