### ISSUE TITLE
$auth.setToken in minified version

### ISSUE THREAD

**Issue by dilerarc** [sahat/satellizer#292]
I'm implementing email changing. I want to save the new token which coming from the server after user change an email and have a problem with minified version, which can be found in
//cdn.jsdelivr.net/satellizer/0.9.2/satellizer.min.js

The method **$auth.setToken(myNewToken)** throws the exception:
TypeError: Cannot read property 'false' of undefined
    at Object.e.module.constant.provider.factory.r.setToken (satellizer.min.js:6)
    at Object.e.module.constant.provider.$get.r.setToken (satellizer.min.js:6)
    ...

With the regular version of satelizer it works fine.

Maybe its because of angular di minifying issues?

**Comment by sabrehagen** [comment]
I encountered this too. I'm guessing it is just that the minified version hasn't been 'recompiled' after some recent pull requests/changes. Minification won't break it. Maybe @sahat can update it?

**Comment by sahat** [comment]
I have updated the minifed version let me know if the issue still persists. Try using satellizer.min.js from `master` branch for now. I will bump the version number soon.

**Comment by graineri** [comment]
Is that really the issue? 

My understanding is that $auth.setToken(token, redirect) calls shared.setToken(response, isLinking) with a 'hardcoded' response having an 'access_token' as attribute. 

However, then in shared.setToken() the token itself is being got from response.data which is undefined.

**Comment by ribomation** [comment]
This is the same bug I reported as issue #302
