### ISSUE TITLE
Same provider, different url depending on type of user

### ISSUE THREAD

**Issue by jaybloke** [sahat/satellizer#296]
Depending on the user type, my app asks for different information prior to the user signing up. For example, for an Expert I need to know their current location, and for a regular Member I need to know their skills. So after completing the relevant form and authenticating through FB or Google, my app needs to post to the appropriate endpoint to register this extra information (different endpoint for different user types). The problem is however, (and correct me if I am wrong) that the URL in $authProvider config are hardcoded and the $auth service does not have a provision to change the config on the fly (in this case the url).

The quick (and dirty) way for me to fix this would be to duplicate the various providers and hardwire the url for each callback. e.g. facebook-expert => url: /auth/facebook-expert, facebook-member => url: /auth/facebook-member . Another option is to use the same endpoint but add meta data to the request and then handle on the backend. A little messy though (i.e. separation of concerns) and was hoping for a more elegant solution.

Is there any other way I could tackle this requirement without too much hackery?

**Comment by sahat** [comment]
Hey @jaybloke I can't think of a better way without doing some big changes to the `authenticate()` method and passing dynamic URL to it.

**Comment by jaybloke** [comment]
Hi @sahat, yes... fully understand it might demand some heavy duty changes. I will go with the separate provider hack for now. Thanks.
