### ISSUE TITLE
Prevent satellizer from sending auth header for some requests

### ISSUE THREAD

**Issue by mathpere** [sahat/satellizer#297]
Hi,

I'm wondering if there was a simple way to prevent satellizer from sending authorization header for some requests, ideally a URL list.

All that I could see in issues and source code was to override satellizer config, can you confirm that?

Thanks in advance,

Mathieu

**Comment by sahat** [comment]
Hi @mathpere,

There is no way to send the Authorization header only to certain URLs. You are right, your best bet is to set the `httpInterceptor` option to false and write your own http interceptor.

**Comment by pootzko** [comment]
Hi,

sorry for raising this again, but how do you use the getToken() function then? I can't inject either $auth or $authProvider into my custom interceptor. I guess that's because they depend on $http which seems is not possible?

Thanks

**Comment by pootzko** [comment]
If someone else needs this, I inverted the logic a little bit. Instead of appending the token inside my custom interceptor (what I used to do with tokens before using satellizer), now I am removing them under certain conditions.

For example:

```ts
    public request = (config: ng.IRequestConfig) => {
      config.headers = config.headers || {};

      if (_.startsWith(config.url, "api")) {
        // OLD WAY
        // let token: {} = this.localStorageService.get("token");
        // if (token) {
        //   config.headers["Authorization"] = "Bearer " + token["access_token"];
        // }
      } else {
        // NEW WAY
        config.headers["Authorization"] = undefined;
      }

      return config || this.$q.when(config);
    }
```

If you however have a better approach in mind, please do tell. :)

And thanks for the lib!

**Comment by BAByrne** [comment]
Calling out to API I have no control over and came up with a similar solution to @pootzko's. In my routes.js file I added:

```javascript
    $httpProvider.interceptors.push(function() {
      return {
        'request': function(config) {
          if(config.url.startsWith('http://specificURLHere')) {
            delete config.headers.Authorization;
          }
          return config;
        }
      };
    });
