### ISSUE TITLE
TypeError: Cannot read property 'token' of null

### ISSUE THREAD

**Issue by NetanelBasal** [sahat/satellizer#304]
When i try to connect with facebook i get this error

**Comment by sahat** [comment]
I will need more information than that to try and help you.

**Comment by mhd999** [comment]
I got same Error today : 
`TypeError: Cannot read property 'token' of undefined
    at Object.i.setToken (satellizer.min.js:6)
    at satellizer.min.js:6`
Version of satellizer i use is 0.9.3
