### ISSUE TITLE
Remove server dependencies from main package.json

### ISSUE THREAD

**Issue by larrifax** [sahat/satellizer#314]
It would be great if the dependencies for the node server example weren't declared in the main `package.json`. I'm using npm as my package manager for a project, and having these dependencies declared in the main `package.json` causes an unnecessary slowdown of our build process.

**Comment by sahat** [comment]
I don't like it either, but I added it there so I could do `git push heroku master`. For some reason Heroku does not pick up dependencies in **examples/server/node** directory. Any suggestions on how to fix it? Right now I would have to manually add these dependencies back before doing another push to Heroku, or create a separate branch for Heroku deployment.

**Comment by larrifax** [comment]
I haven't used Heroku before, but what about only pushing the example directory to heroku? See http://stackoverflow.com/questions/26241683/heroku-deploy-a-sub-directory for a way to do this.
