### ISSUE TITLE
Socket authenfication

### ISSUE THREAD

**Issue by Oldwo1f** [sahat/satellizer#315]
Hi everyone,

I am working with Socket.io and i would like to know if there is a way to Intercept socket request to set the correct authorisation headers.

**Comment by sahat** [comment]
@Oldwo1f , I have not tested Satellizer with Socket.io. 
I am not even sure how that would work.

**Comment by Oldwo1f** [comment]
hi

its just not implemented, but i worked around by adding headers manually to my socket request like this 

```
var header = {'Authorization': 'Bearer '+$auth.getToken()};
 $sailsSocket.get("/subscribeNotif",{"headers":header}).then(...........);
```

It would be nice to have an option to intercept socket request and set the authorisation headers, but the workaround is easy so its not very important.

btw thanks for your answer

**Comment by Johnsel** [comment]
I just bumped into the same issue, this is the way I resolved it:

```
function AppConfig(AppConstants, $sailsProvider, $httpProvider, $stateProvider, $authProvider, $locationProvider, $urlRouterProvider) {
var token = localStorage[$authProvider.SatellizerConfig.tokenPrefix+'_'+$authProvider.SatellizerConfig.tokenName]
  var sailsHeaders = {'Authorization': 'Bearer '+token};
   $sailsProvider.url = AppConstants.socketUrl;
  $sailsProvider.defaults.headers = sailsHeaders;
}
```
