### ISSUE TITLE
Error: Expecting a token named "token" but instead got : ..... with message 'cURL error 7: couldn't connect to host

### ISSUE THREAD

**Issue by CoreTea-Solution** [sahat/satellizer#318]
Hallo master, I'm getting error on facebook login, on localhost everything work fine, but after upload to my hosting provider, i'm getting Error: Expecting a token named "token" but instead got : ..... with message 'cURL error 7: couldn't connect to host 

just facebook login, google, twitter, etc work fine

please help
Thanks

**Comment by samuelbeek** [comment]
I have the same problem.

**Comment by elgs** [comment]
Same problem here.

**Comment by sahat** [comment]
You will get that error if token isn't being sent from the server, e.g.
```js
res.send({ token: 'your generated token' });
```

Open Google Chome Developer Tools and look at the Network tab, then inspect /auth/facebook request to check if token is actually being sent over. If not, well there you have it. As for why it wouldn't be sent, my guess is mismatching redirectUri. In other words, you have to use different set of **Client ID** and **Client Secret** and **Redirect URI** for local development and production. For example, I have both *Satellizer Local* and *Satellizer Heroku* Facebook, Google, Twitter, GitHub, etc. apps.

**Comment by elgs** [comment]
No, the token is not sent. The Response is empty, even github has nothing sent back. However, in the backend, I was authorized and got the token, and retrieved user info successfully. This error only happen on facebook. I didn't create separate apps for local and production, I keep changing the url in facebook, github and google websites.

**Comment by elgs** [comment]
The token is not sent by any of the providers, however, only Facebook complains in the console. I opened a modal window for login, which does not cause the url to change. My redirect url is the same as the login url. Is this because of the url is not changed, the token is not sent?

**Comment by elgs** [comment]
I suddenly realized it's the backend responsibility to send back the token which I didn't. So it's my fault. Reading further in the `How It Works` section in the document. @sahat, can you explain a little bit more about: 
```
Server: In both cases of Step 8, create a JSON Web Token and send it back to the client.
```

What is the exact format the browser expect the token to be from the server? Thanks.

**Comment by furyscript** [comment]
Hi, when I make request with this config
```javascript
  clientId: ***,
  url: '/auth/facebook',
  authorizationEndpoint: 'https://www.facebook.com/v2.3/dialog/oauth',
  redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host + '/',
  scope: 'email',
  scopeDelimiter: ',',
  requiredUrlParams: ['display', 'scope'],
  display: 'popup',
  type: '2.0',
  popupOptions: { width: 481, height: 269 }
```

Facebook not return back token, why??

And when I see the error log with
```javascript
$auth.authenticate(provider).then(function(response) {
            console.log(response);
});
```
`
Error: Expecting a token named "token" but instead got: HERE THERE IS MY HTML PAGE
`

Network tab result
```
clientId: "1580575275544727"
code: "AQB64TA1aPOZ39w30OljiITAlDw3vwY_XkxX3Jt-DOTTc5P_E0FmVwRpGxKhqShg033FmdcaAqRVMhUpu4pfn96C7Xgj3eY-R6Ey2P_Bb3uJB7Yzuj0g5p-vplb3jTDH_C7OZ5_Ur-chOQVpKu-9xc-wHyADvc3o4wN6U28TPBHKz06vgIre-Y2DhZyoniL0WA8n5IOthLl3SeH2FqBo0AkOGmXm-G5D-IMqRh8fzzsIFNz3MavW7EkE2dLHy08RozryOd_BGxVm7BoY9rI3eOGD8Bgu59hLaEt4uCqcxg-QRTzqlQoOdD1AtjYf7f-VcLk"
redirectUri: "****.."
```

**Comment by ajbraus** [comment]
+1

**Comment by productank** [comment]
was this resolved?

**Comment by dhwanishah** [comment]
Hey guys, so I'm having this exact issue, but my backend system is made in Spring. And it works on local, but doesn't on production. I've looked at the network tab for both dev and prod and all that should be there is there. The correct parms are being sent (different code and redirectUri of course for dev vs prod) and the response on both of them is nothing returned (no token), but dev is working while on prod it's not. What else could it be that's causing this? Any help appreciated.

**Comment by truongnhan1176** [comment]
Same problem here when i use "satellizer":"^0.15.4" , but when I use "satellizer":"^0.14.1" , it was resolved :dancer:
