### ISSUE TITLE
Need ability to update $authProvider.loginRedirect outside of configuration? 

### ISSUE THREAD

**Issue by martynchamberlin** [sahat/satellizer#319]
For context, please see my SO post: 

http://stackoverflow.com/questions/29036383/how-to-change-satellizers-authprovider-loginurl-inside-an-angular-controller

We really need to be able to change the `$authProvider.loginRedirect` variable based on the contents of $stateParams. Right now it looks like the only way to change that variable is inside the `.config()` Angular function, and unfortunately `$stateParams` isn't accessible inside the configuration function.

Here's a example I'd like the code to look like: 

  	angular.module("PrayerChain").controller("loginCtrl", ["$rootScope", "$scope", "$state", "$stateParams", "$http", "$auth", loginCtrl]);
	
	function loginCtrl($rootScope, $scope, $state, $stateParams, $http, $auth) {
		/** Here's the functionality we currently don't have and would like to have  **/
		$auth.setLoginRedirect( '/settings' );
	}

Thanks! 

**UPDATE:** I had the wrong SO article linked above. Just now fixed that. Oops!

**Comment by amullins83** [comment]
I would envision it as being a parameter passed in to the `login` method. Right now, `login` performs an HTTP post, and then calls `setToken` with the response. The `setToken` method takes a `redirect` parameter and then does nothing with it except check to see if it's there before performing a redirect `config.loginRedirect`. So, my vision is that we edit the `setToken` method to actually redirect to the given URL (if there is one), and edit `login` to optionally provide that parameter to `setToken`. Then you could call it like:

    $auth.login(userCredentials, '/settings');

**Comment by martynchamberlin** [comment]
Bingo, @amullins83. Love it.

**Comment by amullins83** [comment]
Oh man, the master branch was updated since I pulled it, so I'm going to have to do some conflict resolution before I can submit a PR. You can check out [my branch](https://github.com/amullins83/satellizer) in the meantime. I won't be able to work on this over the weekend, unfortunately.

**Comment by sahat** [comment]
I totally agree, it's a valid use case, although not something I needed at the time when I created Satellizer. Thanks @amullins83 for sending the pull request. :+1:

**Comment by amullins83** [comment]
Glad to be of service!

Austin Mullins
