### ISSUE TITLE
Using "*" in package.json causes error

### ISSUE THREAD

**Issue by varmint09** [sahat/satellizer#327]
Hello,

Something must be configured wrong with this package on npm, if I use     

`
"satellizer": "0.9.4"
`

in my package.json it works, but if I use 

`
"satellizer": "*"
`

It brings down a version 1.0 npm file, and then it won't build.

Many thanks!

**Comment by sahat** [comment]
I don't know why npm pulls version `1.0` considering that it has never been released. In any case it's a bad practice in the Node.js community to use `*`. 

Use  "satellizer": "^0.9.4" or  "satellizer": "~0.9.4" instead.
