### ISSUE TITLE
Suggestion for Twitter

### ISSUE THREAD

**Issue by varmint09** [sahat/satellizer#329]
I do have Twitter Authentication working, however it's worth adding some further details to the documentation I feel.

Firstly,

If the /auth/twitter is on a different host (I run the server as a separate client), make sure that the /auth/twitter responds to GET types, the routes for /auth/facebook and /auth/google need to reply to POST requests so the fact Twitter was different threw me a little. (You might want to mention what requests are made for other service types?_

Secondly, you might want to add a note to this affect;

When creating a Twitter Application, it will not allow you to add localhost or 127.0.0.1 domain to the App, but just enter basically any suitable valid URL, and tick the allow Twitter Login Access box.

In the Application itself, the callback url comes the callback you add into the function called when the /auth/twitter route is hit.

Overall though, adding Twitter support was painless.

==
Although I do notice the User Avatar and Name are not returned in the login request, could that be added in as a request to the Twitter method?

**Comment by varmint09** [comment]
No comment? Seems like it would be useful to return the profile details that we will commonly need, even your examples have placeholders for thumbnailed avatars?

**Comment by kmaida** [comment]
I tried adding the Twitter avatar to the request. I used `user.picture = profile.profile_image_url` in a node backend. However, I'm having other issues with my database, so maybe try adding something like this, and I'll be interested to know if it works on a functional implementation (since I wouldn't exactly call mine functional at this time). In any case, I believe that `profile_image_url` is what you're looking for to grab the avatar.

**Comment by varmint09** [comment]
Whilst that may be the field to look for, the code you are using/satellizer will do nothing as the response does not contain an object with that property, its just the bare minimum oauth access details, but it doesn't then go and use them.

@sahat I think it would be a worthwhile addition if somewhere in the auth process, the following API call was added; 

https://api.twitter.com/1.1/users/show.json?screen_name=X
https://dev.twitter.com/rest/reference/get/users/show

This would then allow anyone using Satellizer to extract the profile data they need from Twitter to populate their system. I would very much like access to the name, and profile_image_url property.

Or perhaps a new part of Satellizer which provides access to profiles for the networks you provide access to... its just fortunate that Facebook defaults to provide plenty.

Regards,

V

**Comment by varmint09** [comment]
Hi,

Am I the only one who would like consistent profile data from the services? :) I think the request makes sense, we have Twitter login, but we don't have a way of extracting the profile data, it would be good if the demo included proper profile data for each service.

**Comment by sahat** [comment]
@varmint09 I will take a look at your suggestions shortly. There was a pull request sometime ago which also suggested to use POST request for Twitter or any other OAuth 1.0 provider.

I'll update README with your callback url tips and suggestions.

As for the avatar I did not get a chance to add it for all providers. Only Foursquare, Facebook and a few others support it at the moment. Again, it all comes down to time. I wish I had more of it. I'll add profile avatar to Twitter when I am going to refactor that route.

**Comment by sahat** [comment]
> @sahat I think it would be a worthwhile addition if somewhere in the auth process, the following API call was added;

https://api.twitter.com/1.1/users/show.json?screen_name=X
https://dev.twitter.com/rest/reference/get/users/show

This would then allow anyone using Satellizer to extract the profile data they need from Twitter to populate their system. I would very much like access to the name, and profile_image_url property.

Ok I will add that as well. Since I initially was not planning to get any additional information, that's why I stopped `https://api.twitter.com/oauth/access_token`.

**Comment by sahat** [comment]
Take a look at the `master` branch when you get a chance @varmint09. I have updated server-side example for Twitter as well OAuth 1.0 behavior in Satellizer.

With Twitter or any other OAuth 1.0, it now opens an empty popup with `window.location.href =  ""`, makes a `POST` request to the server, gets `oauth_token` and `oauth_verifier` from Twitter, which is then used to redirect that empty popup window to the Twitter authorization page, from there the behavior is just like OAuth 2.0.

I had to modify some of the underlying API so please do report any bugs that you run into with OAuth 1 or OAuth 2 providers.

**Comment by varmint09** [comment]
I will review this tonight. Many thanks @sahat

**Comment by super-kamil** [comment]
The node example at 0.10.1 is broken... just lost 2h for debugging :(

It still makes app.get, but the example is for app.post. Changing it to app.get ends with json output. 0.10.0 works for me now.

**Comment by Vincent-Noben** [comment]
@super-kamil 
How did you fix it?
I'm using the latest node and client example (although I seperated them as 2 independent hosts)
If I try to link my twitter account it opens the callback url in the popup screen instead of going to the server etc... I assume it has to do with what you're saying.?

**Comment by super-kamil** [comment]
I had the same problems, i think. Here is my solution:

node:

```javascript
app.get('/api/auth/twitter', function(req, res) {
    var requestTokenUrl = 'https://api.twitter.com/oauth/request_token'
      , accessTokenUrl = 'https://api.twitter.com/oauth/access_token'
      , authenticateUrl = 'https://api.twitter.com/oauth/authenticate';

    if (!req.query.oauth_token || !req.query.oauth_verifier) {
      var requestTokenOauth = {
        consumer_key: config.TWITTER_KEY,
        consumer_secret: config.TWITTER_SECRET,
        callback: config.TWITTER_CALLBACK
      };

      // Step 1. Obtain request token for the authorization popup.
      request.post({url: requestTokenUrl, oauth: requestTokenOauth}, function(err, response, body) {
        var oauthToken = qs.parse(body);
        var params = qs.stringify({oauth_token: oauthToken.oauth_token});

        // Step 2. Redirect to the authorization screen.
        res.redirect(authenticateUrl + '?' + params);
      });
    } else {
      var accessTokenOauth = {
        consumer_key: config.TWITTER_KEY,
        consumer_secret: config.TWITTER_SECRET,
        token: req.query.oauth_token,
        verifier: req.query.oauth_verifier
      };

      // Step 3. Exchange oauth token and oauth verifier for access token.
      request.post({url: accessTokenUrl, oauth: accessTokenOauth}, function(err, response, profile) {
        profile = qs.parse(profile);

        // Step 4a. Link user accounts.
        if (req.headers.authorization) {
          UserModel.get({twitter: profile.user_id}, function(err, existingUserModel) {
            if (existingUserModel) {
              return res.status(409).send({message: 'There is already a Twitter account that belongs to you'});
            }
            var token = req.headers.authorization.split(' ')[1];
            var payload = jwt.decode(token, config.TOKEN_SECRET);
            UserModel.get({id: payload.sub}, function(err, user) {
              if (!user) {
                return res.status(400).send({message: 'UserModel not found'});
              }
              UserModel.twitter = profile.user_id;
              UserModel.displayName = user.displayName || profile.screen_name;
              UserModel.update(user, function(err) {
                res.send({token: createJWT(user)});
              });
            });
          });
        } else {
          // Step 4b. Create a new user account or return an existing one.
          UserModel.get({twitter: profile.user_id}, function(err, existingUserModel) {
            if (existingUserModel) {
              var token = createToken(existingUserModel);
              return res.send({token: token});
            }
            UserModel.twitter = profile.user_id;
            UserModel.displayName = profile.screen_name;
            UserModel.save(function() {
              var token = createJWT(user);
              res.send({token: token});
            });
          });
        }
      });
    }
  });
```

**Comment by Vincent-Noben** [comment]
@super-kamil I tried it but even when I have my client on same host as server this does not work.
Is this version 0.10.0? Because I tried that as you suggested and that didn't work eighter. Maybe you have an older satellizer.js file too?

**Comment by super-kamil** [comment]
i'm using npm "satellizer": "^0.10.1" and bower "satellizer": "~0.10.1",

**Comment by sahat** [comment]
@super-kamil use the satellizer.js on `master` branch.

**Comment by mkdeepan** [comment]
@sahat here I too facing a problem and little confused with @varmint09 ...! Do I need to use post or get method? Here im using post but popup comes with empty url and I couldn't get oauth_token and oauth_verifier.. Could you solve tis
