### ISSUE TITLE
Strange behaviour when deployed

### ISSUE THREAD

**Issue by miguel-vila** [sahat/satellizer#334]
Hi,
First of all thanks for your work. We have the frontend and the backend in separate servers and for the moment we are trying to authenticate users using only google. In our local environments it works fine, but when we deploy to heroku (I'm not sure if that's relevant, it may be a configuration issue) it has a strange behaviour. Sometimes it works fine but sometimes when we click in our "Sign in with Google" button the popup doesn't show the google login page but our login page. We are trying to find a sequence of steps which reproduces this problem but we haven't been able to, sometimes it happens, sometimes it doesn't. This is our setup:

```javascript
$authProvider.google({
    clientId: 'our-google-client-id',
    url: ENV.apiEndpoint+'/v1/authenticate/google',
    authorizationEndpoint: 'https://accounts.google.com/o/oauth2/auth',
    redirectUri: ENV.redirectUri || window.location.origin || window.location.protocol + '//' + window.location.host,
    scope: ['profile', 'email'],
    scopePrefix: 'openid',
    scopeDelimiter: ' ',
    requiredUrlParams: ['scope'],
    optionalUrlParams: ['display'],
    display: 'popup',
    type: '2.0',
    popupOptions: { width: 580, height: 400 }
});

// Auth config
$authProvider.httpInterceptor = true; // Add Authorization header to HTTP request
$authProvider.loginOnSignup = true;
$authProvider.loginRedirect = null;
$authProvider.logoutRedirect = '/';
$authProvider.loginUrl = '/login';
$authProvider.loginRoute = '/login';
$authProvider.tokenName = 'token';
$authProvider.tokenPrefix = 'satellizer'; // Local Storage name prefix
$authProvider.authHeader = 'X-Auth-Token';
```

The environment variable `ENV.redirectUri` is set to `'http://our-app.herokuapp.com/'`

Any idea in what configuration error, if any, may be causing this?

**Comment by jgentes** [comment]
It may have something to do with https vs. http in your redirectUri setting. Are you using Node on the backend? Oftentimes the order of your route setup can cause issues, although a problem there would usually create a consistent problem, not intermittent.

**Comment by miguel-vila** [comment]
@jgentes for the moment the redirectUri is 'http' (we plan to change this in the future). In fact I think it should be enough with `redirectUri : window.location.origin || window.location.protocol + '//' + window.location.host`, right? (I think we had to do that because a silly mismatch between the server's redirect URL, the authorized redirect URL's in the google app and the redirect URL in satellizer). 

We are not using Node, but I think the problem is not in the server side. In fact the error happens before the token exchange. While debugging I think I found the reason. While polling the popup the first condition [here](https://github.com/sahat/satellizer/blob/bc4a59e595e462353d73b52c39d965141bccfd77/satellizer.js#L643) is met but the second one doesn't. I think it may have something to do with the html5Mode. Why that second condition is needed?

**Comment by jgentes** [comment]
I'm not sure why that second condition is there.. I'm just not familiar enough with satellizer. But from my setup, I can tell you:

1. My $authProvider settings only include clientId - I didn't change any of the other settings. It literally looks like this:
```
app
  .config(function($authProvider) {

    $authProvider.linkedin({
      clientId: "myclientid"
    });

  })
```

2. I've got a fairly complicated setup, with an HTML page rendered as the frontend ('/') and my angular app running at '/app', and I can tell you that my redirect still goes to '/' not '/app' which I initially thought it might, since the Oauth process is initiated from /app. My server includes this for HTML5mode support, which might be where your problem is:
```
// Frontend Homepage & Blog
app.get('/', function (req, res, next) {
  res.sendFile("frontend.html", {root: __dirname + config.path});
});

// Backend App
app.get('/*', function (req, res, next) {
  res.sendFile("app.html", {root: __dirname + config.path});
});
```

**Comment by miguel-vila** [comment]
I think we may have solved it by changing the redirect URL from `http://our-app.herokuapp.com/` to `http://our-app.herokuapp.com/login` on the server side and on the front end side (which I'm not sure why is needed, maybe because the `popupWindow.location.hash` part of the condition?). 

I'm gonna close this issue when we confirm it.
