### ISSUE TITLE
Titanium integration

### ISSUE THREAD

**Issue by vanderleisp** [sahat/satellizer#336]
I'm doing some tests as to use Satellizer in a hybrid app being develop as a webview on Titanium cross-platform tool.
Sorry for the two silly questions, but how to open the authentication window inside the same actual window, instead of opening a new window accessing the providers ?? somehow to opening a new window on titanium it's crashing and I still didn't find solution for this so keeping the authentication process inside same window seems a workaround.
Also inside Titanium I couldn't use the /#/home or /#/login or /#/signup so had to change to #/login otherwise it couldn't find the link addresses.

**Comment by sahat** [comment]
Hi @vanderleisp, I don't know what to tell you. This is not a discussion forum for Titanium, nor do I have any experience whatsoever with Titanium. Your best bet may be to take a look at the PhoneGap pull request https://github.com/sahat/satellizer/pull/288 or take a look at the Ionic in the **examples** folder. Besides that I am afraid I cannot help you out.

**Comment by vanderleisp** [comment]
thanks, and I'll check these two ref you mentioned.
