### ISSUE TITLE
TypeError: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by javacado** [sahat/satellizer#337]
Hello

First, thanks for this great module. I use it in my angular website, but now am trying to get it to work on the hybrid app I am working on.

I am getting the token from the server:
![image](https://cloud.githubusercontent.com/assets/3268456/6931764/e77ba2a8-d7c5-11e4-9879-cf841d85b66d.png)

but when I use $auth.setToken(data) I get an error that response.data is undefined. Am I supposed to send more data into .setToken() other than an object with just the token?  

Here is the error:
![image](https://cloud.githubusercontent.com/assets/3268456/6931761/d41db75a-d7c5-11e4-9e41-91925aadec3b.png)

also just for FYI, this is the corresponding line (278) in the satellizer.js file:
![image](https://cloud.githubusercontent.com/assets/3268456/6931795/3ea94f3a-d7c6-11e4-96e2-05e55c44d3e3.png)

**Comment by gkohen** [comment]
I'm getting the same using version 0.9.4 intermittently in Chrome (especially when the devtools are visible) and more often in IE11:
TypeError: Unable to get property 'token' of undefined or null reference
   at shared.setToken (http://localhost:8091/lib/satellizer/satellizer.js:294:13)
   at Anonymous function (http://localhost:8091/lib/satellizer/satellizer.js:365:15)
   at processQueue (http://localhost:8091/lib/angular/angular.js:13248:11)
   at Anonymous function (http://localhost:8091/lib/angular/angular.js:13264:27)
   at Scope.prototype.$eval (http://localhost:8091/lib/angular/angular.js:14466:9)
   at Scope.prototype.$digest (http://localhost:8091/lib/angular/angular.js:14282:15)
   at Scope.prototype.$apply (http://localhost:8091/lib/angular/angular.js:14571:13)
   at tick (http://localhost:8091/lib/angular/angular.js:10428:25)

**Comment by gkohen** [comment]
This still persists in 0.10.1. On IE11, with responseType:'token' it consistently happens. It seems like response.data does not have any value in the response.data object. Instead, in the response object I see:
```
/access_token:	"myfakereturnedtoken" //Isn't this weird there is a slash before the key name?
authuser	:"0"
expires_in:	"3600"
prompt:	"consent"
session_state:	"myfakesessionstate"
token_type:	"Bearer"
```
@sahat , would the right approach been to check if there is a data object and then if not fall back to the values in the actual response? 
Let me know if you're already on in or I should start a fork and PR.
Thanks for an otherwise awesome piece of software!

**Comment by gkohen** [comment]
Pull request related to the issue has been submitted https://github.com/sahat/satellizer/pull/394

**Comment by sahat** [comment]
Closing an old issue.
