### ISSUE TITLE
Yii2 with Satellizer

### ISSUE THREAD

**Issue by mtangoo** [sahat/satellizer#345]
I have Yii2 REST API driving Angular app. I have send username and password to Yii2 but am confused as to How I should return format that I'm supposed to make. In Satellizer docs it says I should return JWT. Frankly I have never worked with JWT and google was of little help.

Laravel added to my confusion as I did not know what it really does (the classes). Any Plain PHP example? If no how can I return correct format with PHP? To be specifc, am asking about error message and success.

**Comment by sahat** [comment]
@mtangoo I don't have enough expertise to help you out with Yii2 or pain PHP example. I put together that Laravel example just by following Laravel documentation with very little knowledge of PHP.

Any language you use, you will have to get a library for dealing with JWT. For example:

- **Node.js** - https://github.com/auth0/node-jsonwebtoken
- **Python** - https://github.com/jpadilla/pyjwt
- **PHP ** - https://github.com/firebase/php-jwt which is specified in `composer.json`:
```json
"require": {
    "laravel/framework": "4.2.*",
    "guzzlehttp/guzzle": "4.2.1",
    "firebase/php-jwt": "dev-master",
    "guzzlehttp/oauth-subscriber": "0.1.2"
  },
```

You only have to look at a specific code snippet of JWT and ignore everything else Laravel-related - classes, controllers, models, configs.

You can see how I use `JWT::decode`` and `JWT::encode` functions in here:
https://github.com/sahat/satellizer/blob/master/examples/server/php/app/controllers/AuthController.php

**Comment by mtangoo** [comment]
I finally got it working. When I find spare time I will write short tutorial and Post it here

**Comment by sahat** [comment]
Ok, I am going to close this issue, but feel free to comment on it when you are ready. This would be helpful to someone else who stumbles upon this GitHub issue in the future.

**Comment by mtangoo** [comment]
:+1:

**Comment by wfcreations** [comment]
I'm working in yii2 extension, authentication with facebook is now ready

https://github.com/wfcreations/yii2-satellizer-server
