### ISSUE TITLE
Same origin (domain) validation on popupWindow

### ISSUE THREAD

**Issue by arterzatij** [sahat/satellizer#349]
the validation for this is currently

 " if (popupWindow.document.domain === document.domain && (popupWindow.location.search || popupWindow.location.hash)) "

But if I have my oauth service on mydomain.com:9000, and my app client on mydomain.com, this validation will pass, and close my popup.

But same origin policy, stablish  domain + port is a validation for same origin ,
https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy

**Comment by WARrior-Alex** [comment]
Hey. What is wrong with ``document.domain`` check? If this value was set both for main window and popup to the same domain, main window has full access to popup content! And this property is one of allowed ways for same origin policy.

Here is note about port setting: [Changing_origin](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy#Changing_origin). 

BTW, the ``document.domain`` setting works well in IE 9+.

**Comment by arterzatij** [comment]
document.domain return only "mydomain.com" but id I have my OAuth service on port 9000 and my client on port 8080. That evaluation will be "mydomain.com" === "mydomain.com", and the popup will close due a same origin for both. But the same origin evaluation is not just the domain.

That's why I propose a modification for this validation.
