### ISSUE TITLE
Problem exchanging code for token

### ISSUE THREAD

**Issue by misterch0c** [sahat/satellizer#352]
I used the node example code in my backend. I use angular on the frontend, twitter auth works fine. But not facebook. I monitored the requests and I see that when the popup closes a GET on /user/login is made but the code is not in parameter. I only get in in the refer. Also before that a POST is made on :8080?code=zaea...

I get this error from the server:
```
{ error: 
   { message: 'An active access token must be used to query information about the current user.',
     type: 'OAuthException',
     code: 2500 } }
```

Here's a screenshot of the request made http://i.imgur.com/wX0lZBs.png
See something wrong here?
If you want to check the code it's basically this:
https://github.com/marley-nodejs/Two-Tier-Enterprise-App-and-API-Development-with-Angular-and-Sails/tree/master/socialfleet
Except I took the code for facebook and not twitter here: https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js and changed provider 'twitter' for 'facebook'.

I checked and I get the access token. So the error is after when I call the graph api on this line https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js#L472

edit: got it working. There was a parse on the accesToken, idk why but after the parse the token was empty...
But now I can't make it work in my real frontend app. The windows open and then I'm on facebook page 'this page is not accessible'...

**Comment by clarle** [comment]
Hi @misterch0c,

Glad you were able to fix your original issue!  For your edit, you likely need to set page visibility settings on your Facebook app.

See here for more details:

http://www.jeffkee.com/when-facebook-page-widgets-give-you-a-visibility-warning/

Let me know if you have any other questions!
