### ISSUE TITLE
Example on how to implement the "Remember me"

### ISSUE THREAD

**Issue by robotiko** [sahat/satellizer#353]
Hi, 

First goes first, thank you for just incredible contribution!  :D

I'm wandering what would be the best solution for the classical "remember me" or "keep me logged"  for  a fixed time.
I'm newbie here and mainly had a look at documentation, the example and some late issues about session and local storage that give me the idea that a remember me is probably to tied and deeply related to the internals of the lib.
The only reference I have is the PassportJS  strategy that is cookie based (https://github.com/jaredhanson/passport-remember-me)  so not useful at all. 

Any suggestion, guideline? 

thank you

**Comment by philippeluickx** [comment]
A great resource to understand all of it better for me was https://hackhands.com/building-instagram-clone-angularjs-satellizer-nodejs-mongodb

Not really a "remember me" checkbox, but a way of keeping a user logged in at least.

Hope it helps!

**Comment by robotiko** [comment]
Hi philippeluickx, 
thanks for the link, I already knew it , but as you said, not covering the remember me :(

Lets see if we get any light in here :)

Thanks for the help!

**Comment by luis-lf** [comment]
You can set the token expiration time to x days when your user checks the remember me check box.

In the article the token will be valid for 14 days:

```javascript
function createToken(user) {
  var payload = {
    exp: moment().add(14, 'days').unix(),
    iat: moment().unix(),
    sub: user._id
  };
 
  return jwt.encode(payload, config.tokenSecret);
}
```
