### ISSUE TITLE
Server examples: Sinatra vs Rails and Lumen vs Laravel? [resolved]

### ISSUE THREAD

**Issue by sahat** [sahat/satellizer#358]
I am only going to support one or the other, not both, that's why I wanted to see what would you like to see in the `examples` folder.

**P.S.** If you haven't heard of [Lumen](http://lumen.laravel.com), it's a new microframework by the Laravel team which is similar to Express, Flask, Sinatra.

*Final verdict*: Rails and Laravel.

**Comment by sahat** [comment]
Ruby: @luseerr @tagazok @simonasdev, @i8ramin @tbandixen, @ericpeters0n, @motric.

PHP: @ElnasrIT, @tarex, @Oxicode, @mtangoo, @lozadaOmr, @jlievano, @jmrhib, @sakoh, @TolotraRam, @ravivit9, @alejandro145, @IceCreamSushi, @ojhaujjwal, @aminemat,

**Comment by luseerr** [comment]
My vote goes for Rails. Having some real problems with CORS dunno why.
Thanks for pinging me!

**Comment by IceCreamSushi** [comment]
Don't know if the vote is between PHP vs Rails, or a framework vs the other. For PHP, I have to say that I'm pretty excited by Lumen. :)

**Comment by arterzatij** [comment]
rails

**Comment by tagazok** [comment]
Rails of course ^^

**Comment by lozadaOmr** [comment]
I'd still go with Laravel :)

**Comment by mtangoo** [comment]
Yii is not one of the options? IMHO Yii2 is simple to follow and should be one of options.
If it cannot be then Laravel of course!

**Comment by simonasdev** [comment]
We should consider the fact that auth is handled just by plain ruby code, not by a gem which is compatible with rails or sinatra. Rails should be the choice just because it's more popular, so more people are comfortable using it. Too bad there isn't a good solution for specifying the public folder path for rails

**Comment by bigali** [comment]
laravel of course ;)

**Comment by dragonfire1119** [comment]
I vote for lumen. It's great for building apis.

**Comment by TolotraRam** [comment]
Laravel for sure, didn't have time to see lumen but in my opinion Laravel is "quite" mature, and with just a quick look in the doc i didn't see any real difference betwen with both.

**Comment by anonymoussc** [comment]
Laravel 5

**Comment by ericpeters0n** [comment]
Rails, please. :)

(Are people still developing in php?)


Eric Peterson

**Comment by aminemat** [comment]
@ericpeters0n : PHP is 80% of the web, Are people still developing in rails ?

**Comment by ericpeters0n** [comment]
Valid question. :) Of course, insomuch as satellizer is designed to interface with existing “legacy” backends, these are all valid answers.


On April 20, 2015 at 11:20:50 AM, Amine Matmati (notifications@github.com) wrote:

@ericpeters0n : PHP is 80% of the web, Are people still developing in rails ?

**Comment by jmrhib** [comment]
Lumen seems like a much more sane choice than Laravel. It is totally overkill if the purpose is just authenticating and a REST api for pushing/pulling data.

Lumen looks quite appealing. Actually I had so much trouble installing Laravel that I re-wrote most of the example in Slim instead. If you guys want I can post (to github) what I have.

I will not go into the Rails/PHP debate, since I have never used Rails and don't know the pros/cons.

**Comment by motric** [comment]
I vote for rails :)



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=6.3.7&pv=5.1]

On sab, apr 18, 2015 at 12:01 AM, IceCreamSushi < notifications@github.com [notifications@github.com] > wrote:
Don't know if the vote is between PHP vs Rails, or a framework vs the other. For
PHP, I have to say that I'm pretty excited by Lumen. :)

—
Reply to this email directly or view it on GitHub
[https://github.com/sahat/satellizer/issues/358#issuecomment-94085183] .[https://github.com/notifications/beacon/AEBAWidO7QvxphUMU1-CGOfdWWafMc85ks5oAXozgaJpZM4EDEpj.gif]

**Comment by sahat** [comment]
I have just finished porting Laravel 4 to Laravel 5. Please check out **examples/php** directory. Ruby on Rails will be next.
