### ISSUE TITLE
cookie fallback if local storage is not avliable

### ISSUE THREAD

**Issue by tianxu0836** [sahat/satellizer#369]
I suggest to use this AngularJS module, it provides the access to the browsers local storage with cookie fallback 
https://github.com/grevory/angular-local-storage

**Comment by sahat** [comment]
Hi @tianxu0836, there was a discussion about this a long time ago, but ultimately decided not to support cookies since local storage is so widely supported now. I also want to keep Satellizer a stand-alone library without any dependencies.
