### ISSUE TITLE
Setting $authProvider.loginUrl appends the URL

### ISSUE THREAD

**Issue by michaeyk** [sahat/satellizer#370]
$authProvider.loginUrl = 'http://myapi.com/auth/local';
    $authProvider.signupUrl = 'http://myapi.com/api/users';

Subsequent POSTs are routed to http://localhost:9000/http://myapi.com/api/users and http://localhost:9000/http://myapi.com/auth/local.

**Comment by michaeyk** [comment]
Okay... I just found $authProvider.baseUrl in the source. Maybe it could be added to the README.

**Comment by sahat** [comment]
Thanks, will add it right now.

**Comment by sahat** [comment]
adbc9f9e6082986b93e27aa3716f42cbd5deb3c5 allows you to set `baseUrl` to `null` so you could still use loginUrl and signupUrl as before, thus avoiding "double urls" like *http://localhost:9000/http://myapi.com/auth/local*
