### ISSUE TITLE
Laravel 5 : try catch

### ISSUE THREAD

**Issue by bryanrscott** [sahat/satellizer#371]
Hi

Still feeling my around php and git.  Not sure how to do this via github.

Just wanted to make a small suggestion on the demo php server code.  In App\Http\Middleware\Authenicate in the function handle it might be good to wrap the JWT decode in a 
try catch just in case a bad token is passed to ensure json is still returned?

ie
            try {
                $payload = (array)JWT::decode($token, Config::get('app.token_secret'), array('HS256'));
            } catch (\Exception $e) {
                return response()->json(['message' => 'Something went wrong with authentication'], 401);
            }

**Comment by sahat** [comment]
Yeah it's a good idea. I skipped it for the sake of an example where I assume other users will use it as intended, but it goes without saying that in production you should always handle potential error cases.

I'd update the code, but I am using `$payload = (array)JWT::decode($token, Config::get('app.token_secret'), array('HS256'));` throughout many examples in AuthController.php and I don't feel like adding try/catch to every single instance.

Ideally,
```js
$token = explode(' ', $request->header('Authorization'))[1];
 $payload = (array) JWT::decode($token, Config::get('app.token_secret'), array('HS256'));
```
should be refactored into a function but I am not sure how to have a shared function that I could use inside all controllers in Laravel 5.
