### ISSUE TITLE
Paypal auth using auth2

### ISSUE THREAD

**Issue by Murwa** [sahat/satellizer#372]
Hey @sahat, I have an issue authenticating paypal as a provider using auth2. This is my config
```js
$authProvider.oauth2({
    url: 'auth/paypal',
    name: 'paypal',
    scopeDelimiter: null,
    clientId: '<client_id_here>',
    redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host,
    popupOptions: { width: 580, height: 400 },
    authorizationEndpoint: "https://api.sandbox.paypal.com/v1/oauth2/token",
    responseParams: null,
    requiredUrlParams: ['grant_type'],
    optionalUrlParams: null,
    defaultUrlParams: ['response_type', 'client_id', 'redirect_uri'],
    responseType: 'code'
})
```

From [paypal docs](https://developer.paypal.com/docs/integration/direct/make-your-first-call/) 
>In the request body, set grant_type to client_credentials

How do i do that based on the config above?

**Comment by sahat** [comment]
@Murwa try the following:

```js
$authProvider.oauth2({
    name: 'paypal',
    url: '/auth/paypal',
    clientId: '<client_id_here>',
    authorizationEndpoint: "https://api.sandbox.paypal.com/v1/oauth2/token",
    requiredUrlParams: ['grant_type'],
    grantType: 'client_credentials',
    popupOptions: { width: 580, height: 400 }
})
```

**Comment by Murwa** [comment]
Thanks @sahat but still I can't get the token response

**Comment by sahat** [comment]
What error are you getting? That code above sounds about right, so the only other issue I could think of is the problem with your back-end implementation or redirectUri mismatch.

**Comment by sahat** [comment]
@Murwa any luck?

**Comment by sahat** [comment]
So after looking more into it, it seems there isn't a way to integrate Satellizer with Paypal. There should be a way for you to redirect to *authorization screen* where you give your permissions to access your information (like with Google, Facebook, Twitter). When you press *Agree/Accept* it should then do request to `"https://api.sandbox.paypal.com/v1/oauth2/token"` on the server where you pass client id, client secret, grant_type. 

But unfortunately I haven't found any documentation on Paypal's website to achieve this flow.

**Comment by Murwa** [comment]
@sahat I had to do a full page refresh, couldn't find a better way out. Thanks for helping

**Comment by franbueno** [comment]
Hey @Murwa Can you show they way you used to fix it? Thanks!
