### ISSUE TITLE
signupRedirect overrided by loginRedirect when loginOnSignup is set to true

### ISSUE THREAD

**Issue by mastermind1981** [sahat/satellizer#373]
Hi,

I have the following configuration :

    $authProvider.loginUrl = 'http://localhost:8080/cars/auth/login';
    $authProvider.signupUrl = 'http://localhost:8080/cars/auth/register';
    $authProvider.signupRedirect = '/completeprofile';
    $authProvider.loginRedirect = '/profile';

When the user signs up i want him to get logged in and i want to redirect him to '/completeprofile, so he can add more info.

My problem is when he is getting logged he is redirected to loginRedirect  route. How could i hack it to have redirection to signupRedirect route?

Thanks in advance,

**Comment by sahat** [comment]
For your particular use case I think it's best to set loginRedirect and signupRedirect to null and do it yourself.

Both login() and signup() functions return a promise when it is successfully completed. So inside that promise you can manually add ` $location.path('/completeprofile')`.

**Comment by JaKXz** [comment]
It would be great if there was a way to override the `loginRedirect` and have it behave as a fallback if nothing else is specified in the `$auth.authenticate` or `$auth.login` methods

**Comment by sahat** [comment]
I assume you both have resolved it, so I am closing this issue. If not, then feel free to re-open this issue.
