### ISSUE TITLE
ionic white screen after facebook login

### ISSUE THREAD

**Issue by countrdd** [sahat/satellizer#376]
getting a white screeen after facebook login...

this shows up in Xcode Logs.

015-04-27 23:00:17.283 Sidemenu[6179:318069] webView:didFailLoadWithError - -1004: Could not connect to the server.

**Comment by rrNuvoPoint** [comment]
How did you solve this?

**Comment by countrdd** [comment]
Never Did.

**Comment by rrNuvoPoint** [comment]
Hello,

Try to install the inapp browser plugin. Solved it for me.

Venlig hilsen
Rune Rasmussen
