### ISSUE TITLE
Not able to change config storage value

### ISSUE THREAD

**Issue by jbeharrell** [sahat/satellizer#380]
There doesn't seem to be a get/set function to change the value of the config storage.  I'm not able to use session storage with ```$authprovider.storage = 'sessionStorage';```, but it works if I hard code it into the module.

```
storage: {
  get: function() { return config.storage; },
  set: function(value) { config.storage = value; }
}
```

Should be at ~line 190

**Comment by TheOneTheOnlyDavidBrown** [comment]
Noticed this right before you submitted it. Here is a PR for it
https://github.com/sahat/satellizer/pull/381
