### ISSUE TITLE
Can we store the access token object into local storage as well?

### ISSUE THREAD

**Issue by tianxu0836** [sahat/satellizer#383]
It only store the token it self into the local storage.
However sometime we need the other parameters inside the token object.

i.e. the token object might contains:

.expires: "Wed, 13 May 2015 21:46:26 GMT"
.issued: "Wed, 29 Apr 2015 21:46:26 GMT"
access_token: "nzInb4MoeKP6ejzlkEWo6"
expires_in: 1209599
fullName: "NANCY BlaBla"
token_type: "bearer"
userName: "test@gmail.com"

Right now it only save the access_token.

What if I need to display the userName?

it is better to stringify the token object and keep it in the local storage as well.

**Comment by varmint09** [comment]
The basic details vary from service to service, the access_token is the only constant. If you want to keep it, store it in your own database and write a service to return the values for a certain user token, thats what I did, and probably what most do.

-1 this idea.
