### ISSUE TITLE
Google Login Error

### ISSUE THREAD

**Issue by varmint09** [sahat/satellizer#384]
Closed.

**Comment by varmint09** [comment]
Nobody able to help? Or offer any input?

**Comment by gkohen** [comment]
I think the issue is not with the authentication(or Satellizer), but rather your use of the Google plus identity service. Have you enabled it in your account console?
See this related thread: https://groups.google.com/forum/#!topic/oauth2-dev/s3d8HaK7bpQ

**Comment by varmint09** [comment]
Yes I have enabled the necessary API's. Any other suggestions?

**Comment by varmint09** [comment]
Although all the app google dialog window says i have asked for is Offline Access, is that correct?
