### ISSUE TITLE
Does the server have to return jwt?

### ISSUE THREAD

**Issue by elgs** [sahat/satellizer#387]
Hi @sahat. Can you help me to understand how the client consumes the token returned from the server? Does the server have to return a jwt? How does the client consume the returned token? Is it handled inside Satellizer, or do I have to parse it myself? Thanks.

**Comment by elgs** [comment]
I figured it myself. The client expect the server to return a json with a key "token", something like this:
```json
{"token": "..."}
```
It doesn't have to be a jwt.

**Comment by mackelito** [comment]
What if I get a json object that contains more than just the token.. eg user info etc.. ?
