### ISSUE TITLE
Option to specify a name for the popup window

### ISSUE THREAD

**Issue by qlicyngn** [sahat/satellizer#391]
Provide option to specify a name for popup window instead of '_blank' which creates a new window every  time it is called.

line 608: popupWindow = window.open(url, '_blank', optionsString);

**Comment by sahat** [comment]
@qlicyngn are you referring to a case where you click "Login with X" button multiple times and it opens multiple instances of popups?

I remember it happening but wasn't sure what is the cause. If it's simply a matter of changing the 2nd parameter, then I think it should be changed to something other than '_blank' by default.

**Comment by qlicyngn** [comment]
Yes, a new popup window will be opened each time the user clicks the Login button.

It is good enough to change it to a fixed name or maybe better an option in popupOptions, e.g. name.

**Comment by varmint09** [comment]
+1 whats the best solution to this issue, was one agreed - I have just recently noticed the issue myself.

Would setting the window name then restore focus to the window rather than opening a second?

Regards,

V
