### ISSUE TITLE
Client Side Linkedin Authentication

### ISSUE THREAD

**Issue by kfuchs** [sahat/satellizer#393]
For something like facebook you are able to set `responseType: 'token',` and that would let you handle getting an access token completely on the client side via an implicit grant. You are able to do something similar via the Linkedin IN JSSDK but there seems to be no way to do it via satellizer.

Am I missing something?

**Comment by sahat** [comment]
I don't know if there is a way to do an implicit grant with LinkedIn and if JS SDK does it somehow I couldn't find any documentation on how to do it.

However, according to https://developer.linkedin.com/docs/oauth2


**GET** https://www.linkedin.com/uas/oauth2/authorization
`response_type`	The value of this field should always be:  `code`
