### ISSUE TITLE
Pass custom parameters in signupUrl dinamically

### ISSUE THREAD

**Issue by imanzano** [sahat/satellizer#396]
Hi,

It would be great to be able to pass custom parameter in redirect url. 

For example , now you are able to do in facebookç

http://facebook.com/v2.3/...../...redirect_uri=<URI>....

Where uri is the redirect uri ,and here you can set http://localhost:8080/myLogin/?parameter=1

I want to know if is it possible to change the url, signupUrl dinamically in the $auth.authenticate(provider) call.

Thanks,
Ignacio

**Comment by sahat** [comment]
@imanzano Not possible unfortunately. It would require having to change `$auth.authenticate` method signature to add more parameters.

**Comment by mrunwal** [comment]
I am also expecting to pass additional parameter. By any chance if you provide option then it would be great.
