### ISSUE TITLE
Twitter php server example not working

### ISSUE THREAD

**Issue by Pietro-Vis** [sahat/satellizer#397]
See [this] (http://stackoverflow.com/questions/30121061/angularjs-satellizer-twitter-login-cors-error-on-redirect) SO question for details. 
I've adapted for Yii framework the twitter authentication flow described in examples/server/php/app/Http/Controllers/AuthController.php

The problem is at the method twitter at line 331:
```php
return redirect($authenticateUrl . '?' . $params);
```
The server is redirecting the ajax call made by the client (not the popup window!), but twitter doesn't accept Cross-origin resource sharing, so i only get this error on chrome console:
```
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin is therefore not allowed access.
```

To circumvent this, i had to return instead the oauth_token to the client, and make the client redirect the popup to the twitter $authenticateUrl, obviously not using satellizer.
**Am i doing something wrong or can you tell me what is the problem?**

**Comment by sahat** [comment]
@Pietro-Vis I have recently changed the behavior of OAuth 1.0 and thus Twitter. I documented the changes in https://github.com/sahat/satellizer/issues/329.

Currently, only node.js supports the new Twitter flow. I will update other languages when I get a chance.

**Comment by Pietro-Vis** [comment]
Thank you for answer, i did not notice the changes documentation about it.
Do you think that the behavior to follow with new changes will be similar to the one i am approaching?

**Comment by agarwalexpress** [comment]
in production server auth/me  not working  kindly suggest any change required

**Comment by sahat** [comment]
I just updated the Laravel example to work with the new OAuth 1.0 flow in Satellizer.
https://github.com/sahat/satellizer/commit/eb386527ec3f50129dffd4a2a09e6da8af84752f

Notice that the /auth/twitter route is now POST instead of GET. Also, there is no longer a page redirect.

**Comment by Pietro-Vis** [comment]
Thank you for the fast correction, great work!
