### ISSUE TITLE
Use Satellizer with laravel framework

### ISSUE THREAD

**Issue by aditigoel** [sahat/satellizer#399]
Hi Sahat,
I used satellizer with nodejs its working fine. But i tried to use it with laravel 5 , I didn't get the flow . When i send request through angular controller like:
$auth.signup to Laravel route.
It gives me error message url not found.
Angular Controller :

	 $scope.signup = function() {
		 alert($scope.email);
		 alert($scope.password);
		
		 var data =  {
        email: $scope.email,
        password: $scope.password
		}; 
		  $auth.signup(data)
			.then(function() {
				alert('You are successfully registered. Please check your mail to activate your account.');
        })
        .catch(function(response) {
			alert('Email already exists');
        }); 
	 };

And in Routes.php of Laravel 5, I am calling it like that :
Route::post('auth/signup', 'TodosController@signup');

Please Help Me out, if any mistake I am doing.

Thanks in advance.

**Comment by sahat** [comment]
Your route declaration looks correct. I see you are using `TodosController`. Do you have a `signup()` function there which lives in `AuthController` in my example?

```php
public function signup(Request $request)
    {
        $validator = Validator::make($request->all(), [
            'displayName' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required'
        ]);

        if ($validator->fails()) {
            return response()->json(['message' => $validator->messages()], 400);
        }

        $user = new User;
        $user->displayName = $request->input('displayName');
        $user->email = $request->input('email');
        $user->password = Hash::make($request->input('password'));
        $user->save();

        return response()->json(['token' => $this->createToken($user)]);
    }
```

**Comment by aditigoel** [comment]
Thanks for replying.
Yes , I have signup() function in my TodosController as follow:-

public function signup(Request $request)
	{
		echo 'Aditi Goel';
		die;
	}

But it gives me error:- 
404 Not found as shown in screenshot for reference
![screenshot from 2015-05-12 09 43 16](https://cloud.githubusercontent.com/assets/10771021/7580071/6988fbb6-f88b-11e4-94f5-ceb388f91f3f.png)

**Comment by sahat** [comment]
PHP example is located under examples/php.

I think I know what's your issue. Look at your URL - `localhost/todosapplication/public`. Now I don't know which exactly is your app root `localhost/todosapplication` or `localhost/todosapplication/public` but try setting this option in your Angular app:
```js
$authProvider.baseUrl = '/todosapplication';
```

This will add a URL prefix to all requests, e.g. `todosapplication/auth/signup`.

**Comment by aditigoel** [comment]
Thank you so much , it help me. Your php example is as useful as , the node example. :-)

**Comment by aditigoel** [comment]
But , in this where u mention the port i.e http://localhost:3000/#
in server.php file such port is not defined

**Comment by sahat** [comment]
@aditigoel No it isn't, so what I usually do is run `php artisan serve --port 3000` to launch it on *http://localhost:3000* locally.

**Comment by aditigoel** [comment]
Hi,

I have done this, and setup it on my local system. 
But the problem aries when submit the signup form.

it shows me below error :

TokenMismatchException in VerifyCsrfToken.php line 46:

before doing signup, i just edit the satellizer.js file and 
edit   loginOnSignup: true,  to   loginOnSignup: false,

For CsrfToken i tried out lots of methods like but not getting any success :
1. https://laracasts.com/discuss/channels/general-discussion/keep-getting-tokenmismatchexception-verifycsrftokenphp-on-line-46
2. http://laravel.io/forum/11-14-2014-laravel-5-cant-post
3. https://laracasts.com/discuss/channels/1. https://laracasts.com/discuss/channels/general-discussion/keep-getting-tokenmismatchexception-verifycsrftokenphp-on-line-46general-discussion/l5-avoiding-csrf-middleware-on-api-post-routes?page=1
4. http://stackoverflow.com/questions/18336699/how-to-send-csrf-token-inside-angularjs-form-using-laravel-api

Any approch if i am doing some thing wrong.
Please Help !!!
Thanks in advance.

**Comment by Murwa** [comment]
hey @aditigoel I don't think u really need that middleware. U can disable the middleware by commenting it out in Http/Kernel.php file.

If u do, then u have to send the csrf token in your requests.

**Comment by aditigoel** [comment]
Hi, 
yes right now , I am working only by commenting that middleware.

**Comment by sahat** [comment]
Closing this issue since the original problem seems to be resolved. I haven't played around with Laravel CSRF middleware, so can't comment on it.
