### ISSUE TITLE
polyfill atob not used when using browserify

### ISSUE THREAD

**Issue by mathpere** [sahat/satellizer#403]
Hi,

I saw that satellizer was including Base64.js from David Chambers.

But, when using satellizer with Browserify, ```atob``` and ```btoa``` functions are added to module (```exports```) rather than window (```this```). See here: https://github.com/sahat/satellizer/blob/master/satellizer.js#L838

2 consequences:
- these methods are always added to the module (not a big deal)
- When we really need it (e.g. IE9) by using $window.atob, this could not work. See here: https://github.com/sahat/satellizer/blob/master/satellizer.js#L298

**Comment by sahat** [comment]
Hi @mathpere, I didn't know about such behavior when used with Browserify. What's your suggested solution?

There are two that I see:
1. Remove Base64.js from Satellizer completely and ask developers to include it as a polyfill.
2. Create an internal helper function that would use appropriate atob() and btoa() on `window` or `this` object. Although I am not exactly sure how that would work yet.

**Comment by mathpere** [comment]
Hi @sahat,

I personally think that it's always a bad idea when a library includes itself polyfills. 
This issue that I met for the first time is a new good argument :)

- You should document the requirements for IE <= 9:
```
<!--[if lte IE 9]>
    <script src="../base64.js"></script>
<![endif]-->
<script src="//cdn.jsdelivr.net/satellizer/0.10.1/satellizer.min.js"></script>
```

- You could eventually do a submodule with david chambers git repo to facilitate polyfill inclusion.

- You could also print a warning log when atob function is unavailable.

**Comment by sahat** [comment]
I have removed the base64.js polyfill from the library and added a note in the README about requiring it directly from CDN if they wish to support IE9 browser.
