### ISSUE TITLE
Encoding issue

### ISSUE THREAD

**Issue by mathpere** [sahat/satellizer#404]
Hi,

When I'm trying to decode this token with satellizer:
```
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJfaWQiOiI1NTUwZTNmNWI2YTRkMGE4MDM5ODkwZTAiLCJmaXJzdE5hbWUiOiJyb2LDqXJ0w6AiLCJsYXN0TmFtZSI6InRow6nDtCIsInJvbGVzIjpbInVzZXIiXSwiZW1haWwiOiJyb2JlcnRhLnRlb0BnbWFpbC5jb20iLCJpYXQiOjE0MzEzNjQ1OTcsImV4cCI6MTQzMjU3NDE5N30.cIWEwWdzbCWIVt98SFpwCEemmAsDffs4NoEIrJpv7Tg
```
I get this payload:

```
{
  "_id": "5550e3f5b6a4d0a8039890e0",
  "firstName": "robÃ©rtÃ ",
  "lastName": "thÃ©Ã´",
  "roles": [
    "user"
  ],
  "email": "roberta.teo@gmail.com",
  "iat": 1431364597,
  "exp": 1432574197
}
```

whereas I was expecting the following:
```
{
  "_id": "5550e3f5b6a4d0a8039890e0",
  "firstName": "robértà",
  "lastName": "théô",
  "roles": [
    "user"
  ],
  "email": "roberta.teo@gmail.com",
  "iat": 1431364597,
  "exp": 1432574197
}
```

When looking at angular-jwt lib, they prevent this issue by replacing
```return JSON.parse($window.atob(base64));``` at https://github.com/sahat/satellizer/blob/master/satellizer.js#L298
with
```return JSON.parse(decodeURIComponent(escape(window.atob(base64))));``` at  https://github.com/auth0/angular-jwt/blob/master/dist/angular-jwt.js#L75

Are you interested in a pull request with this fix if you think it's a good idea?

**Comment by sahat** [comment]
Hey @mathpere, sure I'd love a PR for this. It was negligence on my part for not testing inputs using non-english characters.
