### ISSUE TITLE
Duplicate request after authorization

### ISSUE THREAD

**Issue by broncha** [sahat/satellizer#406]
Hi,

I am trying to implement xero (OAuth1.0) authentication. Everything is working fine till the user authenticates. But when the user is redirected back to the callback URL, the popup has already requested the server with "oauth_verifier" and "oath_token". Also the popup poller intercepts and makes an ajax request to the same URL. 
But the first request has already exchanged the request token with access token and the second request (the one initiated through ajax) always fails as the request token is already expired. 

I tried to lower the polling time from 35 to 5, but its still not working.
Can we stop the first request completely?

**Comment by zenny-ritchie** [comment]
Hi, first i must say this is awesome plugin / module and thank you guys :)

I also have this issue with duplicating requests after login, i'm using $resource to create requests, do you know whats going on here and how to fix it ? if you need more info, please let me know.

tnx in advance.
