### ISSUE TITLE
Problem with CORS

### ISSUE THREAD

**Issue by burakkilic** [sahat/satellizer#407]
Hi;

I am using Cloudinary to upload my images.

It is not allowing Authorization header in the request. So I write request like:

    $http({
      url: '[cloudinary url is here]',
      skipAuthorization: true,
      method: 'POST',
      data: {
            file: file
     }
    });

But it is still giving errors. 

If I set 

    $authProvider.httpInterceptor = false;

it is working.

**Comment by sahat** [comment]
httpInterceptor is what's appending `Authorization: Bearer` to the headers on every request. By setting it to `false` you can control when and how to send the token.
