### ISSUE TITLE
Production server  {"message":"Please make sure your request has an Authorization header"}

### ISSUE THREAD

**Issue by agarwalexpress** [sahat/satellizer#408]
On Production Server  after transfer I am getting this error
{"message":"Please make sure your request has an Authorization header"}

Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOjgsImlhdCI6MTQzMTYwNTI1NCwiZXhwIjoxNDMyODE0ODU0fQ.eL5uYKY3zUhft7SGVBDkOy7zk2BxVZ0R3fdkoRPTou4
Cache-Control:max-age=0
Connection:keep-alive
Cookie:XSRF-TOKEN=eyJpdiI6InltVk9CMzlFaW1IZGFcL1llXC93YXM3dz09IiwidmFsdWUiOiJnTkltSmZWXC9KelROSHE5ZGRZRWpCOWlta0dFb1BpdUY2N2lVSmROb0hqbU0yYnpIb04yem92RW93YnltY0NvbjYwXC9aWTdsNzRjcld3MVwvOUZJdytrQT09IiwibWFjIjoiNGU0NDlhNTgyY2RhNGFkNjYyZmZkMzU0YTc5OTA3ZGJlZDRhY2E2MGNiY2I4MzYxZjcyMmQwZWI0YjM4MDc5MSJ9; laravel_session=eyJpdiI6Im5KaHZScHVxNHRpaitEcWZQaGZoWXc9PSIsInZhbHVlIjoiNVNIT1BCWW9ad0xpVE42Y1wvS0d1VmtaTkVQYVdEcnVZN1BpN2dIWHMyd1YxNTNkVXFpaUtPZ2o5djZ1QWVacTNDSDJ1ckF2MkJIMlwvNkhic0M4XC9vNlE9PSIsIm1hYyI6IjJmYzEyMjE0NDdiYjk1Yjk2NGVhMTEwNTMyZGUwNTI3OTgyZGQxZWVlNDY2YmVjZjY3M2U3YjJhYmZjNmI3ZmUifQ%3D%3D
Host:agarwalexpress.loc
Referer:http://agarwalexpress.loc/
User-Agent:Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36
X-XSRF-TOKEN:eyJpdiI6InltVk9CMzlFaW1IZGFcL1llXC93YXM3dz09IiwidmFsdWUiOiJnTkltSmZWXC9KelROSHE5ZGRZRWpCOWlta0dFb1BpdUY2N2lVSmROb0hqbU0yYnpIb04yem92RW93YnltY0NvbjYwXC9aWTdsNzRjcld3MVwvOUZJdytrQT09IiwibWFjIjoiNGU0NDlhNTgyY2RhNGFkNjYyZmZkMzU0YTc5OTA3ZGJlZDRhY2E2MGNiY2I4MzYxZjcyMmQwZWI0YjM4MDc5MSJ9

**Comment by barryvdh** [comment]
PHP/Laravel?
I needed to add this to my .htaccess file:
`RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]`

**Comment by sahat** [comment]
Take a look at the [.htaccess](https://github.com/sahat/satellizer/blob/master/examples/server/php/public/.htaccess) file in the examples/server/php/public directory: https://github.com/sahat/satellizer/tree/master/examples/server/php/public
