### ISSUE TITLE
pollpopup removes a slash from code

### ISSUE THREAD

**Issue by olegabu** [sahat/satellizer#410]
Google returns a slash as part of the code: '4/...' and pollpopup removes the slash making it invalid, satellizer.js line 684.
Note the version on satellizer.herokuapp.com is different with
search.replace(/\/$/, '');
not
search.replace(/[\/$]/, '');

**Comment by sahat** [comment]
Hey @olegabu, this changed was added 11 days ago as part of https://github.com/sahat/satellizer/pull/394. If I understand correctly it was a suggested fix for IE11. Is there any way we can satisfy both issues without hard coding browser version checks? @ghoken

**Comment by sahat** [comment]
Fixed on `master` branch. I will be releasing 0.11 shortly.
