### ISSUE TITLE
Error: Invalid grant with node.js server example

### ISSUE THREAD

**Issue by nodeEnthu** [sahat/satellizer#415]
Hi , 
thanks for this awesome product sahat and other contributors .. saves a lot of time
Issue:
I getting this error {"error":"invalid_grant"} while trying to login with my google account using the node.js example (https://github.com/sahat/satellizer/tree/master/examples/server/node). Ive spent too much time on but could not solve it. Any help .. much appreciated

    var accessTokenUrl = 'https://accounts.google.com/o/oauth2/token';
    var peopleApiUrl = 'https://www.googleapis.com/plus/v1/people/me/openIdConnect';
    var params = {
        code: req.body.code,
        client_id: req.body.clientId,
        client_secret: '6OZgHvGGk6YhCImOGoCvuxsR',
        redirect_uri: req.body.redirectUri,
        grant_type: 'authorization_code'
    };

    // Step 1. Exchange authorization code for access token.
    request.post(accessTokenUrl, {
        json: true,
        form: params
    }, function(err, response, token) {
        console.log('Access token ' + JSON.stringify(token));
        console.log('Response ' + JSON.stringify(response));
        var accessToken = token.access_token;
        var headers = {
            Authorization: 'Bearer ' + accessToken
        };

        // Step 2. Retrieve profile information about the current user.
        request.get({
            url: peopleApiUrl,
            headers: headers,
            json: true
        }, function(err, response, profile) {
            console.log('This is what google lets ppl know abt me ', JSON.stringify(profile));
            res.send('ok');
            // Step 3a. Link user accounts.
            if (req.headers.authorization) {
                User.findOne({
                    google: profile.sub
                }, function(err, existingUser) {
                    if (existingUser) {
                        return res.status(409).send({
                            message: 'There is already a Google account that belongs to you'
                        });
                    }
                    var token = req.headers.authorization.split(' ')[1];
                    var payload = jwt.decode(token, config.TOKEN_SECRET);
                    User.findById(payload.sub, function(err, user) {
                        if (!user) {
                            return res.status(400).send({
                                message: 'User not found'
                            });
                        }
                        res.send({
                            token: token
                        });
                    });
                });
            } else {
                // Step 3b. Create a new user account or return an existing one.
                User.findOne({
                    google: profile.sub
                }, function(err, existingUser) {
                    if (existingUser) {
                        return res.send({
                            token: createJWT(existingUser)
                        });
                    }
                    console.log(JSON.stringify(profile));
                });
            }
        });
    });
// console log

Access token {"error":"invalid_grant"}
Response {"statusCode":400,"body":{"error":"invalid_grant"},"headers":{"content- type":"application/json","cache-control":"no-cache, no-store, max-age=0, must-revalidate","pragma":"no-cache","expires":"Fri, 01 Jan 1990 00:00:00 GMT","date":"Mon, 18 May 2015 06:27:59 GMT","x-content-type-options":"nosniff","x-frame-options":"SAMEORIGIN","x-xss-protection":"1; mode=block","server":"GSE","alternate-protocol":"443:quic,p=1","accept-ranges":"none","vary":"Accept-Encoding","connection":"close"},"request":{"uri":{"protocol":"https:","slashes":true,"auth":null,"host":"accounts.google.com","port":443,"hostname":"accounts.google.com","hash":null,"search":null,"query":null,"pathname":"/o/oauth2/token","path":"/o/oauth2/token","href":"https://accounts.google.com/o/oauth2/token"},"method":"POST","headers":{"content-type":"application/x-www-form-urlencoded","accept":"application/json","content-length":276}}}
This is what google lets ppl know abt me {"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}}
{"error":{"errors":[{"domain":"global","reason":"authError","message":"Invalid Credentials","locationType":"header","location":"Authorization"}],"code":401,"message":"Invalid Credentials"}}

**Comment by sahat** [comment]
I am aware of the issue and currently struggling to understand why it doesn't work either. Could be related to the new API endpoint: `https://www.googleapis.com/oauth2/v3/token`.

**Comment by nodeEnthu** [comment]
hey..
thanks for responding .. Ive been going crazy over this.. will let you guys know if happen to resolve it

**Comment by sahat** [comment]
@nodeEnthu I already know the issue. It was caused by https://github.com/sahat/satellizer/pull/394/files

**Comment by sahat** [comment]
Should be working now.

**Comment by nodeEnthu** [comment]
cool.. thanks bud
