### ISSUE TITLE
FB app's in-app browser issue

### ISSUE THREAD

**Issue by prashantmishraimpinge** [sahat/satellizer#416]
Hi Sahat,

Using code that pushed to Github https://github.com/sahat/satellizer/releases/tag/0.7.0

I am having issues with FB app's in-app browser. It doesn't let my facebook login working properly.

Any guess?

Thanks in advance.

**Comment by austintodo** [comment]
+1 Same issue here. Any idea how to fix it? Thanks!

**Comment by sahat** [comment]
This should have already been fixed sometime ago.
