### ISSUE TITLE
$auth.logout()

### ISSUE THREAD

**Issue by hasanaydogar** [sahat/satellizer#418]
if i add local stroge "satellizer_token" = "12" (anything)
i can be login. how can handle with more secure logout?
Thanks

**Comment by sahat** [comment]
I could update `isAuthenticated` to make sure it's at the very least a valid JWT token with a proper structure, so that `"satellizer_token" = "12"` would be invalid, e.g.:

```eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
```

However whether it is valid or not it still has to be determined by the server.

**Comment by hasanaydogar** [comment]
Thanks.

**Comment by sahat** [comment]
Fixed and pushed to `master` branch. Satellizer 0.11 will be released shortly which will include this fix.
https://github.com/sahat/satellizer/commit/c875f6d46fba62f5dc8acade667b6332b9b1a7a9
https://github.com/sahat/satellizer/commit/bb8518b46111d143aac32114ce7e4c9d52bf16e8
