### ISSUE TITLE
Login don't work in ios with google chrome

### ISSUE THREAD

**Issue by Lucyan** [sahat/satellizer#419]
Hi, i'm working in app with satellizer and i try in ios 8.3 with Chrome for iOS version 42.0.2311.47 and login don't work (facebook and twitter).

i try with demo https://satellizer.herokuapp.com and does not work

(sorry if my english is very bad :p)

**Comment by clarle** [comment]
Hi @Lucyan,

I'm able to successfully login on Chrome 43.0.2357.56 (latest iOS app on iOS 8.3) for both Twitter and Facebook using https://satellizer.herokuapp.com.

What do you see on your side when you can't login?

**Comment by joturako** [comment]
I'm having this issue on Chrome for iOS: I'm able to login with the demo app, but not my app. I'm using ionic framework and ui-router.

**Comment by vasconcelloslf** [comment]
@clarle @Lucyan @joturako 

I just found the solution for it. This bug affects all versions after 0.9.4, so to solve it use the 0.9.4 version.

**Comment by joturako** [comment]
@vasconcelloslf the bug is that satellizer use window.open with more parameters than just the url. go into the satellizer source code and change the line to use just the url as the only parameters. the bug is then gone.

**Comment by vasconcelloslf** [comment]
@joturako I chose the downgrade path, but your solution also works.

**Comment by sahat** [comment]
Let's discuss this issue in #467.
