### ISSUE TITLE
Code Improvemnt: documentOrigin and popupWindowOrigin are calculated wrong

### ISSUE THREAD

**Issue by nzamani** [sahat/satellizer#420]
In line 680 you do the following (see source at https://github.com/sahat/satellizer/blob/master/satellizer.js#L680-L681 ):

```javascript
var documentOrigin = document.location.host + ':' + document.location.port,
                popupWindowOrigin = popup.popupWindow.location.host + ':' + popup.popupWindow.location.port;
```

In JavaScript document.location.host already contains the port, so doing something like  

```javascript
var documentOrigin = document.location.host + ':' + document.location.port;
```
will have a weird result, i.e. "localhost:8181:8181". Instead you should use

```javascript
var documentOrigin = document.location.host,
    popupWindowOrigin = popup.popupWindow.location.host;
```

This also makes sure that you don't have a tailing ":" without a port...

**Comment by sahat** [comment]
Thanks, this was actually submitted as a PR a while back. This is a case of two "wrongs" make 1 "right", because in the end it still worked.
