### ISSUE TITLE
(node-example) User can remove his last method of authentication 

### ISSUE THREAD

**Issue by dotch** [sahat/satellizer#421]
A user can unlink a social account even when it is his last remaining method of authentication.

**Comment by sahat** [comment]
Yeah I left it as is. I don't know if there is an easy way to determine if it's a last linked provider? Checking for every possible provider using a big `if` statement is not practical either.

**Comment by dotch** [comment]
We could add an array to the user model to keep track of the user's currently used auth-providers.
When a new one gets linked, it gets pushed to the array and removed on unlink.
This would also fix #413, because we check if the provider, which is to be removed is actually set in the array.

**Comment by satishimpingesolutions** [comment]
Hi,

I am getting two issues(Facebook in-app browser) that might be related to same problem.
- Pop-up is not getting closed 
- Facebook is unable to exchange token with my server.

"The default value for $authProvider.platform is "browser".

Do I need to change something to get it working? Here is the URL to my Satellizer.js file
[Satellizer JS Link](http://staging.juxtap.com/bower_components/satellizer/satellizer.js?v=35345436546)

any help? 

Thanks,
