### ISSUE TITLE
Emit login logout event on rootscope

### ISSUE THREAD

**Issue by cgarnier** [sahat/satellizer#426]
Sending login/logout events on rootscope could be convenient.

**Comment by javiermarinros** [comment]
+1

**Comment by sahat** [comment]
There was a discussion about `$rootScope` in the past but I think it was decided not to go through with it: https://github.com/sahat/satellizer/issues/152 and https://github.com/sahat/satellizer/issues/55

Don't know if you guys can tell, but there are a lot of open issues, and with my limited time on this project I would rather fix existing issues than work on adding new features that could potentially break something else.
