### ISSUE TITLE
Hook on token receival

### ISSUE THREAD

**Issue by RavisMsk** [sahat/satellizer#427]
Hey, @sahat! Huge thanks for a great module.

Is there any way to set a hook/callback on token receival event?
I think it can be used for manually settings a cookie, because cookies are still needed in situations of first application page load, even in SPA. Token from localstorage is not getting automatically set to request header by browser, so first request is always w/o auth token.

P.S. Typical behaviour of SPA is of course to load all statics from CDN, then check sessions and perform app inits etc. But having cookie would still help in some cases.

Thanks in advance!

**Comment by sahat** [comment]
Hey @RavisMsk, don't think Satellizer can do that. If you want to protect the initial request, before your Angular app loads, then it is best to put it behind the server authentication.

Or what you could try is to use `resolve()` provided by ui-router which will not load that particular route until user is authenticated as demonstrated by the demo project in `examples/client/app.js`:

```js
.state('profile', {
        url: '/profile',
        templateUrl: 'partials/profile.html',
        controller: 'ProfileCtrl',
        resolve: {
          authenticated: function($q, $location, $auth) {
            var deferred = $q.defer();

            if (!$auth.isAuthenticated()) {
              $location.path('/login');
            } else {
              deferred.resolve();
            }

            return deferred.promise;
          }
        }
      });
```

**Comment by RavisMsk** [comment]
Thanks for advice, @sahat! Already using that method, showing loading screen until whole application becomes determined, and, in particular, until current JWT token is confirmed alive.

**Comment by sahat** [comment]
@RavisMsk Ok sounds good. I am closing this issue since I don't have any other better solutions for you.
