### ISSUE TITLE
How can I apply Azure AD as provider ?

### ISSUE THREAD

**Issue by AbdoDabbas** [sahat/satellizer#433]
Hi, I tried to apply Azure AD as provider but it didn't work, after opening the popup and entering my credentials it redirects me to my 'redirect URL', shouldn't redirect me to a URL I can get the 'code' from it ?
It doesn't redirect me to a page asks me that "this application is trying to access you info" for example.What should I do ?
And it's closing quickly.

**Comment by sahat** [comment]
@AbdoDabbas Have you followed the documentation here? https://msdn.microsoft.com/en-us/library/azure/dn645542.aspx

You probably have to point `authorizationEndpoint` to **https://login.windows.net/common/oauth2/authorize** if you haven't already done so. That's the URL for  a page with authorization access.

**Comment by sahat** [comment]
Closing since I haven't heard back. If you still can't get it to work after following Azure's OAuth 2 documentation, feel free to re-open the issue.

**Comment by nigel-dewar** [comment]
Hi There. I'd really like to know if there is an Azure AD module for satellizer? From this post I cannot tell what the story is. If there is, I'd really like to know because it is a requirement of mine on a project.

Cheers
