### ISSUE TITLE
baseUrl default / wrong join in joinUrl

### ISSUE THREAD

**Issue by Flofie** [sahat/satellizer#434]
In Version 0.10.1 the default in satellizer.config is baseUrl = '/'.
The error only is relevant if you set a url for a provider:

```javascript
$authProvider.facebook(angular.extend({}, commonConfig, {
    clientId: 'FACEBOOK_APP_ID',
    url: 'https://satellizer.herokuapp.com/auth/facebook'
  }));
```
This leads to url calls like: http://localhost:8100/https://satellizer.herokuapp.com/auth/facebook'

The error seams to be in satellizer.utils - joinUrl
joining baseUrl which is '/' and the given url which is for example 'https://satellizer.herokuapp.com/auth/facebook' leading to a url of '/https://satellizer.herokuapp.com/auth/facebook' leading to a call of 'http://localhost:8100/https://satellizer.herokuapp.com/auth/facebook'

Workaround: set baseUrl to null:
```javascript
$authProvider.baseUrl = null;
```

**Comment by satishimpingesolutions** [comment]
Hi,

I am getting two issues(Facebook in-app browser) that might be related to same problem.
- Pop-up is not getting closed 
- Facebook is unable to exchange token with my server.

"The default value for $authProvider.platform is "browser".

Do I need to change something to get it working? Here is the URL to my Satellizer.js file
[Satellizer JS Link](http://staging.juxtap.com/bower_components/satellizer/satellizer.js?v=35345436546)

any help? 

Thanks,

**Comment by sahat** [comment]
@Flofie It was easy enough fix by checking if `url` is absolute. If that's the case, skip `baseUrl` concatenation, otherwise works exactly the same as before.
