### ISSUE TITLE
Error token

### ISSUE THREAD

**Issue by furyscript** [sahat/satellizer#435]
Hi, when I make request with this config
```javascript
  clientId: ***,
  url: '/auth/facebook',
  authorizationEndpoint: 'https://www.facebook.com/v2.3/dialog/oauth',
  redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host + '/',
  scope: 'email',
  scopeDelimiter: ',',
  requiredUrlParams: ['display', 'scope'],
  display: 'popup',
  type: '2.0',
  popupOptions: { width: 481, height: 269 }
```

Facebook not return back token, why??

And when I see the error log with
```javascript
$auth.authenticate(provider).then(function(response) {
            console.log(response);
});
```
`
Error: Expecting a token named "token" but instead got: HERE THERE IS MY HTML PAGE
`

Network tab result
```
clientId: "1580575275544727"
code: "AQB64TA1aPOZ39w30OljiITAlDw3vwY_XkxX3Jt-DOTTc5P_E0FmVwRpGxKhqShg033FmdcaAqRVMhUpu4pfn96C7Xgj3eY-R6Ey2P_Bb3uJB7Yzuj0g5p-vplb3jTDH_C7OZ5_Ur-chOQVpKu-9xc-wHyADvc3o4wN6U28TPBHKz06vgIre-Y2DhZyoniL0WA8n5IOthLl3SeH2FqBo0AkOGmXm-G5D-IMqRh8fzzsIFNz3MavW7EkE2dLHy08RozryOd_BGxVm7BoY9rI3eOGD8Bgu59hLaEt4uCqcxg-QRTzqlQoOdD1AtjYf7f-VcLk"
redirectUri: "****.."
```

I've frontend with angularjs and backend with nodejs. Maybe I set different url when function fired, but domain are different...?? @sahat

Or I need to create another route with angular and what have I do?

I also test the example of your repository and the error show again...

**Comment by furyscript** [comment]
Ok I understand, I need a Backend server for route.
But I need to change Url.
Frontend : test.it
Backend : api.test.it
If I use Absolute url is: http://test.it/http://api.test.it/facebook

**Comment by furyscript** [comment]
I resolve with 
```
$authProvider.baseUrl = 'http://api.test.it'; // API Base URL for the paths below.
```

**Comment by satishimpingesolutions** [comment]
Hi,

I am getting two issues(Facebook in-app browser) that might be related to same problem.
- Pop-up is not getting closed 
- Facebook is unable to exchange token with my server.

"The default value for $authProvider.platform is "browser".

Do I need to change something to get it working? Here is the URL to my Satellizer.js file
[Satellizer JS Link](http://staging.juxtap.com/bower_components/satellizer/satellizer.js?v=35345436546)

Thanks,

**Comment by furyscript** [comment]
Hi,
I resolve the issue.
You must have a frontend and a backend. For me frontend is AngularJS and backend is NodeJS.
You need to integrate satellizer in AngularJS and you can get Ideas for Backend in this repository on server folder.
The problem is that post request of provider (Facebook, google etc) not find route or the route is the same and it return the HTML.
Be carefull: if you have a backend with different origin (URL) you need to set baseUrl options! (Prev comment :+1: )

**Comment by varmint09** [comment]
So basically, we can summarise this as "Read the documentation".

Nice one.

**Comment by satishimpingesolutions** [comment]
@furyscript : But it works fine in web browser and mobile browsers, It is not working in FB in-app browsers. I have Front-end and back-end set-up then what can be the issue.

Satish

**Comment by furyscript** [comment]
@satishimpingesolutions it's difficult diagnosticate problem in mobile if you cannot check some error or similar ):

**Comment by satishimpingesolutions** [comment]
@furyscript @sahat : If we set verison: mobile, then also it doesn't work in web browser. It got stuck at in the pop-up and with an authentication code in get. 

Try to change verison to mobile and check in web browser.

**Comment by furyscript** [comment]
I've same problem with twitter.
With facebook and google I return my personal token called auth_token, but twitter need two call with if statement (see https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js#L599) so with the first call I expected a token named "auth_token" but the code return this object
```
oauth_callback_confirmed: "true"
oauth_token: "sUfVs388xEcl2hHco4BPOxWBNdprpeSK6"
oauth_token_secret: "FGQ98b7rTt6gKOegD5qKncXNd4MXWrxzY"
```
So I catch the error:
```
Error: Expecting a token named "auth_token" but instead got: {"oauth_token":"sUfVs388xEcl2hHco4BPOxWBNprpseSK6","oauth_token_secret":"FGQ98sb7rTt6gKOegD5qKncXN4MXWrxzY","oauth_callback_confirmed":"true"}
```

@satishimpingesolutions If I change version to mobile, in web browser works fine! You use node??

**Comment by satishimpingesolutions** [comment]
I am using Angular and Laravel.

You can see it here: [Link] (http://staging.juxtap.com/widget/login?v=YruO)

**Comment by satishimpingesolutions** [comment]
In mobile in-app browser,  my code is not working at following lines:

It stuck here. @furyscript @sahat 
popupWindow.addEventListener('loadstart', function(event) {
  ..
}
