### ISSUE TITLE
Bug: Cannot make new account after logout

### ISSUE THREAD

**Issue by Vincent-Noben** [sahat/satellizer#436]
A bug I found while testing out your examples.

Setup:
Nodejs server and client (On same server ==> localhost:3000)

- I open a new chrome incognito window
- I register with facebook
- I get logged in, account is created in mongodb, I get my profile information as should.
- I press logout button
- I click the google+ or twitter button and try to register.
- I get "logged in" and can acces the profile page. But no new user was made in the database,
  nor do I get any profile information (as there is no user in database ;) )
- I try to signup with username/password ==> this still works and makes a new user.
(idem for when I empty my database and start this process with google/twitter)

So I assume that when you press logout not everything is cleared from your browsers localstore/session? And therefore you cannot make a second/new account in the same browser. And that seems very strange to me. That would mean somebody else cannot make a new account using my pc.

**Comment by furyscript** [comment]
You need to set more options in database, for example each column for all socials that contains Id or email register user in the socials.
So when user logged in you compare email or id and then make user log in. When user log out you don't make anything because after next login you compare other column

**Comment by clarle** [comment]
Hi @Vincent-Noben,

@furyscript is correct. You'd need to store the user's ID for whatever authentication service you're using based on what you're getting back from OAuth / other identity protocol.

Let us know if you have any other questions, or if there's anything else we can help with.

Thanks!
