### ISSUE TITLE
Twitter error

### ISSUE THREAD

**Issue by furyscript** [sahat/satellizer#438]
Hi all, 
I've same problem with twitter.
In contrast to facebook and google I return my personal token called auth_token, but twitter need two call with if statement (see https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js#L599) so with the first call I expected a token named "auth_token" but the code return this object
```javascript
oauth_callback_confirmed: "true"
oauth_token: "sUfVs388xEcl2hHco4BPOxWBNdprpeSK6"
oauth_token_secret: "FGQ98b7rTt6gKOegD5qKncXNd4MXWrxzY"
```
So I catch the error:
```javascript
Error: Expecting a token named "auth_token" but instead got: 
{"oauth_token":"sUfVs388xEcl2hHco4BPOxWBNprpseSK6",
"oauth_token_secret":"FGQ98sb7rTt6gKOegD5qKncXN4MXWrxzY",
"oauth_callback_confirmed":"true"}
```
P.S: With twitter I'd set "type" option, therefore the post request got 404.
How can I resolve that?

**Comment by sahat** [comment]
@furyscript I don't think I understand your question. Twitter (OAuth 1) works completely different from Facebook, Google (OAuth 2). 

You use 
```js
{"oauth_token":"sUfVs388xEcl2hHco4BPOxWBNprpseSK6",
"oauth_token_secret":"FGQ98sb7rTt6gKOegD5qKncXN4MXWrxzY",
"oauth_callback_confirmed":"true"}
```
to exchange it for access token, that in turn gets used to get user profile information, and once you have that user, you create a JWT token that you send back to the client: `res.send({ auth_token: 'your jwt token'});`

**Comment by furyscript** [comment]
yes but I copied your node example server. I set token name "auth_token", then in facebook and google I return my token name correctly. In twitter at the first "IF" it return object with "oauth_token" and I got error "Error: Expecting a token named "auth_token" but instead got: OBJECT HERE".

How to resolve that??

**Comment by sahat** [comment]
Are you using the latest node.js example and the latest version of satellizer? I may have to see your code to figure out what is the issue.

**Comment by furyscript** [comment]
Yes I'm using the latest code...

2015-06-06 1:35 GMT+02:00 Sahat Yalkabov <notifications@github.com>:

> Are you using the latest node.js example and the latest version of
> satellizer? I may have to see your code to figure out what is the issue.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahat/satellizer/issues/438#issuecomment-109482939>.
>



-- 
Web developer ~ Programmatore

**Comment by danamajid** [comment]
Current latest NodeJS example for Twitter does not work. Basically, the auth flow stops here: https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js#L611

**Comment by furyscript** [comment]
@danamajid Yes, it doesn't work!!!

**Comment by danamajid** [comment]
Just to verify, this is CORS related as it's only the case when the server and client are not on the same domain.

**Comment by furyscript** [comment]
Uhm, are you sure?? The code expected a token name, so it return error but in real case the request should be open twitter confirmation...

**Comment by sahat** [comment]
@danamajid Node.js example works just fine for me on the same port `http://locahost:3000`. I'll investigate the CORS issue with Twitter authentication. Perhaps it could be related to @furyscript's problem?

**Comment by sahat** [comment]
So for CORS, I had to download and require `cors` package:
```js
var cors = require('cors');
...
app.set('port', process.env.PORT || 3000);
app.use(cors());
app.use(logger('dev'));
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));
```

And the AngularJS example add the following configuration:
```js
$authProvider.withCredentials = false;
```

Although, it seems this issue is not related to @furyscript after all.

**Comment by furyscript** [comment]
I've cors enabled and withCredentials = false
When Twitter send oauth_token back to open new dialog, satellizer repond me:
```
Error: Expecting a token named "auth_token" but instead got: 
{"oauth_token":"sUfVs388xEcl2hHco4BPOxWBNprpseSK6",
"oauth_token_secret":"FGQ98sb7rTt6gKOegD5qKncXN4MXWrxzY",
"oauth_callback_confirmed":"true"}
```
In the first "IF"...

**Comment by furyscript** [comment]
Now it seems to work, I'm really happy but I don't know because now it work, I don't modified anything except the type of twitter OAuth from 1.1 to 1.0...

**Comment by danamajid** [comment]
Check you callback url in your Twitter app settings and see if it's listed with www or without. Works with one of the two – depending what you have there. Might have be the reason.

**Comment by furyscript** [comment]
@danamajid Thanks!!!! Is the reason!!! FINALLY!! :)

**Comment by danamajid** [comment]
Glad it worked out for you. Added an explanation to my comment for future reference.

**Comment by sahat** [comment]
I'll take a look at it, but stripping `www` before comparing may be a good idea. I could have never guessed that is the issue @furyscript is having.

**Comment by furyscript** [comment]
Now already not work... why??? After 1 day I try to login but twitter gave me error... @sahat

**Comment by furyscript** [comment]
Not work. 
The first call work, when it make second call not work
```Error: Expecting a token named "auth_token_value" but instead got: {"oauth_token":"vdxykwAAAAAAf5ZsAAAfBTgDQksw","oauth_token_secret":"u3U0thi7lfv5uObnNNrjhjApBR1pSP4cs","oauth_callback_confirmed":"true"}```

**Comment by furyscript** [comment]
Ok now I resolve it, be carefull to callback!!
