### ISSUE TITLE
pollPopup not working with mobile

### ISSUE THREAD

**Issue by jatsrt** [sahat/satellizer#441]
I get the following error:

    Error: undefined is not a function (evaluating 'popup.open(url, defaults.name, defaults.popupOptions, defaults.redirectUri).pollPopup()')

Looking at the code: line 490 I see:

    return popup.open(url, defaults.name, defaults.popupOptions, defaults.redirectUri)
              .pollPopup()

However, there is this in the open function line 632:

    if (config.platform === 'mobile') {
            return popup.eventListener(redirectUri);
          }

Finally looking at the eventListener function line 674, it returns a promise:

    return deferred.promise; 

So, it seems in the mobile option case this will not work as you are calling an object method on a promise.  In the open function you return a promise sometimes and a object others.

Thoughts on a clean way to fix this?

**Comment by jatsrt** [comment]
Looks like the functionality was introduced on here
https://github.com/sahat/satellizer/commit/50a31109f969dcca18c7513c99c290f08d6b2bed

Changing from returning a promise to the object itself.

**Comment by jatsrt** [comment]
Changing line 489-490 to:

    return popup.open(url, defaults.name, defaults.popupOptions, defaults.redirectUri)
              .then(function(oauthData) {

And line 635 back to:

    return popup.pollPopup();

This solves the facebook workflow, probably breaks others.

**Comment by persnoid** [comment]
I've got the same problem, too!
Login via Facebook and Google does not work. With the workaround of jatsrt I was able to fix the Facebook workflow, but the Google's one is still breaking.

**Comment by leonprou** [comment]
Now i'm also having this error,
any chance for a fix?

**Comment by jatsrt** [comment]
I've hacked around it for now for my particular use cases.  Maybe we can get @sahat 's attention.

**Comment by sahat** [comment]
There have been some changes to the popup factory and `pollPopup` method when I was refactoring OAuth 1.0. I'll take a look at it later tonight or tomorrow depending on my availability.

**Comment by Flofie** [comment]
Same problem here. I reverted back to 0.10.1 which works for me.

**Comment by sahat** [comment]
@jatsrt Are you using Ionic or Phonegap?

**Comment by sahat** [comment]
I just pushed a fix to `master` branch. Please download it and let me know if it works. If there aren't issues I will bump up the version number on npm and bower.

Tested with the latest version of Ionic Frameworka nd `cordova-inappbrowser` 1.0.

![quickcast-08-06-2015-02-55-52](https://cloud.githubusercontent.com/assets/544954/8046361/fb4db514-0dee-11e5-8e96-4c0bccd57036.gif)

**Comment by jatsrt** [comment]
@sahat I'm using Ionic, I will download and test soon

**Comment by jatsrt** [comment]
OK, I lied, test was easy, on my Ionic 1.0, Cordova 5.0, cordova-plugin-inappbrowser 1.0.0 application, it seems to be working wonderfully.

**Comment by sahat** [comment]
Great, closing this issue. Satellizer 0.11.2 is now live.
