### ISSUE TITLE
BREAKING CHANGE: 0.11.0 does not specify the bearer token after local login.

### ISSUE THREAD

**Issue by niemyjski** [sahat/satellizer#442]
I have confirmed that there is no request header sent in 0.11.0 but it is sent in 0.10.0. Is anyone else seeing this?

**Comment by niemyjski** [comment]
I went through the diff and I'm not sure what it could be: https://github.com/sahat/satellizer/compare/0.10.1...0.11.0 I can reproduce by just switching only the version.

**Comment by niemyjski** [comment]
`if (shared.isAuthenticated() && config.httpInterceptor) {` The `shared.isAuthenticated()` is what broke me... My token is a guid and it's trying to split it.. Can we get a fix out there asap that just uses any defined token..

![image](https://cloud.githubusercontent.com/assets/1020579/7961504/95c0596a-09cd-11e5-95a0-5fc9f2a5c2be.png)

**Comment by niemyjski** [comment]
The unit tests were changed: [test/http.spec.js](https://github.com/sahat/satellizer/commit/435084aa4a05874a0add926071b9598d98aac2d1#diff-11acf2f5be7e38bd444bb3e0aa669073) which should have been a red flag that people could be broken..

**Comment by niemyjski** [comment]
@sahat  I've created a pull request for this and incremented the version number as well as included the minified build (I don't think it was updated for the 0.11.0 release.

**Comment by gkohen** [comment]
@niemyjski I ran into the same issue. I've added a similar pull request which give the flexibility if to check or not check the token expiration.
https://github.com/sahat/satellizer/pull/444

**Comment by sahat** [comment]
@niemyjski I could accept your PR and make it accept any token, but why are you using a GUID as your token instead of JWT as it is intended?

**Comment by gkohen** [comment]
@sahat if you use implicit flow with Google, and use accessType of token the browser gets back the access_token from google. That token is not a JWT and as a result is not passing the parsing done in isAutenticated. We should at least make it optional as I did in my pull request.

**Comment by niemyjski** [comment]
@sahat we had an existing system that was not using jwt. We didn't feel like it was worth converting everything to jwt when what we had worked (validated/expired etc)  and was much smaller payload per request.

**Comment by sahat** [comment]
I see, ok fair enough. I'll merge the PR and bump the version after I get home.

**Comment by niemyjski** [comment]
@sahat Thanks!
