### ISSUE TITLE
injecting dynamic value into the login url

### ISSUE THREAD

**Issue by landaud** [sahat/satellizer#445]
Hello @Sahat,
Thanks for the wonderful Satellizer module.
I use Identity Server as one of my open id / oauth2 providers.
I have to inject a generated random value into the login request URL. This value is called "nonce".
I tried to achieve that by using an anonymous function, as the "value", but the function body text itself is  sent to the server.... which is not the desired result:
            scope: ["profile"],
            scopePrefix: "openid",
            nonce : function() {
                return rand();
            },
           requiredUrlParams: ["scope", "nonce"]

Can you help me please?
Thanks.

**Comment by sahat** [comment]
Hey @landaud, it wasn't possible before because it expected url params to be a simple value such as a string or a number. Check out the latest build on master branch and let me know if it works for you.

I literally had to change just one line of code in `oauth2.buildQueryString`:

```js
var paramValue = angular.isFunction(defaults[paramName]) ? defaults[paramName]() : defaults[camelizedName];
```

**Comment by landaud** [comment]
Thank you. It works now.

**Comment by landaud** [comment]
As can be seen from the code, the popup doesn't close after authentication process. For some reason you commented out the line that closes the popup.... 
                //popup.popupWindow.close();

**Comment by sahat** [comment]
@landaud I fixed it almost immediately after I noticed that I forgot to uncomment it out. I had to do it in the first place for debugging purposes to see if `nonce` was actually being passed in.

**Comment by landaud** [comment]
Thank you.
