### ISSUE TITLE
Does satellizer consider tablets to be mobile?

### ISSUE THREAD

**Issue by JaKXz** [sahat/satellizer#448]
Right now, I'm specifying `$authProvider.platform = 'browser'` for tablets - should it actually be 'mobile'?

I'm using [bowser](https://github.com/ded/bowser) for easy platform detection

**Comment by sahat** [comment]
That flag was introduced in https://github.com/sahat/satellizer/pull/294 and as far as I can tell it's only relevant if you are building an ionic or phonegap app. For mobile browsers like Chrome and Safari you should leave it as `browser`.

**Comment by JaKXz** [comment]
Ah. Thanks for the quick reply!

So even for mobile phones, it should be `browser`?

**Comment by sahat** [comment]
No problem.
