### ISSUE TITLE
Use Satellizer to get token and user data

### ISSUE THREAD

**Issue by elimence** [sahat/satellizer#449]
Hi, I'm building an app where I need to retrieve user data from various accounts such as facebook accounts etc. I also need to get and store the tokens in a database.

Can I use this module to do this. So far, I haven't found a way to do this.
Thanks

**Comment by varmint09** [comment]
Try reading the example which has all the code for that.

**Comment by elimence** [comment]
I'd appreciate it if you could point me to the said example. Thanks

**Comment by varmint09** [comment]
https://github.com/sahat/satellizer if you look at the listing of the files - it has a folder called examples, from there you should be able to find what you need...

**Comment by sahat** [comment]
Yes, I am surprised you had to ask because the included [examples](https://github.com/sahat/satellizer/tree/master/examples) do pretty much just that.
