### ISSUE TITLE
FB popup not closing on iOS 7.

### ISSUE THREAD

**Issue by eriklovdahl** [sahat/satellizer#450]
Hi!

Seems like there is something fishy going on with Facebook login on older iOS versions.
In iOS 8+ the popup closes fine and the login proceeds. On iOS 7 however the popup doesn't close and nothing happens in the new window. If I switch back to the old window the popup closes and login proceeds. If I discard the new window nothing happens in the old window.

Any help appreciated!

**Comment by sahat** [comment]
Hey @eriklovdahl, I don't have the time or an older device to test this with. I would rather worry on making sure it works with the upcoming iOS 9 than try to figure out why it doesn't work on an older iOS 7. Again, if I had more time I'd take a look into it, but unfortunately that is not the case.

If you do want to debug the issue please feel free to do so and if it's a small fix, I'd appreciate a pull request.

**Comment by eriklovdahl** [comment]
Thanks for the reply!

Correct me if I'm wrong, but I really don't see how to fix this issue easily. When the popup gets focus the window that opened it becomes inactive and thus won't run javascript (so the polling won't work).

I solved it by doing the login in the new window instead.

**Comment by eriklovdahl** [comment]
Thank for the reply!

I really don't see how do fix the easily. The problem is that javascript is paused in an inactive web tab, which means the first window can't poll the popup.

I temporarily solved by doing the login in the popup on mobile. Looking into a better solution though and will make a pull request if I find one.

**Comment by sahat** [comment]
I am going to close this meanwhile, because it's getting hard to manage Github issues and separating actual bugs vs people doing something weird with the library vs some random questions.
