### ISSUE TITLE
Twitter login broken in mobile mode

### ISSUE THREAD

**Issue by aduffeck** [sahat/satellizer#452]
Hi,

I'm trying to use Twitter login in an ionic mobile app (with satellizer 0.11.2)  and ran into some issue. Facebook and Google login work just fine, though.

The error I get is:

```
TypeError: Cannot read property 'location' of undefined
    at satellizer.js:587
    at processQueue (ionic.bundle.js:21888)
    at ionic.bundle.js:21904
    at Scope.$eval (ionic.bundle.js:23100)
    at Scope.$digest (ionic.bundle.js:22916)
    at Scope.$apply (ionic.bundle.js:23205)
    at done (ionic.bundle.js:18358)
    at completeRequest (ionic.bundle.js:18548)
    at XMLHttpRequest.requestLoaded (ionic.bundle.js:18489)
```

The corresponding line is

```
 popupWindow.popupWindow.location.href = [defaults.authorizationEndpoint, oauth1.buildQueryString(response.data)].join('?');
```

and debugging further it seems to expect a popup object but instead gets a promise returned:

satellizer.js:639-642
```
          if (config.platform === 'mobile') {
            return popup.eventListener(redirectUri);
          }

          return popup;
```

**Comment by sahat** [comment]
Thanks, I will take a look at it. When I was refactoring Twitter authentication I was so focused on getting it  to work on desktop browsers that I completely forgot about that `popup.eventListener` flow on mobile.

**Comment by sahat** [comment]
I just pushed an update to `master`. Let me know if it works for you.

**Comment by aduffeck** [comment]
Thanks for the fix, it seems to work for me :fireworks: 

I directly ran into the next issue, though, but I think it is already tracked at https://github.com/sahat/satellizer/issues/417.
