### ISSUE TITLE
Azure AD ?

### ISSUE THREAD

**Issue by nigel-dewar** [sahat/satellizer#453]
Hi Sahat,

Fantastic work on Satellizer! 

I was wondering if there is the ability to use Satellizer with Azure AD? I dont see any options for that but assume it must be doable?

**Comment by sahat** [comment]
Thank you. Look for azure ad github issues. Someone else was trying to implement it recently. From what I understand you would implement it just as any other oauth2 provider. Check out  how I implemented the foursquare example.

**Comment by nigel-dewar** [comment]
Cool thanks Sahat.

 

Cheers

 

:)

**Comment by sahat** [comment]
@nigel-dewar were you able to get Azure AD to get working? If so, I'd love a pull request for it.

**Comment by nigel-dewar** [comment]
Hi Sahat. No I haven’t had a chance to try yet, but about to try today.

I’ve had to dive deep into understanding oAuth and the whole authentication flow before I even got started. But having spent a solid couple of days researching it, I will give it a crack.

 

Since oAuth2 is supported by Azure AD endpoint, it should be sweet, and yes I see the FourSquare implementation you did, so likely it will be just a case of swapping out the specifics required by AzureAD and should be good to go.

 

Ill let you know how I go

 

Cheers

**Comment by nigel-dewar** [comment]
Hi Sahat.

 

I had a go at this, but no joy. Cant even get the thing to post to the backend api.

 

Is the $authProvider.oauth the only option there is for custom providers?

 

 

 

Cheers

**Comment by sahat** [comment]
I will see if I can add it myself. Will update you on the progress.

**Comment by sahat** [comment]
Were you able to get this far? I am still not sure how exactly will it work. I don't see a client secret anywhere on the dashboard. The closest thing there is to client secret is some kind of **Key** with 1-year or 2-year expiration.

<img width="859" alt="screenshot 2015-07-08 17 29 07" src="https://cloud.githubusercontent.com/assets/544954/8585463/e9e5d33c-2596-11e5-9050-59ab445044d8.png">

**Comment by nigel-dewar** [comment]
Hi Sahat, Awesome bro, I’m so glad you are taking a look at this.

 

Yeah I did get this going and I’ll share all the info on it with you of course.  Ok, so I did it all manual. Heres what I did.

 

I got a file in my angular project called auth.js,

 

I make the call to Azure AD oauth authorize endpoint like so; See the highlighted yellow code below. I make a call to the Azure AD, passing through both my clientID and my tenant ID (in yellow)

 

var urlBuilder = [];
    var clientId = '076dd0d4-ec11-6546465465465465465’;
    urlBuilder.push('client_id=' + clientId,
        'redirect_uri=' + window.location.origin,
        'response_type=code'
    )

this.office365Auth = function () {


    var url = 'https://login.microsoftonline.com/fd4f1e86-7cb0-4ac4-9600-a0e331f0ee06/oauth2/authorize?' + urlBuilder.join('&');
    var options = "width=500, height=500, left=" + ($window.outerWidth -500) / 2 + ",top=" + ($window.outerHeight -500) / 2.5;

    var deferred = $q.defer();

    var popup = $window.open(url, '', options);
    $window.focus();

    $window.addEventListener('message', function (event) {
        if(event.origin === $window.location.origin){
            var code = event.data;
            popup.close();
            console.log(code);
            
                $http.post(API_URL + 'auth/office365', {
                code: code,
                clientId: clientId,
                redirectUri: window.location.origin
            }).success(function (jwt) {
                authSuccessful(jwt);
                deferred.resolve(jwt);
            });
        }
    });
    return deferred.promise;
}

 

I have some code in my app.config.js here like so, that deals with the code returned from azure AD, and passes it back to auth.js out of the window

 

run(function ($window) {
        var params = $window.location.search.substring(1);
        if(params && window.opener && $window.location.origin === $window.location.origin){
            var pair = params.split('=');
            var code = decodeURIComponent(pair[1]);
            $window.opener.postMessage(code, $window.location.origin);
            console.log("im running");
        }
});

 

So the initial post to get an auth_code is made from my front end (angular), and once Ive got that I post it to my node/express backend passing through the code and client it like so ( which receives a jwt in the callback )

 

  $http.post(API_URL + 'auth/office365', {
    code: code,
    clientId: clientId,
    redirectUri: window.location.origin
}).success(function (jwt) {
    authSuccessful(jwt);
    deferred.resolve(jwt);
});

 

So in my backend, here is how I take that auth-token, and get my access token from azure AD, this code here is the ‘auth/office365’ route being called from the code above (frontend).

 

Here the code in node/express

 

var request = require('request');
var config = require('./config.js');
var createSendToken = require('./jwt.js');
var User = require('../models/User.js');

module.exports = function (req,res) {

    config.authCode = req.body.code; // get my code passed from angular

    var url = "https://login.microsoftonline.com/fd4f1e86-7cb0-4ac4-9600-a0e331f0ee06/oauth2/token";  // tenant ID in yellow, Note: I could pass this through from front end also 
    var clientSecret = 'UwCr/kLcQ9xvm346546546546545646542cc='; // client secret ( that is what I got from Azure AD when I set up the app ( I could also pass this through from front end but choose to put here. I would likely put in a config file instead of putting it in here
    var resource = 'https://graph.microsoft.com/';
    var apiUrl = "https://graph.microsoft.com/beta/me";

    var data = 'client_id=076dd0d4-ec11-4654654654654564’ 
        + '&redirect_uri=http://localhost:8000'
        + '&client_secret=' + encodeURIComponent(clientSecret)
        + '&grant_type=authorization_code'
        + '&code=' + req.body.code
        + '&resource=' + encodeURIComponent(resource);
 
//notice I encodeURI a the client secret, and resourse ( you must do this ). Also I hard coded in my client ID in the string builder above, but you could just pass that through from front end.
 
// now I build my request

    var opts = {
        url: url,
        body: data,
        headers : {
            'Accept' : 'application/json',
            'Content-Type' : 'application/x-www-form-urlencoded'
        }
    };

    // makes a call and gets an access token
    request.post(opts, function (err, response, token) {
        //var parsedToken = JSON.parse(token.body);
        var parsedToken = JSON.parse(token);
        var accessToken = parsedToken["access_token"];
        //console.log(accessToken);

        // now we get ready to do a get call and get the users profile from the graph
        var headers = {
            'Accept': 'application/json',
            //'Content-Type': 'application/json;odata=verbose',
            'Authorization': 'Bearer ' + accessToken
        }
 
// !!! you must use this in your request – see below: secureProtocol: 'TLSv1_method'  

        request.get({
            url:apiUrl,
            agentOptions: {
                secureProtocol: 'TLSv1_method'  
            },
            headers:headers,
            json:true
        },function(err, response, body){
                console.log(body);
            User.findOne({azureId: body.mail}, function (err, foundUser) {
                if(foundUser) return createSendToken(foundUser, res);
                var newUser = new User();
                newUser.email = body.mail;
                newUser.azureId = body.mail;
                newUser.displayName = body.displayName;
                newUser.save(function (err) {
                    if(err) return next(err);
                    createSendToken(newUser, res);
                });
            });
        });

 

So this code takes the code obtained from front end, goes and gets its access_token, makes a call to the graph API ( which is in beta ‘so this will change soon’), and get the user info. Then I do the standard stuff, like check if user exists in Mongo, if not, create the user etc etc with an AzureID field. I could not find a uniqueID from the graph data returned, like you get with google, facebook etc. So for now I just use the users email address. Not the best, but you may be able to find the proper unique ID in Azure ID, and populate that.

 

I hope this provides the info you need!

 

If you need more understanding about the authentification cycle, you can also leverage Kirt from MS example here https://github.com/OfficeDev/O365-Node-Express-Ejs-Sample-App . He using node/express but not with an angular front end however. But you can see a bit more about calling the various endpoints.

 

I hope this helps, And I’d love to see Azure AD support for satellizer, that would be awesome mate!

 

Any other help or questions, just let me know

 

Cheers

 

Nigel

**Comment by sahat** [comment]
I have decided not to add Azure AD authentication after all. It was the most frustrating experience. Their single sign-on process is either broken or just so horribly unintuitive. I couldn't even get past sign in popup to get `authorization code`. The page kept redirecting back after clicking on my account to `https://login.microsoftonline.com/common/reprocess?sessionId=......`. And if I were to log out I couldn't get to sign-in at all. When I enter an email and press TAB to enter a password, it automatically tries to sign you in, it then redirects to microsoft login, after logging in there, it redirects me back to Azure login. And the cycle repeats.

**Comment by nigel-dewar** [comment]
Hi Sahat,

 

Im really sorry you had this experience. Yes it was very frustrating for me too. I’ve had a good rant and rave at MS about it, and said they need to sort their #@@# out because no-one will deal with this rubbish long term.

 

I noticed that you are using the /common/ endpoint. That wont work for you. /common/ is used when you are creating a multi-tenant app. You need to use your ‘tenant ID’, in the endpoint. See below.

 

I know its really confusing, but a multi-tenant app is setup differently in Azure AD. If you have not set the application in Azure AD control panel to be ‘multi-tenant’, then I imagine you would be trying the /common/ endpoint all you want and getting nowhere. 

 



 



 

But I understand if your really frustrated and don’t want to bother. It is a pain and I’ll be sure to let a couple of dudes at MS know about your troubles, as further emphasis to the fact that ‘this rubbish is not good enough guys!’.

 

Anyway, if your still curious, try using the endpoint with your tenantID, and you should be able to get your code back.

 

Cheers

**Comment by nigel-dewar** [comment]
I’ll send you a word doc fully screenshotted later with the whole process that I used. From setting up in Azure AD, testing in Fiddler, ( common pitfalls I found ), and then my setup in node/express/angular. Initially when I started I spent 1 hour to hook up to google, 1 hour further to get FB and twitter, not a prob. Azure AD, cost me almost a week and A LOT of research. Absolute joke the company turned into under Steve Balmer. Hopefully this new guy can fix the company up otherwise it will be the new IBM for sure, give them enough time to hang themselves.

**Comment by partha360** [comment]
Hi Nigel, where you able to upload working example with Azure AD?

**Comment by khuongduybui** [comment]
My answer could be too late, but here it is anyway:
I was able to, extremely simply, get Satellizer to work with Azure AD auth:
```
  $authProvider
    .oauth2({
      name: 'aad', // whatever you want to call it
      clientId: '', // this must be an app registered inside the Office 365 account, not a personal account
      url: 'http://127.0.0.1:8080/auth/token/microsoft', // this is my back-end route
      authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      redirectUri: window.location.origin,
      requiredUrlParams: ['scope'],
      scope: ['user.read'],
      scopeDelimiter: ' '
    });
```

**Comment by nigel-dewar** [comment]
Its not late and im glad somebody finally answered this.

Cheers!!!!


Sent from Samsung Mobile


-------- Original message --------
From: "Duy K. Bui"
Date:01/10/2016 15:05 (GMT+10:00)
To: sahat/satellizer
Cc: nigel-dewar , Mention
Subject: Re: [sahat/satellizer] Azure AD ? (#453)


My answer could be too late, but here it is anyway:
I was able to, extremely simply, get Satellizer to work with Azure AD auth:

  $authProvider
    .oauth2({
      name: 'aad', // whatever you want to call it
      clientId: '', // this must be an app registered inside the Office 365 account, not a personal account
      url: 'http://127.0.0.1:8080/auth/token/microsoft', // this is my back-end route
      authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/v2.0/authorize',
      redirectUri: window.location.origin,
      requiredUrlParams: ['scope'],
      scope: ['user.read'],
      scopeDelimiter: ' '
    });


-

**Comment by nsteenbeek** [comment]
Thanks to @khuongduybui's solution I found a working solution my side. If his one doesn't work, maybe my one will help.

```
let url: 'http://127.0.0.1:8080/auth/token/microsoft'; // this is my back-end route
$authProvider
    .oauth2({
      name: 'aad', // whatever you want to call it
      clientId: '', // this must be an app registered inside the Office 365 account, not a personal account
      url: url,
      authorizationEndpoint: 'https://login.microsoftonline.com/common/oauth2/authorize',
      redirectUri: window.location.origin, //"http://localhost" for Cordova apps
      responseType: 'token',
      requiredUrlParams: ['resource'],
      resource: url
    }); 
```

**Comment by LTAravindh** [comment]
Can anyone share server side code for this changes?
If we do Google authentication, we will use `GoogleClient`. For Azure AD what class we need to use?

**Comment by khuongduybui** [comment]
My server side code is in NodeJS.

```javascript
 /**
   * Login with Azure AD.
   */
  server.post('/auth/token/microsoft', (req, res) => {
    fetchOAuthProfile(
        'https://login.microsoftonline.com/common/oauth2/v2.0/token',
        'https://graph.microsoft.com/v1.0/me', {
          code: req.body.code,
          client_id: req.body.clientId,
          client_secret: config.auth.aad.clientSecret,
          redirect_uri: req.body.redirectUri,
          grant_type: 'authorization_code'
        }
      ).then((profile) => {
        // Make sure profile has "email" and "displayName" fields.
        profile.email = profile.mail || profile.userPrincipalName;
        profile.microsoftUserId = profile.id;

        return profile;
      })
      .then(generateTokenForProfile)
      .then((token) => res.send({
        token: token
      }))
      .catch(res.send.bind(res, 500));
  });
```

and my `fetchOAuthProfile` is a generic one that is shared between Google, Facebook, Live, and Azure AD

```javascript
function fetchOAuthProfile(accessTokenUrl, profileUrl, params) {
  return request
    // Step 1. Exchange authorization code for access token.
    .postAsync(accessTokenUrl, {
      json: true,
      form: params
    })
    .then((response) => response.body)
    // Step 2. Retrieve profile information about the current user.
    .then((token) => {
      if (token.error) {
        console.error(token);
        throw token.error;
      }
      return request.getAsync({
        url: profileUrl,
        headers: {
          Authorization: 'Bearer ' + token.access_token
        },
        json: true
      });
    })
    .then((response) => response.body)
    .then((profile) => {
      if (profile.error) {
        console.error(profile);
        throw profile.error;
      }
      return profile;
    });
}
```

**Comment by LTAravindh** [comment]
@khuongduybui thanks to share your code.
But I need to do this with C#. 
Finally I done this by using below codes:

```
protected override void BeforeGetAccessToken(BeforeAfterRequestArgs args) {

            args.Request.AddObject(new {
                code = args.Parameters.GetOrThrowUnexpectedResponse("code"),
                client_id = Configuration.ClientId,
                client_secret = Configuration.ClientSecret,
                redirect_uri = Configuration.RedirectUri,
                grant_type = "authorization_code",
                resource = "https://graph.microsoft.com/"
            });
        }
protected override UserInfo ParseUserInfo(string content) {
            var response = JObject.Parse(content);
            return new UserInfo {
                Id = response["id"].Value<string>(),
                Email = response["userPrincipalName"].SafeGet(x => x.Value<string>()),
                FirstName = response["givenName"].Value<string>(),
                LastName = response["surname"].Value<string>(),
            };
        }
 /// <summary>
        /// Defines URI of service which issues access code.
        /// </summary>
        protected override Endpoint AccessCodeServiceEndpoint {
            get { return new Endpoint { BaseUri = BaseURI, Resource = "/" + TenentId + "/oauth2/authorize" }; }
        }

        /// <summary>
        /// Defines URI of service which issues access token.
        /// </summary>
        protected override Endpoint AccessTokenServiceEndpoint {
            get { return new Endpoint { BaseUri = BaseURI, Resource = "/" + TenentId + "/oauth2/token" }; }
        }

        /// <summary>
        /// Defines URI of service which allows to obtain information about user which is currently logged in.
        /// </summary>
        protected override Endpoint UserInfoServiceEndpoint {
            get { return new Endpoint { BaseUri = "https://graph.microsoft.com", Resource = "/v1.0/me" }; }
        }
```
