### ISSUE TITLE
Using the satellizer client sample with nodeJs sample and getting popup problem.

### ISSUE THREAD

**Issue by paulvanbladel** [sahat/satellizer#461]
I'm taken the latest sources from github and using the client sample together with the nodeJs sample.
I registered correctly a google api.
The request towards google is functioning, the popup is shown, I provide the consent details and then the home page of the sample app is shown inside inside the popup window and it is not closed.
I have exactly the same problem with twitter, so probably the problem is simply somewhere in the client sample.
![image](https://cloud.githubusercontent.com/assets/4886272/8277409/cf96b04a-18c2-11e5-9393-e01bb9abe898.png)

**Comment by paulvanbladel** [comment]
When I rollback sattelizer.js to version 0.9.4, without changing anything else, the problem is gone and everything works perfectly.

**Comment by sahat** [comment]
It would be nice to see if you could post console output of both the popup and main window. Something is causing an error which prevents the popup to be closed.

**Comment by paulvanbladel** [comment]
I cant reproduce systematically. Will come back if the problem reoccurs.
Thanks a lot for this great library.
