### ISSUE TITLE
Twitter authentication

### ISSUE THREAD

**Issue by Guiguillermo** [sahat/satellizer#463]
Hello,

I'm trying to authenticate to Twitter from angularjs (full client authentication).
Here is my code : 

	$authProvider.oauth2({
		name: 'twitter',
		redirectUri: window.location.origin,
		clientId: 'HKPLcISTdj7LieFI4FEOLi5Tw',
		authorizationEndpoint: 'https://api.twitter.com/oauth/request_token',
	});

And when I do : 
$auth.authenticate('twitter');
It opens a popup which returns a 404 error.

Thanks for helping me !

**Comment by sahat** [comment]
Twitter uses OAuth 1.0 authorization., not OAuth 2.0. But that's not even the issue here. Have you looked at the README? Satellizer already comes with twitter method:  `$authProvider.twitter(...)`.

**Comment by qpbp** [comment]
Hi, i have the similar issue. How to create the custom Twitter provider. Could you provide some example?
