### ISSUE TITLE
Feature Request: Restrict Google OpenID by Hosted Domain

### ISSUE THREAD

**Issue by rhewitt22** [sahat/satellizer#465]
Google's OpenID supports a [hosted domain (hd)](https://developers.google.com/identity/protocols/OpenIDConnect#hd-param) parameter to restrict accounts to a certain domain.  This is preferable to having a user select a Google account from a different domain and handling the response logic on the backend.  Can this option be added to the list of parameters for `$authProvider`?

```
$authProvider.google({
  hd: 'umd.edu'
});
```

**Comment by sahat** [comment]
Yes, you should be able to, so in addition to what you have, add it to optionalParams:

```
optionalUrlParams: ['display', 'hd'],
```

**Comment by sahat** [comment]
@rhewitt22 did you get it working and if so can I close this issue now?

**Comment by rhewitt22** [comment]
Yes, thanks!

Worked like a charm.

**Comment by MikeWizzard** [comment]
Im not sure this works correctly as i can still login with any email @gmail or @hotmail i have this code at the moment.

 $authProvider.google({
      hd: 'example.com',
      clientId: 'xxxxxxxxxxx.apps.googleusercontent.com',
    });


this.providers = {
                google: {
                    name: 'google',
                    url: '/auth/google',
                    authorizationEndpoint: 'https://accounts.google.com/o/oauth2/auth',
                    redirectUri: window.location.origin,
                    requiredUrlParams: ['scope'],
                    optionalUrlParams: ['display', 'hd'],
                    scope: ['profile', 'email'],
                    scopePrefix: 'openid',
                    scopeDelimiter: ' ',
                    display: 'popup',
                    oauthType: '2.0',
                    popupOptions: { width: 452, height: 633 },
                    state: function () { return encodeURIComponent(Math.random().toString(36).substr(2)); }
                }
            };


is there something wrong or missing? also i cannot see the email when logged in with google on the profile page. i only get image and display name.

Thanks in advance

**Comment by houssem-yahiaoui** [comment]
hey  @MikeWizzard  check : #1057 hope it helps !
