### ISSUE TITLE
Can´t return to my mobile app after login

### ISSUE THREAD

**Issue by denialtorres** [sahat/satellizer#470]
Hello everyoe.

I finally can sing up and login with gmail,twiiter,facebook on my website app (https://rails-tutorial-denialtorres.c9.io) with your module, I'm using ionic framework with cordova on the client side (android) and ruby on rails for the server side.

the problem is that when i´m login with my social credentials a little pop-up window (inappbrowser plugin) appears but never closes, so i´m navigating my website app on the pop-up window instead of the mobile app,

and the mobile app does nothing, it still remains in the main window where you are prompted for credentials

any suggestian with that ??

regards

**Comment by sahat** [comment]
Check to make sure your `redirectUri` is configured properly.

**Comment by clarle** [comment]
Hi @denialtorres,

Let us know if @sahat's suggestion works. Feel free to re-open this issue if you think there might still be an issue in Satellizer.

Thanks!
