### ISSUE TITLE
Twitter OAuth GET instead POST

### ISSUE THREAD

**Issue by hadokee** [sahat/satellizer#473]
I see your example in node.js for twitter OAuth:

`app.post('/auth/twitter', function(req, res)`

But when I try to use twitter provider it starts a GET request instead POST:

```
$authProvider.twitter({
	url: '/token',
});
```

So I receive this from node server:
```
Cannot GET /token
```

**Comment by sahat** [comment]
Which version of Satellizer are you using?

**Comment by hadokee** [comment]
0.10.1

**Comment by hadokee** [comment]
ok it send POST request in the latest release
