### ISSUE TITLE
Facebook OAuth not working: "Origin 'http://localhost:3000' is therefore not allowed access."

### ISSUE THREAD

**Issue by masiarb** [sahat/satellizer#476]
Hello, new to satellizer & angular in general. I've set up a simple Facebook login on the client side:

```javascript
angular.module('CODLogin', ['satellizer'])
    config(function($authProvider) {
          $authProvider.facebook({
          clientId: 'myappid'
});

//[...]

angular.module('CODLogin')
   .controller('LoginCtrl', function($auth) {
     this.authenticate = function(provider) {
     $auth.authenticate(provider);
     /*$auth.link(provider).then(function(data) {
             console.log(data);
     });*/
};
```

And on the server I'm using passport-facebook, but nothing is reaching there, so I will not show the code here. Basically when I click on my FB login banner the pop-up opens. The first time it asked me if I wanted to let the app use my data, the following times I clicked the FB login banner the pop-up opened, but closed after a short while (since I gave permissions I guess it's an expected behaviour).

When the banner closes, in the console I get the following error: 

     XMLHttpRequest cannot load https://www.facebook.com/v2.2/dialog/oauth?response_type=code&redirect_uri=..... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.

Shouldn't auth work with apps hosted in localhost? Moreover I don't get why it's going to v2.2 given the fact that in the satellizer.js code, there is "v2.3" in the facebook oauth url.

Any thoughts?

**Comment by aligajani** [comment]
You have to setup things in the Developer Console inside your Facebook App.

On Fri, Jul 10, 2015 at 3:07 PM, masiarb <notifications@github.com> wrote:

> Hello, new to satellizer & angular in general. I've set up a simple
> Facebook login on the client side:
>
> angular.module('CODLogin', ['satellizer'])
>     config(function($authProvider) {
>           $authProvider.facebook({
>           clientId: 'myappid'
> });
> //[...]
>
> angular.module('CODLogin')
>    .controller('LoginCtrl', function($auth) {
>      this.authenticate = function(provider) {
>      $auth.authenticate(provider);
>      /*$auth.link(provider).then(function(data) {             console.log(data);     });*/
> };
>
> And on the server I'm using passport-facebook, but nothing is reaching
> there, so I will not show the code here. Basically when I click on my FB
> login banner the pop-up opens. The first time it asked me if I wanted to
> let the app use my data, the following times I clicked the FB login banner
> the pop-up opened, but closed after a short while (since I gave permissions
> I guess it's an expected behaviour).
>
> When the banner closes, in the console I get the following error:
>
>  XMLHttpRequest cannot load https://www.facebook.com/v2.2/dialog/oauth?response_type=code&redirect_uri=..... No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:3000' is therefore not allowed access.
>
> Shouldn't auth work with apps hosted in localhost? Moreover I don't get
> why it's going to v2.2 given the fact that in the satellizer.js code, there
> is "v2.3" in the facebook oauth url.
>
> Any thoughts?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahat/satellizer/issues/476>.
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by masiarb** [comment]
Hi, thanks for the reply. I Actually set it up correctly ("http://localhost:3000/") on Facebook in the App page.

**Comment by sahat** [comment]
@masiarb Are you running your client and server apps on different ports? If for example your Angular app is on http://localhost:8000 and server is on http://localhost:3000 you will get that message if you haven't explicitly configured CORS support on the server. And yes Satellizer does use v2.3 Graph API so I am not sure why are you seeing v2.2. Try downloading *satellizer.js* directly from GitHub.

**Comment by sahat** [comment]
Closing this issue. Seems like it's an error on your side because you haven't set up CORS properly.

**Comment by sharduul** [comment]
I have the same issue. 
My client and server apps are on different port. I also configured CORS support on my server.
But, I am still facing this issue. Could you please help me?

**Comment by nanocity** [comment]
Same here, server and client running on the same port and still getting CORS problem.

Backend is RoR 4 + Devise. I use Facebook and Twitter providers with the same problem on both.

**Comment by nanocity** [comment]
Hi all, I finally found what was causing the issue with RoR 4 + Devise + Omniauth. 

They are not meant to play together with Satellizer. Omniauth always redirects browser when Satellizer calls /auth/:provider causing the CORS message to raise. So basically I misunderstood how Satellizer works.

Not sure if OP had the same problem given he was on nodejs.
