### ISSUE TITLE
Can't get Facebook Integration to work.

### ISSUE THREAD

**Issue by nesh170** [sahat/satellizer#489]
What should I put in as my valid callback URL.

Currently I listed the Site URL as http://localhost:3000/ but what should I use for the Callback URL. I am building this on Cordova and Angular.JS

Thanks

**Comment by sahat** [comment]
Here are my Facebook Ionic settings.

<img width="759" alt="screenshot 2015-07-23 21 14 57" src="https://cloud.githubusercontent.com/assets/544954/8867581/f34f4148-317f-11e5-8ec1-781ec24af1bf.png">

If you look at Ionic example, I think redirectUri is set to `localhost/` there as well.

**Comment by nesh170** [comment]
Thanks
