### ISSUE TITLE
Facebook OAuth2 returns no authorization code

### ISSUE THREAD

**Issue by SnakeME** [sahat/satellizer#490]
Hey,

I currently try to get the satellizer Facebook Login to work on my localhost environment.
But when I call the Facebook API via the $auth.authenticate() function the returned code from facebook is always empty.

I've tried to debug the issue and therefore included at line 515 in the satellizer.js the following:
console.log(data);

And the result looks like this:
Object { code: undefined, clientId: "XXXXXXXXXXXXX", redirectUri: "http://localhost/" }

![screen](https://cloud.githubusercontent.com/assets/1651752/8876042/6e42e0ba-321d-11e5-8aab-8e2d40ca21ad.jpg)

Maybe this could be an issue because the acutal version for Facebook OAuth is V2.4 and satellizer uses 2.3? If you create a new app you can not switch back to an older version.

**Comment by sahat** [comment]
Works fine here with 2.3 app and 2.4 app. Also, if I understand correctly Facebook will automatically use the latest version even if you access the API with v2.2 or v2.3 parameter.

<img width="1191" alt="screenshot 2015-07-24 09 07 18" src="https://cloud.githubusercontent.com/assets/544954/8879009/6afde3b2-31e3-11e5-8cbb-7deeef31420f.png">

**Comment by SnakeME** [comment]
Any idea what the problem could be? I've tested it on two different computers on two different browsers with the latest version. Here are my facebook app settings:

![screen](https://cloud.githubusercontent.com/assets/1651752/8883038/2c0e2306-324c-11e5-9541-1573665cfbc8.jpg)

**Comment by SnakeME** [comment]
UPDATE: I found out what the problem caused. I had to specific the redirectUri for facebook.

$authProvider.facebook({
  redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host + '/'
});

didn't work for me.

Now with the updated redirectUri it's working fine:

$authProvider.facebook({
  redirectUri: 'http://localhost/project/login
});

**Comment by sahat** [comment]
That's fine, the reason why I made `redirectUri` a configurable property in the first place is so that you can override it when necessary, like in this case.

**Comment by niemyjski** [comment]
@sahat upon further looking I think I may be hitting this to only on windows 10 with edge and ie11. I'm not seeing it in any other browser...

**Comment by niemyjski** [comment]
I see the code being returned as a query string parameter...

![image](https://cloud.githubusercontent.com/assets/1020579/9046720/5bbe9bd2-39f2-11e5-9d09-c383f9b19cb2.png)

but when it auths it doesn't contain code, only clientid and redirecturi.

**Comment by niemyjski** [comment]
But the wierd thing is with the latest release is if I click on the social login, it will use the new oauth tab to log me into the site instead of closing it and using the previous one.
