### ISSUE TITLE
Facebook Malformed access token?

### ISSUE THREAD

**Issue by mackelito** [sahat/satellizer#491]
I have everything setup and I get a json response containing
- clientId
- code
- redirectUrl

But it is not logging me in.. from my server I get a 409 conflict.
When I test the code I get back on https://graph.facebook.com/me?access_token=myCodeIGetInTheResponse

I get a "Malformed access token" message?

**Comment by mackelito** [comment]
Anyone with a idea?

All I have set is
```
    $authProvider.facebook({
      clientId: 'myId',
      url: '/auth/facebook',
      scope: 'email'
    });
```

and then I have setup some settings for authProvider.

**Comment by kimiBST** [comment]
You need to make another request asking for the the access_token.

Something like GET /'https://graph.facebook.com/oauth/access_token?code={code}&client_id={clientId}&redirect_uri={redirecturi}'

**Comment by sahat** [comment]
`code` is not the same as `access token`. Look at the example here https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js#L477 with step by step comments of the entire flow from obtaining the `code` > exchange it for `access_token`, then querying the Graph API.
