### ISSUE TITLE
$auth.logout() not clean facebook session (Cannot make new account after logout)

### ISSUE THREAD

**Issue by wuilmeryair** [sahat/satellizer#494]
I am using $auth.logout() method to logout app, but when I try again with facebook login the application does not ask login credentials.

The bug can be reproduced in the demo https://satellizer.herokuapp.com/

1. Login with facebook user
2. Logout 
3. Click Login with facebook => the application does not ask facebook login credentials

**Comment by sahat** [comment]
@wuilmeryair It's not a bug. You are logging out from your application, not Facebook, when you call `$auth.logout()`. If you want to log out from Facebook as well you should consider using Facebook JavaScript SDK.

**Comment by correasebastian** [comment]
hi @sahat, @wuilmeryair , any idea how to accomplish that (close the facebook  session too)? , can i use the facebook javascript sdk  without affecting the functionality of Satellizer ?(because is working really good in my ionic app), but i have to close the facebook session somehow

thanks

**Comment by wuilmeryair** [comment]
I solved the problem call facebook url logout (https://www.facebook.com/logout.php?access_token=FFFFFFFFFFFFFFFFF...GGG&next=/) with the following code:


  $scope.logout = function()
  {
    var token = $auth.getPayload().access_token;
    $auth.logout().then(function() {
             
              var options = {
                location: 'yes',
                clearcache: 'yes',
                toolbar: 'yes'
              };

              if (typeof token !== "undefined")
              {
                //localhost
                var url = 'https://www.facebook.com/logout.php?access_token='+ token + '&next=http://localhost:8100/';
                //app
                if (ionic.Platform.isIOS() || ionic.Platform.isAndroid()) 
                    url ='https://www.facebook.com/logout.php?access_token='+ token + '&next=/';
                  
               $cordovaInAppBrowser.open(url, '_blank', options)
                .then(function(event) {
                  $cordovaInAppBrowser.close();
                })
                .catch(function(event) {
                  $cordovaInAppBrowser.close();
                });


                //Cerrar Pagina login Facebook
                 $rootScope.$on('$cordovaInAppBrowser:loadstop', function(e, event){
                    // insert CSS via code / file
                    $cordovaInAppBrowser.close();
                  });

               
             }
         }
 }

**Comment by correasebastian** [comment]
thaks  @wuilmeryair for your quick reply, ill try and i let you know

**Comment by stepmarti** [comment]
Hi @wuilmeryair, do you know wich is the url to make google logout?

Thanks in advance

**Comment by stepmarti** [comment]
I tried with https://accounts.google.com/Logout? and it seems to be working on.
