### ISSUE TITLE
Provider has not support to customize link feature.

### ISSUE THREAD

**Issue by toancong** [sahat/satellizer#495]
Hi,

Any support to customize link feature? Current it use authen url for both authentication and link provider like that `/auth/facebook`. Could any support `/auth/facebook` to authen and `/auth/link/facebook` to link ?

Thanks!

**Comment by sahat** [comment]
There is no need to do that, because they are practically the same methods. Pretty much all of the linking happens on the server side. So, `$auth.link` just exists for semantic reasons.
