### ISSUE TITLE
Token not being passed

### ISSUE THREAD

**Issue by dineshcooper** [sahat/satellizer#496]
I am using 0.11.3 with Angularjs 1.3.0 - I have implemented the login (laravel-jwt) and I see that the token is being stored in local storage. If I call getPayload and getToken I see the correct info is coming through
however the token is not being passed in the headers in $http requests.

In my angular.module('app').config() I configure satellizer with
$authProvider.loginUrl = urls.AUTH_API + '/login';

Is there something else I need to be setting to get the token added to the Header or is there something else I could be missing?

(As an interim workaround I have added the token manually with my own interceptor)

**Comment by sahat** [comment]
The token should be passed on all HTTP requests after you sign in. Can't say why it wouldn't for you, without looking at your code.

This issue was opened 18 days ago, were you able to resolve it or did you give up on it?

**Comment by LunarDevelopment** [comment]
Are you setting : 

`$authProvider.httpInterceptor = true;`

In your config block ?

**Comment by csrui** [comment]
I'm currently having this issue. 

Authentication works. The "satellizer_token" is stored after login but none of the following $http requests send the token. 

The  $authProvider.httpInterceptor is set to true;

Any thought on what I should check to debug this thing will be greatly appreciated.
