### ISSUE TITLE
auth/{{provider}} 404

### ISSUE THREAD

**Issue by staleyr** [sahat/satellizer#498]
I'm trying to implement satellizer. I've currently enabled facebook and microsoft. However after authenticating through the popup my post auth/facebook or auth/live returns a 404. I see where the "/auth/facebook" is setup in the satellizer config, however from what i can see there's no real auth controller or action. Can anyone point me in the right direction?

http://depict.azurewebsites.net/#/Login

**Comment by staleyr** [comment]
It seems auth/facebook is supposed to be a POST api endpoint, is that correct?

**Comment by aligajani** [comment]
Yeah

**Comment by staleyr** [comment]
Sounds good, I'll have a swing at the c# version.
