### ISSUE TITLE
Token key should be "access_token"

### ISSUE THREAD

**Issue by hkdobrev** [sahat/satellizer#50]
On this line: https://github.com/sahat/satellizer/blob/5bb71949d8075c9122e72a693dc798129b6ba6b3/satellizer.js#L284,

Satellizer is expecting in the JSON response the token to be in the key `token`. However the spec says it should be `access_token`: http://tools.ietf.org/html/rfc6749#section-5.1

I am working with https://github.com/bshaffer/oauth2-server-php and it is highly configurable about anything including query keys, key names and others. However it does not allow configuring the keys of this particular response, because this is what the specification defines: https://github.com/bshaffer/oauth2-server-php/blob/6a30b9b67ae35c228e852109ed743bf34da22568/src/OAuth2/ResponseType/CryptoToken.php#L86-L91

I think Satellizer should respect the specification or at least provide a configuration about the token key to read from the data.

**Comment by pickjonathan** [comment]
@sahat hey there ! im trying to implement satellizer --> all going well until closing the popup page.. 
closing the pop up page resolve in an error

 "message: "Expecting a token named "token" but instead got: "…nav-view></ion-nav-view>\n</body>\n</html>\n\n\n""" (my index.html page)

the oauth2 provider is google and i can see in satellizer.js that the promise qs has the parameter "code" in it and its all looking good .. 

Im using ionic framework and running it on google app engine using go(lang)..

the error respond i get is my complete index.html page .. 

Thanks mate !! T sure need some help ..

**Comment by anjum121** [comment]
@sahat  same Error: Expecting a token named "access_token" but instead got: "<!DOCTYPE html>\n<html>\n  <head>\n  ....

Any idea how to fix it wasted full day on this

**Comment by philippeluickx** [comment]
@pickjonathan @anjum121 I had something similar. Basically you need to have your backend accept POST from e.g. localhost:3000/auth/facebook. Expect a code as input.
If this POST is not accepted (i.e. does not exist) then typically you would just get to your base template as a response.

https://github.com/sahat/satellizer/wiki/Login-with-OAuth-2.0

Hope this helps.

**Comment by philippeluickx** [comment]
@sahat having the access_token response type would be immensively useful IMO. Both in android (ANSE) and django (allauth + rest_auth) libraries the expected output/input is an access_token.
Maybe this is something you can add in the config for each provider seperatly?
