### ISSUE TITLE
Small issue in Java Twitter Example

### ISSUE THREAD

**Issue by blasd** [sahat/satellizer#501]
The method accept GET while Satellizer does a POST even for Twitter. Thanks for the great work.

**Comment by blasd** [comment]
My bad, it uses GET because Twitter is supposed to follow OAuth1. Is there any support for Twitter over OAuth2 ?

**Comment by blasd** [comment]
There is no issue. Twitter accepts OAuth2 for App-Only authentication. User authentitacation needs to use OAuth1. OAuth1 is supposed to do GET calls. However, Satellizer does POST fron 0.11.X . Another issue has been open for this.

**Comment by sahat** [comment]
I'll accept a pull request that changes the Twitter auth from GET to POST in Java example. I am not too familiar with Java and due to time constraints it's hard to update the library as well as every example in all languages.
