### ISSUE TITLE
Can't sign in with google account.

### ISSUE THREAD

**Issue by nakarin4350** [sahat/satellizer#502]
I try to use the server and client from examples folder when I try to sign in by using google account.
![capture](https://cloud.githubusercontent.com/assets/8923854/9020863/af6dde36-384f-11e5-988b-4138b7b16d17.PNG)
After I click accept the popup windows close,but the page does not redirected to anywhere
(still at http://localhost:8000/#/login) .My redirect uri configs.
![capture1](https://cloud.githubusercontent.com/assets/8923854/9020876/8a868310-3850-11e5-8c25-36e23612879c.PNG)
And my log in console.
![image](https://cloud.githubusercontent.com/assets/8923854/9020885/f8504e6c-3850-11e5-99e9-d0a837cfe308.png)
I use google chrome browser,Thx for your helps.

**Comment by rjgarciadelpino** [comment]
I have the same problem, did you get a solution?

**Comment by nakarin4350** [comment]
Sorry,no luck yet.

**Comment by sahat** [comment]
Which example are you using? @nakarin4350 

It seems like your back-end implementation does not support POST method.

**Comment by sahat** [comment]
Also, your Google API settings look correct to me.

**Comment by nakarin4350** [comment]
I use this example "https://github.com/sahat/satellizer/tree/master/examples/client".

**Comment by sahat** [comment]
@nakarin4350 I meant which server example or did you write your own?

**Comment by nakarin4350** [comment]
I use this server example "https://github.com/sahat/satellizer/tree/master/examples/server/node".

**Comment by sahat** [comment]
@nakarin4350 So, let me see, you are running client example on port 8000 via Python HTTP server and node.js example on port 3000?

Notice the error, it is trying to POST `/auth/google`. But relative to `http://localhost:8000` (where you are running the client app) there is no `/auth/google` route, because that's on the server at `http://localhost:3000/auth/google`.

Update google config:
```js
$auth.google({
  clientId: 'your client id',
  url: 'http://localhost:3000/auth/google'
});
```

Or add this line, which will affect all provider configs:

```js
$authProvider.baseUrl = 'http://localhost:3000';
```

**Comment by nakarin4350** [comment]
I just got this "XMLHttpRequest cannot load http://localhost:3000/auth/google. A wildcard '*' cannot be used in the 'Access-Control-Allow-Origin' header when the credentials flag is true. Origin 'http://localhost:8000' is therefore not allowed access.",sorry I just newbie.

**Comment by sahat** [comment]
@nakarin4350 Try setting `$authProvider.withCredentials = false`.

**Comment by nakarin4350** [comment]
@sahat  I still got this {"message":"Invalid Credentials"}.

**Comment by sahat** [comment]
Have you updated client id in *app.js** and client secret in *config.js* files?

**Comment by nakarin4350** [comment]
I think the sign in is working now but after I go to profile page,I got this error "GET http://localhost:8000/api/me 404 (File not found)"

**Comment by nakarin4350** [comment]
It 's working now,thank you very much.Cheers.

**Comment by sahat** [comment]
Glad you got it resolved!
