### ISSUE TITLE
Should OAuth1 do GET or POST on /auth/provider?

### ISSUE THREAD

**Issue by blasd** [sahat/satellizer#504]
In 0.11.0, we do a POST:
```java
            oauth1.exchangeForToken = function(oauthData, userData) {
            var data = angular.extend({}, userData, oauthData);
            var exchangeForTokenUrl = config.baseUrl ? utils.joinUrl(config.baseUrl, defaults.url) : defaults.url;
            return $http.post(exchangeForTokenUrl, data, { withCredentials: config.withCredentials });
          };
```

However in 0.10.1, we do a GET:
```java
oauth1.exchangeForToken = function(oauthData, userData) {
            var data = angular.extend({}, userData, oauthData);
            var qs = oauth1.buildQueryString(data);
            var exchangeForTokenUrl = config.baseUrl ? utils.joinUrl(config.baseUrl, defaults.url) : defaults.url;
            return $http.get(exchangeForTokenUrl + '?' + qs);
          };
```

Following https://github.com/sahat/satellizer/wiki/Login-with-OAuth-1.0, we expect a GET. In the Java example, we accept only GET for twitter, which accepts only OAuth1

Thanks

**Comment by sahat** [comment]
OAuth 1 has been changed to POST to be consistent with OAuth 2. I haven't had a chance to update the wiki, so for now I just put up a notice that says "OUTDATED". It's not too different really, only the first few steps need to be changed.

**Comment by sahat** [comment]
I have updated the wiki page for OAuth 1.0.
