### ISSUE TITLE
setToken() and redirect parameter - possible wrong use?

### ISSUE THREAD

**Issue by RatkoR** [sahat/satellizer#507]
Hi all,

I'm wandering if redirect parameter in the [setToken()](https://github.com/sahat/satellizer#authsettokentoken-redirect) method is used ok?

The documentation states that redirect is: *An optional boolean value that controls whether or not to redirect to loginRedirect route after saving a token. Defaults to false.*  

So, Default to false means we don't get redirected to *loginRedirect*. But [code](https://github.com/sahat/satellizer/blob/master/satellizer.js#L326) seems to do just that - we're redirected to *loginRedirect* if it's set to false and if it is set to some string value, we redirect there.  

So we're **not** being redirected only if it's set to **true**. Which is a bit weird, no?

**Comment by venil7** [comment]
I would like to second this issue, `redirect` should definately not be part of `setToken`.
at the moment I'm avoiding this behavior by setting `$authProvider.loginRedirect = false` but that feels like a hack..

**Comment by sahat** [comment]
I agree, this was a hacky way to do it. Going forward, setToken() will no longer have the `redirect` parameter, and all loginRedirect, logoutRedirect, signupRedirect config options are going awar for the sake of simplicity and to have less maintenance work for me.

If you rely on any of those redirects, you'll have just have to redirect yourself from one of the controllers using `$location.path`, and if you are not relying on redirects, then you can actually remove a few lines, like in the case above - `$authProvider.loginRedirect = false`.

**Comment by sahat** [comment]
Resolved in [0.12](https://github.com/sahat/satellizer/releases/tag/0.12.0) release.
