### ISSUE TITLE
400 Bad request when using Amazon s3

### ISSUE THREAD

**Issue by fligen** [sahat/satellizer#508]
I have everything working just fine on using satellizer with one exception.  When the user is authorized and trying to post an image to S3 the request is denied due to the Authorization header being in place on the S3 post.  I have looked though the documentation but have not been able to come up with a solution to bypass the header injection on the S3 post. any ideas?

Update:
We are using angular 1.4 with laravel 5.1

**Comment by Pietro-Vis** [comment]
Have you tried with this?https://github.com/sahat/satellizer/blob/master/README.md#not-sending-the-jwt-for-specific-requests

**Comment by fligen** [comment]
I have, I have set it in the config with no joy and also the controller with no joy.  Where would I place this to work?

**Comment by fligen** [comment]
$http({
  url: 'https://s3-us-west-2.amazonaws.com/dun4me',
  skipAuthorization: true,
  method: 'POST'
});

is what I have, I added a "," after skipAuthorization and set the url to my S3 bucket url the error I get now is:
POST https://s3-us-west-2.amazonaws.com/dun4me 412 (Precondition Failed)

**Comment by fligen** [comment]
Got it, thanks for your help.

**Comment by Pietro-Vis** [comment]
@sahat i think you can close this one.
