### ISSUE TITLE
permanent login?

### ISSUE THREAD

**Issue by am3000** [sahat/satellizer#509]
- Can I keep users logged in for like a month or more with satellizer?
- Where can I set the expiration time of the JWT?

Sorry for my newbisch questions ...

**Comment by Pietro-Vis** [comment]
Look this: https://github.com/sahat/satellizer#authisauthenticated
On your server side, when you create the json web token to send to satellizer in frontend, add an 'exp' field to the token, with a value in seconds, corresponding to the expiry time.
Then in frontend, when you check the token you can use $auth.isAuthenticated(), which automatically check if the token is expired.
```
$auth.isAuthenticated()
Returns true if a JWT is present in Local Storage and it is not expired, otherwise returns false.
Note: This method expects the exp claim to check for the expiration time.
```

**Comment by sahat** [comment]
It is done on the server. For example, in Node.js:

```js
/*
 |--------------------------------------------------------------------------
 | Generate JSON Web Token
 |--------------------------------------------------------------------------
 */
function createJWT(user) {
  var payload = {
    sub: user._id,
    iat: moment().unix(),
    exp: moment().add(14, 'days').unix()
  };
  return jwt.encode(payload, config.TOKEN_SECRET);
}
```
