### ISSUE TITLE
Twitter authentication with node server

### ISSUE THREAD

**Issue by root-io** [sahat/satellizer#510]
I tried to implement the node server example but Twitter returns me:

`{"<?xml version":"\"1.0\" encoding=\"UTF-8\"?>\n<hash>\n  <error>Desktop applications only support the oauth_callback value 'oob'</error>\n  <request>/oauth/request_token</request>\n</hash>\n"}`

**Comment by sahat** [comment]
Did you set Callback URL on the Twitter's app settings page?
