### ISSUE TITLE
In firefox one in two times the oauth login fails cause the popup closes too fast

### ISSUE THREAD

**Issue by chanar** [sahat/satellizer#513]
I have the exact same problem as with the following githubber have with authentication module for ember.js

I tried adding setTimeout(function() { window.close event }, 500) but it has not solved the problem. 
 
Link to ember.js project: https://github.com/Vestorly/torii/issues/133

Has anybody else had similar issue with satellizer ?

Thanks!

**Comment by sahat** [comment]
@chanar Can you post exact steps to reproduce this behavior? I have tried authorizing Facebook app for the first time, creating a Private window and re-authenticating with Facebook, but all works fine here in Firefox 39 on Mac OS X.

**Comment by sahat** [comment]
Closing since I couldn't reproduce this issue with any OAuth 2.0 providers, in both Firefox for Windows and Mac.
