### ISSUE TITLE
configure local.login() and local.signup() in angular's config

### ISSUE THREAD

**Issue by mikehm** [sahat/satellizer#514]
I had made changes to local.login() and local.signup() inside satellizer.js. What I want now is to do the configuration inside my app.js file, so future updates to satellizer won't override my changes. I looked at the docs (configuration) and tried using $authProvider and $auth, but I still could not get it to work or figure out what object to use to refer to those two functions from inside my angular config block. Any help would be appreciated.

**Comment by sahat** [comment]
Satellizer does not expose internal login and signup functions. Any changes you make to satellizer.js yourself, it then becomes your responsibility to keep it up date with any changes that I make to the official library. As you have pointed out, you can only call those functions from `$auth` object.
