### ISSUE TITLE
setStorage should be part of $authProvider

### ISSUE THREAD

**Issue by venil7** [sahat/satellizer#516]
`setStorage` should be part of `$authProvider` not `$auth`, as it's being set once at application startup

**Comment by venil7** [comment]
there's a `$authProvider.storage` property..

**Comment by aligajani** [comment]
What dies setStorage do??

On Friday, August 14, 2015, Art Deineka <notifications@github.com> wrote:

> Closed #516 <https://github.com/sahat/satellizer/issues/516>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahat/satellizer/issues/516#event-382899355>.
>


-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by venil7** [comment]
@aligajani sets the storage type to either `localStorage` or `sessionStorage`

**Comment by sahat** [comment]
FYI, going forward with v0.12, it will be called `storageType` and `setStorageType`.

**Comment by venil7** [comment]
@sahat thanks, i have closed this issue, as its no longer relevant
should have RTFMed :)
