### ISSUE TITLE
instagram authentication

### ISSUE THREAD

**Issue by ersensen** [sahat/satellizer#519]
Hi sahat,

There is no instagram auth example code in the node server here https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js.

Can you provide it if you have an example?

Thanks

**Comment by sahat** [comment]
I will add it when I get a chance.

**Comment by sahat** [comment]
Added node.js example and a "sign-in with instagram" button to the angular.js demo app.

**Comment by guilhermecvm** [comment]
@sahat any chances of writing a php example also?

**Comment by sahat** [comment]
@guilhermecvm I can do that, but not right away. I am currently working on implementing the last server-side example on TODO list: C# w/ ASP.NET 5.

**Comment by guilhermecvm** [comment]
That is fine, I try to write it based on the node.js

**Comment by ersensen** [comment]
Hi,

I have updated satellizer package to 0.12.4 with bower. But instagram provider is not there in satellizer.js when i look at the code under bower_components. 

I checked the top of the satellizer.js, it's ok.
/**
 * Satellizer 0.12.4
 * (c) 2015 Sahat Yalkabov
 * License: MIT
 */

I tried to uninstall and reinstall but the same.

Any idea?

**Comment by sahat** [comment]
@ersensen It is only available on `master` branch right now.

**Comment by ersensen** [comment]
ok thanks.

Isn't it possible to get email info by instagram api?

**Comment by sahat** [comment]
I don't believe so but you should double check.

**Comment by sahat** [comment]
PHP example has been updated to include Instagram auth. But do keep in mind Instagram authentication is only available with `satellizer.js` on master branch, the latest version does not have it yet.
