### ISSUE TITLE
I can't run this, it shows me an error

### ISSUE THREAD

**Issue by onlinepch** [sahat/satellizer#520]
Hi, I have an issue with this.
When I click on your home page Login goes to this page and show me this social buttons, but when I downloaded .zip and try it show me an error Forbidden You don't have permission to access / on this server, but look my Set Permissions and they are all check. I can't run this at all! I try to run examples/client/index.html it is the same home page I hope.
Can you help me, thank you.

**Comment by sahat** [comment]
1. Download the project.
2. Run `npm install` inside the project directory.
3. Run `gulp` as well.
4. Launch `mongod` monogdb database server.
5. Run `npm start` in the project directory.
