### ISSUE TITLE
regression at the exchange json object

### ISSUE THREAD

**Issue by adben** [sahat/satellizer#521]
The cleanup introduced by https://github.com/sahat/satellizer/commit/314b0eca806af53a78e0d1ddb675adb62e5ec242 
introduces the hardcoded userData (perhaps for testing) at https://github.com/sahat/satellizer/blob/master/satellizer.js#L467-467
            userData = { foo: { bar: { baz : 1 }}};
but this breaks the Payload validation during the exchange for token on a Java server. when for instance '/auth/google' expecting just "clientId", "redirectUri", "code";

So the client will send something like 
```javascript
{
    "foo": {
        "bar": {
            "baz": 1
        }
    },
    "code": "4/50KBKRgBLdXXXXXXXXXXXXXXXXXXXY",
    "clientId": "XXXXXXX.apps.googleusercontent.com",
    "redirectUri": "http://XXXXXX:9000"
}
```

**Comment by sahat** [comment]
@adben Woops, didn't mean to have that code checked in. I'll fix it right away.

**Comment by adben** [comment]
That was fast!, thank you.
