### ISSUE TITLE
Update README for the 0.12 release

### ISSUE THREAD

**Issue by sahat** [sahat/satellizer#522]

**Comment by mprentic-harris** [comment]
It should include that only Angular 1.4.0+ is supported since you are using `angular.merge` now which doesn't exist in Angular 1.3.x and before.

**Comment by sahat** [comment]
@mprentic-harris Good point, I will need to update `bower.json` dependencies version as well.

**Comment by jayzeng** [comment]
hmmm, how many companies out there are on Angular 1.4.0+? I know most are still on 1.2 and 1.3, can we make it backward compatible with 1.2, at least 1.3?

**Comment by jozsi** [comment]
The `angular.merge` is a breaking change, indeed. I am using Angular 1.3.15 because it's still more recommended than 1.4.x in conjunction with angular-material.

**Comment by sahat** [comment]
I understand that since some people are stuck with 1.3.x, moving forward with 1.4.x just for the `angular.merge` doesn't make much sense. I am going to add a polyfill for the time being. That function won't incur any performance penalties, as it won't be executed on AngularJS 1.4.x. It will increase the minified file size by 463 bytes, which I think is an acceptable trade off.

Meanwhile, if you have a suggestion on how to avoid using `angular.merge` to achieve the same result I'd like to hear your opinion. If I don't find a better solution, I'll push out a patch (0.12.2) with a polyfill later today.

Need to do a deep merge of these two objects. The problem with just using `angular.extend` occurs with **responseParams** (nested object) being overwritten, instead of extended.

```js
var defaults = {
  defaultUrlParams: ['response_type', 'client_id', 'redirect_uri'],
  responseType: 'code',
  responseParams: {
    code: 'code',
    clientId: 'clientId',
    redirectUri: 'redirectUri'
  }
};
```

and

```js
facebook: {
  name: 'facebook',
    url: '/auth/facebook',
    authorizationEndpoint: 'https://www.facebook.com/v2.3/dialog/oauth',
    redirectUri: (window.location.origin || window.location.protocol + '//' + window.location.host) + '/',
    scope: ['email'],
    scopeDelimiter: ',',
    requiredUrlParams: ['display', 'scope'],
    display: 'popup',
    type: '2.0',
    popupOptions: { width: 580, height: 400 },
  responseParams: {
    clientId: 'client_id',
      redirectUri: 'redirect_uri'
  }
}
```

**Comment by sahat** [comment]
Satellizer 0.12.2 is now available and it no longer uses `angular.merge`.

**Comment by sunild** [comment]
Another item for the read me would be the fact that redirects no longer happen automatically.

I'm looking at the commits, and it seems there's quite a bit changing. Anything else that might be worth putting in the documentation?

**Comment by jayzeng** [comment]
We upgraded to 0.12.2 and realized redirect were removed, will be great to update readme to reflect these changes (very much like https://github.com/sahat/satellizer/releases/tag/0.12.0)

**Comment by sahat** [comment]
@jayzeng Will do that tonight.

**Comment by sahat** [comment]
The entire README has been updated top to bottom, so be sure to check it out!

**Comment by mprentic-harris** [comment]
Awesome job on the polyfill and the README looks great!
