### ISSUE TITLE
loginOnSignup option not working anymore

### ISSUE THREAD

**Issue by mbellezi** [sahat/satellizer#524]
When I signup satellizer is not doing  automatically the login anymore. (verion 0.12.1).
Looking the source, the option loginOnSignup is missing. Was this functionality removed from satellizer?

**Comment by sahat** [comment]
@mbellezi yes that is correct, it was removed in 0.12: https://github.com/sahat/satellizer/releases/tag/0.12.0

**Comment by sahat** [comment]
Redirects have been nothing but a headache, that's why it was removed, and delegated to the user to implement that feature. All that `loginOnSignup` flag was doing is calling `setToken()` function after successful `signup(user).then(function() { .... // call setToken } );

**Comment by mbellezi** [comment]
Ok. Thanks for the clarification.
