### ISSUE TITLE
Google+ Login not working

### ISSUE THREAD

**Issue by roychowdhurysourav23** [sahat/satellizer#526]
I am having an issue while integrating google+ (oAuth2) login with angularjs 1.3.X .I made the changes as per the readme.md document but always having an error in saying....
while hitting this function.
$scope.login = function(provider) {
            $auth.authenticate(provider);
    };
Error: angular.merge is not a function
"angular.merge" is under satellizer.js library file. Please find me a solution ASAP.

**Comment by dojadop** [comment]
angular.merge is an angular 1.4 feature. It has been fixed in the 0.12.2 release see #522
