### ISSUE TITLE
state param not set before query string is built

### ISSUE THREAD

**Issue by dojadop** [sahat/satellizer#527]
Dynamic state variable coming from a function worked in 0.11.3 because it was called before the queryString is built:

See https://github.com/sahat/satellizer/blob/0.11.3/satellizer.js#L480-L488

In 0.12.2, the Oauth2.buildQueryString() is called before state is put into local storage so it could be null or it could be the previous state value.

See https://github.com/sahat/satellizer/blob/0.12.2/satellizer.js#L437-L444

**Comment by sahat** [comment]
That was a mistake on my part. I have pushed the fix to master branch, so you can use that file until I bump the version on bower and npm.

```js
            var url;
            var openPopup;
            var stateName = defaults.name + '_state';

            if (angular.isFunction(defaults.state)) {
              storage.set(stateName, defaults.state());
            } else if (angular.isString(defaults.state)) {
              storage.set(stateName, defaults.state);
            }

            url = [defaults.authorizationEndpoint, Oauth2.buildQueryString()].join('?');
```
