### ISSUE TITLE
Social signup

### ISSUE THREAD

**Issue by ersensen** [sahat/satellizer#529]
Hi sahat,

Some web sites like airbnb offer signup with social accounts and some don't. In satellizer live demo the later is the case. 

I prefer to offer social signup, since the users may not go with the login link and miss the social authentication. 

In my app, first I built the login flow with satellizer. Then, I compared the facebook links on signup and login pages of airbnb. They looked the same. I decided to do the same for the signup, i just copied the relevant stuff in my login view and login controller to my signup view and controller without any change, and that's all. And it seems there is no problem.

Suspicious... Am i missing some point?

Thanks

**Comment by sahat** [comment]
No, that's exactly how it works. The logic that decides whether to create a new account or sign-in with an existing  one is on the server.
