### ISSUE TITLE
Add config option

### ISSUE THREAD

**Issue by furyscript** [sahat/satellizer#530]
I need add config paramter to http request, how can I made it?

**Comment by sahat** [comment]
Which HTTP request are you referring to? There are about 6 $http calls in total.

**Comment by furyscript** [comment]
I use authenticate function but I wat to set options parameter of its http request

**Comment by yugen** [comment]
+1

**Comment by yugen** [comment]
@furyscript One way around this until the enhancement gets made is to write an interceptor that adds the config parameter to requests to $authProvider.loginUrl.  Maybe not the most elegant solution, but did the trick for me.
