### ISSUE TITLE
Example profile.js

### ISSUE THREAD

**Issue by bryanrscott** [sahat/satellizer#531]
Hi

I was having a problem with the example client profile.js.    To resolve I changed "then" to "catch" on line 17 in the  $scope.updateProfile function.  This seemed to fit the pattern elsewhere and resolved my console errors.    Just wondering how valid this is?

cheers
Bryan

**Comment by sahat** [comment]
Thanks for reporting the issue. It should have been `.catch()` on line 17. Should be fixed now.
