### ISSUE TITLE
token remains in localstorage after it expires

### ISSUE THREAD

**Issue by ersensen** [sahat/satellizer#533]
Hi,

I set payload exp to 1 minute. After logging in the front end app i wait for 1 minute. Satellizer logouts bu the token remains in the localstorage. It doesnt seem harmful but i just wanted to inform.

**Comment by sahat** [comment]
The token should be removed when you logout, so I will have to investigate this issue further.

**Comment by ersensen** [comment]
Yes when user clicks logout button and calls $auth.logout the token is removed. 

But when the user is away, satellizer logout itself after expiration time. But the token remains in localstorage.
