### ISSUE TITLE
LinkedIn Auth Not working: JWT error ''throw new Error('Not enough or too many segments')"

### ISSUE THREAD

**Issue by leonaburime** [sahat/satellizer#537]
I am able to pass the data to my server and when i debug it, my app shows the correct first and last name.  However when it hits this line of code ..

361: var payload = jwt.decode(token, config.TOKEN_SECRET);

which fails on in jwt.js line 60 -  

  var segments = token.split('.');
  if (segments.length !== 3) {
    throw new Error('Not enough or too many segments');
  }

the token it gets has no periods and fails saying 'Not enough or too many segments'.  Ive done nothing to the server side.  Im thinking that LinkedIn has changed the way their tokens are formatted and is causing this application to break.

**Comment by leonaburime** [comment]
Actually its happening with Google Authentication also.  I suspect Facebook will have the same problem...

**Comment by sahat** [comment]
@leonaburime Can you open the Dev Tools and see the value of the token in Console? Type `localStorage` and you should see something like *satellizer_token* there.

**Comment by leonaburime** [comment]
Hi Sahat,

Thank you for responding so quickly.  This is actually on the server-side node.js code. I had to use the node debugger to see it.  This is my token minus the last couple characters im receiving from 

225: var token = req.headers.authorization.split(' ')[1];

which is...

CAAXJfDxwfXQBAPZCZCyDlgnhEfcGViqJHWidxBpLLq2CpD5g200oXsiGOYVVnSTKMCFOtPuahElbB3ri1R087TxuM8D79qhcIVpGkVI5ZBnK72UPQCa28mBK0eZAlJfZBzUv8IEFaGvfUfAvAySUqwqYbAJ6IGHRzW9gRmT2pLNftULYKGsqcqTtiPtD3

As you can see there are no periods and this is why the jwt.decode is failing.

**Comment by leonaburime** [comment]
Hmmm.. I tried it for Google and Linkedin and the tokens appear identical...

**Comment by sahat** [comment]
@leonaburime do `localStorage.clear()` in the browser. That is not a JWT token. Here is what it looks like:

```js
eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiI1N…UwMn0.z7RWMtcKTmQlayQAqkUOGgJEKZgq1nOYLVuSaam4_bo
```

**Comment by leonaburime** [comment]
This was it exactly.  I must have retained bad values in there from when I was testing earlier.  Now though nothing saves to my database.  What code on the server side in the node/server.js file actually saves it to mongodb using mongoose?  I cant find it...

**Comment by sahat** [comment]
It's this code here:

```js
        // Step 3b. Create a new user account or return an existing one.
        User.findOne({ linkedin: profile.id }, function(err, existingUser) {
          if (existingUser) {
            return res.send({ token: createJWT(existingUser) });
          }
          var user = new User();
          user.linkedin = profile.id;
          user.picture = profile.pictureUrl;
          user.displayName = profile.firstName + ' ' + profile.lastName;
          user.save(function() {
            var token = createJWT(user);
            res.send({ token: token });
          });
        });
```

Just add a few `console.log` inside each if-statement and trace it to where the problem is occuring. Also note that I am not handling any error handling there, so be sure to do `if (err) console.log(err);` as well.
