### ISSUE TITLE
Question: Using Twitter API (search, post, get etc)

### ISSUE THREAD

**Issue by LunarDevelopment** [sahat/satellizer#539]
Hello! 

I love this project, bravo, it's saved me a lot of time and hassle. 

I was wondering; I've set up a working Laravel/ Angular App to log users in and out of twitter, now could anyone recommend a library to actually interact with the twitter rest api as the logged in user? 

Searching tweets, posting and replying are the key calls I need, but I don't know if I should find an angular or a laravel library to do this and how well Satellizer plays with other libraries (most of which seem to have their own OAuth log in functions before being allowed to post) 

Any help will be GREATLY appreciated!

Lewis

**Comment by sahat** [comment]
@LunarDevelopment why not write your own endpoints for what you need to do with Twitter API? It would be a good learning exercise for you as well. 

Start by creating Laravel routes and controllers:
```
GET /search
POST /search
POST /tweet
POST /retweet
POST /follow/:id
etc...
```

Each of these routes will use an HTTP library like Guzzle to make OAuth-signed requests to Twitter API. Alternatively look at some of the existing Twitter PHP libraries: https://dev.twitter.com/overview/api/twitter-libraries

In any case, I believe you will need to pass at least these 3 pieces of information to make an API request: consumer_key, consumer_secret, oauth_token. The last one, oauth_token, is obtained after successful Twitter authorization (look at one of the server examples in the Satellizer repo), so you will need to store it somewhere for subsequent use of Twitter API.

**Comment by LunarDevelopment** [comment]
Thats really useful feedback, thanks, I've been eager to write my own end points so I'll go with that. 

If you don't mind kickstarting me, is my best option altering the AuthController in Laravel to store the tokens I need during the satelizer oauth log in process ? 

And presumably I'd better store these in the DB, since user session requires log in to the app however Satellizer's laravel example only needs to link an account once, therefor the 3 keys I need will always be valid? 

I hope that made sense.

**Comment by LunarDevelopment** [comment]
Thanks for your help! I've got my home made api working with guzzle and satelizer for the logged in user!
