### ISSUE TITLE
getting email data from facebook login

### ISSUE THREAD

**Issue by ersensen** [sahat/satellizer#540]
Hi,

I am unable to get the user email using facebook auth. 

At the back end in this step profile contains id and name fields.
// Step 2. Retrieve profile information about the current user.
    request.get({ url: graphApiUrl, qs: accessToken, json: true }, function(err, response, profile) {

Here is my frontend config;
    $authProvider.facebook({
       clientId: '20198098210',
       url: API_CONFIG.authUrl + 'facebook',
       scope: ['email'],
       scopeDelimiter: ',',
       requiredUrlParams: ['display', 'scope']       
    });    

I want to get email and other possible user info. How do we do this?

Is it related with the facebook app configuration?

Thanks

**Comment by mbecker** [comment]
Do you request the email via the 'graphApiUrl' in request.get()?

The URL must be: var graphApiUrl = 'https://graph.facebook.com/v2.3/me' + '?fields=email,name,id';

**Comment by ersensen** [comment]
Yeah I discovered the fields paramaters then after. Thanks.
