### ISSUE TITLE
How to show a loading / progress spinner for XHR request?

### ISSUE THREAD

**Issue by mbecker** [sahat/satellizer#542]
Hi,

is it possible to show that satellizer performs a XHR request to the local server to fetch the token?

I tried to use the following angular modules:
* http://tech.wonga.com/angular-http-loader/
* https://github.com/chieffancypants/angular-loading-bar

I wasn't able to configure it for satellizer. For "normal" XHR request the spinner is shown.

Does anyone know how to show a loading progress for the XHR requests from satellizer?

Thank you very much!

**Comment by LunarDevelopment** [comment]
Did you add the api route to your whitelist when using angular-http-loader? 

And if so, you say XHR request to "local" server, do you mean your local host or have you tried on remote server or only your localhost ?  if localhost you'll need to whitelist both:
* localhost
* 127.0.0.1

.config(['httpMethodInterceptorProvider',
  function (httpMethodInterceptorProvider) {
  httpMethodInterceptorProvider.whitelistDomain('127.0.0.1');
  httpMethodInterceptorProvider.whitelistDomain('localhost');
  // ...
 }
])

**Comment by mbecker** [comment]
Hi LunarDevelopment,

thank you for your answer. Unfortunately I had an error in my grunt file; the css-Files weren't copied. So my mistake. Both modules are working.

Can I delete this post due to my mistake? Thank you!

**Comment by LunarDevelopment** [comment]
Next to "Comment" under your reply box click comment and close - I'm not admin or contributor on this repo so I cant close this for you.
