### ISSUE TITLE
Bug: no options for signup

### ISSUE THREAD

**Issue by aal89** [sahat/satellizer#544]
According to the documentation for signup ($auth.signup(user, [options])) there should be an options parameter but there isn't one, making this function not work like it should. I fixed it locally by editing line 207 & 208 in satellizer.js:

`$auth.signup = function(user, opts) {
            return local.signup(user, opts);
          };`

**Comment by sahat** [comment]
Thanks for catching that mistake. It is fixed now.

```js
$auth.signup = function(user, options) {
     return local.signup(user, options);
};
```
