### ISSUE TITLE
process status 403 API RESTful

### ISSUE THREAD

**Issue by lucianoreis** [sahat/satellizer#545]
I am using a PHP REST API, and when it returns a 403 status saterllizer the 'kill' the session and directs you to login.
How do I configure a message without ending login?

**Comment by sahat** [comment]
@lucianoreis Could you be a little more descriptive? Why are you getting a 403 status message - invalid username/password, an error during OAuth flow? Is server redirecting user the login page or your Angular app? I am also not sure what did you mean by your last question: *How do I configure a message without ending login?*
