### ISSUE TITLE
question: can I have FB and twitter callbacks on client side?

### ISSUE THREAD

**Issue by boazin** [sahat/satellizer#546]
I know it is considered less secure - but can I somehow have a client side function do the login and get the token in order to get basic user info?
(specifically facebook and twitter)

**Comment by sahat** [comment]
Facebook yes, Twitter no. https://github.com/sahat/satellizer/issues/143

It's  not that it's less secure, but requires additional verification on the server-side if you are going to store that data in your database eventually. Say you do an implicit grant flow and obtain access token on the client-side. Sure, you can query Facebook API to get basic user info, but when you are going to do a POST request to your server with that data  how do you know if that is real user info or a malicious user forged the user information and it's not actually from Facebook.com. Just keep that in mind.

If all you need is Facebook and you only want to get basic user info on the client-side you may be better of with Facebook JavaScript SDK. Twitter uses OAuth 1.0 so it's not possible to do an entire flow on the client-side.

**Comment by boazin** [comment]
Yeah... That's why I said it is less secure. Well, my current API server doesn't have OAuth implementation, but I'm guessing I have no choice (it is an old PHP code I'm trying to get around, but I can have those endpoints in the server that servers the angular)

Thanks!
