### ISSUE TITLE
Shared.getPayload() & Shared.isAuthenticated() should call replace with RegEx and global flag

### ISSUE THREAD

**Issue by jskrzypek** [sahat/satellizer#551]
`Shared.getPayload()` & `Shared.isAuthenticated()` both do `replace()` on the the string of the token, to switch from http-safe characters to characters `window.atob()` is happy with (`'-' -> '+'` & `'_' -> '/'`). See them here: https://github.com/sahat/satellizer/blob/master/satellizer.js#L282 & https://github.com/sahat/satellizer/blob/master/satellizer.js#L325.

These methods work, but only if there is only one such character in the token. If there are more than one '-' or '_' `window.atob()` throws an error, since the second character hasn't been replaced.

Instead these methods should call `replace()` using the RegEx syntax with the global flag, as is used elsewhere in the library. This would look like this:
```js
base64Url.replace(/-/g, '+').replace(/_/g, '/');
```

**Comment by sahat** [comment]
@jskrzypek In which case do you have more than one such character inside a token string? I am curious because I have used this approach for almost a year and no one has reported this issue.

**Comment by jskrzypek** [comment]
It happens to us occasionally, though not every time. We're using [`jsonwebtoken`](https://github.com/auth0/node-jsonwebtoken) to build the tokens, and we're attaching some custom user information along with the profile data from each of the linked accounts, so it might be that our tokens are larger than most. 

When we do get a token that has more than one `_` or `-` most of the authorization still works, but these methods fail.

**Comment by jskrzypek** [comment]
Currently we have to put `try {...} catch () {...}` blocks around the `isAuthenticated()` method to make sure that we can return false if it has an error, since we can't actually check the `.exp` property. Of course this means that certain users simply can't authenticate, which is a big headache.
