### ISSUE TITLE
Trying Satellizer with passport js

### ISSUE THREAD

**Issue by lmouhib** [sahat/satellizer#560]
I was wondering if it is possible to use passport js with satellizer? instead of writing our own code in the back-end. Thanks

**Comment by lekaha** [comment]
Backend? or Frontend? If you really meant backend I guess you are looking for a library it is able to handle with authentication in backend. But actually it's a bit weird cause it should be depended on what the develop environment (programming language, database, ...) you are working on. In the other hand, you wanna use passportjs and satellizer both? I think nothing is impossible but they are responsible for the same thing (satellizer is inspired by passportjs). better for either one of them :)

**Comment by lmouhib** [comment]
What i meant is there a way to get the authorization token from satellizer and supply it to passport js in the backend, instead of implementing the steps for getting the access token for google, facebook or any other account!

**Comment by sahat** [comment]
I am not sure how you would do it, but it may be possible. 

Try pointing Satellizer's Facebook `redirectUri` to `'/auth/facebook/callback'`, then on your back-end:

```js
//app.get('/auth/facebook', passport.authenticate('facebook', { scope: ['email', 'user_location'] }));
app.get('/auth/facebook/callback', passport.authenticate('facebook'), function(req, res) {
  res.redirect(req.session.returnTo || '/');
});
```

I don't know if this will work, but give it a try. The main reason I did not want to use Passport from the very beginning is because I had to replicate the back-end logic across multiple languages and frameworks.

Play around with it, if you do figure it out, I will add a FAQ section on how to use Satellizer with Passport. You could use this as a reference: https://github.com/sahat/hackathon-starter/blob/master/config/passport.js

**Comment by lmouhib** [comment]
I did understand the purpose of satellizer. The reason i'm asking this, is just to see if i can cut down time on implementing the server side and use just passport to get the the access token, and use it to send to my web app.

The flow would be as follow:
 1. get the authorization token with satellizer
 2. send it to the backend 
 3. passport would get the authorization token and exchange it for an access token
 4. send the access token to the the web app to be used.

Thanks for your answer, I will further investigate how to combine both of them ig it is possible.

**Comment by lmouhib** [comment]
I went ahead and tried it, it just add a layer of hasle. Better just write your own code and customize it to what you want your backend to do. thanks man :) great work.

**Comment by danivek** [comment]
I think the best alternative to passport for server side auth working with satellizer is [authom](https://github.com/jed/authom).

**Comment by lmouhib** [comment]
It seems a good alternative, did you try it? Thanks buddy

**Comment by denisazevedo** [comment]
Hi @lmouhib, could you share your implementation? We may add it to the FAQ section like Sahat said.
Thanks

**Comment by clarle** [comment]
Hi all,

We've added information about Passport.js to the README.

As well, feel free to use [Hackathon Starter](https://github.com/sahat/hackathon-starter/blob/master/config/passport.js) as an example of how to use them together.

Let us know if you have any other questions!
