### ISSUE TITLE
No authorization header 

### ISSUE THREAD

**Issue by umasgn** [sahat/satellizer#566]
Hi, authorization header is not being sent after successful login. In local stoare token is saved

1. Local Storage token Img
2. req.headers.authorization object on server, Img
![token](https://cloud.githubusercontent.com/assets/12139440/9957080/f899beae-5e1a-11e5-855f-8fb140d95663.png)
![header](https://cloud.githubusercontent.com/assets/12139440/9957086/ff7a94b4-5e1a-11e5-8d53-3a10de62afac.png)

**Comment by ConstantineZarzhytskyy** [comment]
Hi, umasgn!

https://github.com/sahat/satellizer#configuration

**Comment by codeuniquely** [comment]
There used to be two properties

      $authProvider.authHeader = 'app-auth-header';
      $authProvider.authToken = '';


Into which properties (listed in the configuration above) have these now been moved
using 

    $authProvider.tokenHeader = 'app-auth-header';
    $authProvider.tokenName = '';

Just does not pass a request header with [app-auth-header] and so authentication does work.
Which properties should now be used ..
