### ISSUE TITLE
Satellizer vulnerable to XSS?

### ISSUE THREAD

**Issue by aarongray** [sahat/satellizer#567]
Very cool library. I have a question though. It looks like you are storing your tokens in localStorage or sessionStorage. Forgive me if I am wrong, but I thought these are vulnerable to XSS attacks and that the data in here can be viewed by scripts on the page - so if you have a compromised script served from a CDN or if there is malicious code in a JS library used alongside satellizer in a web app, they can steal the token out of those storage places and impersonate a user until the token expires.

See:
https://stormpath.com/blog/where-to-store-your-jwts-cookies-vs-html5-web-storage/
https://www.owasp.org/index.php/HTML5_Security_Cheat_Sheet#Local_Storage
https://blog.whitehatsec.com/web-storage-security/

I think the most secure approach is to store a JWT + CSRF token in a cookie, and then place your computed JWT with the CSRF token inside it in the request header, and validate based on the request header. (See first link above.)

Am I missing something?

**Comment by monderwa** [comment]
This is my understanding as well, but I'm no expert. Anybody else out there with thoughts on this?

**Comment by honkskillet** [comment]
This seems pretty critical.  First, I'd like to say that I am far from an expert on security issues.  I guess the question is how vulnerable is your site to XSS?  My (possibly flawed) understanding was that Angular is not very vulnerable to XSS in normal usage.

Moving to $cookies for storage would mitigate XSS(?), but (as @aarongray points out) introduces CSRF vulnerabilities which necessitates CSRF tokens and increased complexity on both client and server side.  In the angular docs for $http, it has this to say about CSRF (XSRF)... ( https://docs.angularjs.org/api/ng/service/$http )
>XSRF is a technique by which an unauthorized site can gain your user's private data. Angular provides a mechanism to counter XSRF. When performing XHR requests, the $http service reads a token from a cookie (by default, XSRF-TOKEN) and sets it as an HTTP header (X-XSRF-TOKEN). Since only JavaScript that runs on your domain could read the cookie, your server can be assured that the XHR came from JavaScript running on your domain. The header will not be set for cross-domain requests.

>To take advantage of this, your server needs to set a token in a JavaScript readable session cookie called XSRF-TOKEN on the first HTTP GET request. On subsequent XHR requests the server can verify that the cookie matches X-XSRF-TOKEN HTTP header, and therefore be sure that only JavaScript running on your domain could have sent the request. The token must be unique for each user and must be verifiable by the server (to prevent the JavaScript from making up its own tokens). We recommend that the token is a digest of your site's authentication cookie with a salt for added security.

>The name of the headers can be specified using the xsrfHeaderName and xsrfCookieName properties of either $httpProvider.defaults at config-time, $http.defaults at run-time, or the per-request config object.

Thoughts?

**Comment by monderwa** [comment]
After some more reading it does indeed seem that proper use of Angular should prevent XSS. I found this helpful: http://stackoverflow.com/a/28011263, and the Wikipedia page on XSS suggests the same (https://en.wikipedia.org/wiki/Cross-site_scripting).

**Comment by aarongray** [comment]
Thanks for the replies. I'm still not convinced though, and I don't think it addresses the problem of a compromised script from a CDN, third party service, or JS library in your app. From my links above, the Open Web Application Security Project, a respected security company, and Stormpath (a company that has built their entire business around web authentication, and largely Angular in particular) all say that you should not store anything of value or trust (including JWT's) in localStorage or sessionStorage.

**Comment by aarongray** [comment]
Interestingly, it looks like modern browsers are starting to address the issue of compromised scripts from CDN's by using an `integrity` attribute on the script tag. This would solve the problem from a different direction.
https://hacks.mozilla.org/2015/09/subresource-integrity-in-firefox-43/

**Comment by sahat** [comment]
Appologies for joining the conversation so late, but @aarongray you are right, it does introduce the possibility of XSS when storing JWT in Local Storage.

[10 Things You Should Know about Tokens](https://auth0.com/blog/2014/01/27/ten-things-you-should-know-about-tokens-and-cookies/) says that it is easier to deal with XSS than CSRF and the only reasonable solution is to keep token expiration time low.

Also, as a rule of thumb, you shouldn't be storing any sensitive information in JWT, in its unecrypted form, inside the Local Storage. I did read something about Encrypted JWT last year, however, I don't know much about it.

And thanks for pointing out the `integrity` attribute; didn't know about it.

**Comment by aarongray** [comment]
:+1:

**Comment by pavankumarkatakam** [comment]
So, finally whats the conclusion?

**Comment by pavankumarkatakam** [comment]
Storing the JWT token in the localstorage and protect from XSS by keeping the expiration time low.

**Comment by pavankumarkatakam** [comment]
Hi guys, this thread has so many thoughts, but whats the final conclusion. Hi @aarongray , yes `integrity` can be very helpfull in future but for now the site should use own javascript files rather than an CDN it should do the trick.but im scared that is there a way for the chrome plugin to XSS to the site.

**Comment by marciocamello** [comment]
localStorage.setItem('satellizer_token', 'token');

**Comment by pavankumarkatakam** [comment]
What @marciocamello .
