### ISSUE TITLE
Token not being saved to local storage on other clients

### ISSUE THREAD

**Issue by xrockwell** [sahat/satellizer#568]
There's this strange behavior that occurs in an app I've been developing:
In most clients/browsers/computers that I've used in a network for testing, the authentication works and I can login successfully, while in some, (about 2 in 7) the authentication fails.

I've tried to discern where the differences lie in the said clients, and have found the following:
1. The API I'm using to return a token works. (tested in Postman), and that in all clients and all kinds of browsers, the request returns a token on successful authentication in the server,
2. I could set items in the local storage just fine, using localStorage.setItem(); again, regardless of the browser used,
3. The satellizer_token does not set automatically on the aforementioned some clients. Setting it manually via console works but the item is lost on page load.

I'm using something that goes like the following:
````javascript
$scope.signin = function () {
 if(login.isValidated){
  $auth.login(credentials).then(function() {

     return $http.get('api/authenticate/user');
     }, function(error) {
     $scope.loginError = true;
     $scope.loginErrorText = error.data.error;
     ngToast.danger({content: 'The server returned the following error <br/>'+$scope.loginErrorText});
     $scope.validation.username = "has-error";
     $scope.validation.password = "has-error";
     return $q.reject($scope.loginErrorText);

   }).then(function(response) {

       var user = JSON.stringify(response.data.user);
       localStorage.setItem('user', user);
       $rootScope.authenticated = true;
       $rootScope.currentUser = response.data.user;
       $scope.validation.username = "";
       $scope.validation.password = "";
       //rest of the code
  });
 }else
 {
  //validation code
 }
}
````

with just a
````javascript
$authProvider.loginUrl = 'sis/public/api/authenticate';
````
in my config block.
Your help will be much appreciated. I've been stuck in this one for a day almost ;_;

EDIT:
Yep, it's consistent, it never works on some computers/clients while others do just fine.

Tested in the latest Chrome and Opera update/release. Forgot to check the Firefox one.
I'm using Satellizer 0.12.2 and AngularJS v1.3.13.

**Comment by xrockwell** [comment]
Decided to code my own implementation and now it's working on all clients as expected.

**Comment by ddw147** [comment]
@xrockwell how did you solved this issue 
i am facing same problem in my app

**Comment by prime-ralph** [comment]
I decided to stop using Satellizer altogether, and came up with my own, less-featured implementation.

**Comment by pavankumarkatakam** [comment]
Hi @ddw147 , im also facing same issue. is there any solution let me know.

**Comment by shonatodc** [comment]
Not sure what version you're using but "setStorageType" seems to be working just fine for me in version 0.14.0, http://screencast.com/t/PC7kSClEEh.

e.g. $scope.login=function(asdf){$auth.setStorageType('localStorage');}

Also, if you're using "access_token" as the name, you'll need to add the code below to your app.
yourapp.config(function ($authProvider) {
    $authProvider.tokenPrefix = '';
    $authProvider.tokenName = 'access_token';
});
