### ISSUE TITLE
LinkedIn Auth.

### ISSUE THREAD

**Issue by fnbns** [sahat/satellizer#57]
Hello,

Can you please help me with this problem : i'm trying to set-up linkedin auth and i get this message : 
Invalid redirect_uri. This value must match a URL registered with the API Key.

From the configs i've seen that the redirect uri is windows.location.origin, but i guess linkedin is asking me for a real api like http://localhost:3000 (i'm using node).
My question is how should i get this going?:D

Thanks,
Alex

**Comment by aditigoel** [comment]
Hi , 
I am also getting same error . And follow steps suggested by you after doing this when i click on login with linkedin button pop-up open and disappers in a second and not showing any error in console.
My redirect uri is http:localhost:8080

For reference please find the attachment. 
In attacment pop-up open and disappers in sec
![linke](https://cloud.githubusercontent.com/assets/10771021/5974403/100bf534-a89a-11e4-8731-806967c3f5b5.png)
