### ISSUE TITLE
Problem with Ionic App

### ISSUE THREAD

**Issue by sariyu** [sahat/satellizer#572]
Hi @sahat, when i try to use satellizer with ionic app i'm getting an error. same code working fine with angularjs web application. redirecturi , i used in ionic is 'http://localhost' but i came to know that window.location.origin for ionic app is 'file://' it should return the response back to location.origin to work properly. Any IDEA on it ? Otherwise is it possible to modify the location.origin value , so that we can fix this issue ?

**Comment by sahat** [comment]
@sariyu I haven't used Ionic much, or Cordova, but I can take a look into this issue tonight and provide my feedback if I have any.

**Comment by pietrovismara** [comment]
I don't know for ionic, but have you tried with `window.location.protocol + '//' + window.location.host` ?

**Comment by rrNuvoPoint** [comment]
Did you remember to put: $authProvider.cordova = true;

**Comment by iagoleao** [comment]
@sahat I have the same problem
