### ISSUE TITLE
Suggestion: Add Avatar fetching examples for services

### ISSUE THREAD

**Issue by varmint09** [sahat/satellizer#576]
Hi,

Would be keen to get the Twitter/Facebook avatars when people sign up too, would this be possible to add to the code/documentation at all?

Thanks

**Comment by sahat** [comment]
@varmint09 You are not talking about this profile avatar which is already in the server example?
<img width="384" alt="screenshot 2015-09-27 13 44 53" src="https://cloud.githubusercontent.com/assets/544954/10125116/f44649d0-651d-11e5-9579-ac5b9a245610.png">
