### ISSUE TITLE
login stalls under IE

### ISSUE THREAD

**Issue by timbell** [sahat/satellizer#582]
Under IE the popup isn't closed and the login stalls. This happens when the provider requires input (choose email and/or enter password). If the provider already has the credentials and the redirect happens without user input then the popup closes fine and login completes successfully.

NB I only reproduce this behaviour if using a non-admin account. Using an admin account and/or running with elevated privileges (run as admistrator) then the login is fine.

The problem occurs in pollPopup. When the redirect back to the app's url has completed it still can't access Popup.popupWindow.location.host even though there shouldn't be a cross-domain issue. Then, Popup.popupWindow.closed returns true and so we stop polling and the popup remains open.

I've tested with IE 9 and 11 on three different machines and get consistent results.

**Comment by timbell** [comment]
Just revisited this. I was using google as the provider in my tests. I just tried with windows live and couldn't reproduce the issue. I finally realised that although I have *.google.com and *.google.co.uk in my trusted sites I didn't have *.youtube.com. Adding this makes the problem go away. Seems obvious now...

**Comment by clarle** [comment]
Hi @timbell,

Thanks for the information, and glad you were able to solve the problem!

Let us know if there's anything else that we can help with.
