### ISSUE TITLE
Use with $resource?!

### ISSUE THREAD

**Issue by lmouhib** [sahat/satellizer#585]
I was wondering if satellizer work when using $resource to make api calls? Does it still intersept the http call and add in the header the token or not  -knowing that $resource would probably use the $http, since i believe it just add a level of abstraction over $http-. thanks

**Comment by matthiasg** [comment]
we use it successfully with $resource yes. i could not get it to run with https://github.com/TalAter/UpUp yet because the serviceworker doesnt seem to retain the token, but thats another issue

**Comment by lmouhib** [comment]
thanks
