### ISSUE TITLE
Roadmap to v1.0

### ISSUE THREAD

**Issue by honkskillet** [sahat/satellizer#593]
Awesome work on this package to date.

What is the Roadmap to this package being considered v1.0?

**Comment by sahat** [comment]
Thank you. I have started the `1.0` milestone on GitHub. It will mainly consist of bug fixes and maybe a few small features.

From Semver:

##### How should I deal with revisions in the 0.y.z initial development phase?

The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

##### How do I know when to release 1.0.0?

If your software is being used in production, it should probably already be 1.0.0. If you have a stable API on which users have come to depend, you should be 1.0.0. If you're worrying a lot about backwards compatibility, you should probably already be 1.0.0.
