### ISSUE TITLE
The server responded with a status of 500 (Internal Server Error)

### ISSUE THREAD

**Issue by thari911** [sahat/satellizer#594]
Hey. I setup everything as mentioned and i'm trying to login with one of the social logins. But i'm getting a server error (500). Please advice me on how to overcome this and get it to work.

Thank you.

**Comment by elmeister** [comment]
Check server's log for the reason of 500 error.

**Comment by thari911** [comment]
I'm using a local host. Is it possible to check the server log?

Regards,

Tharindu Gamage

**Comment by elmeister** [comment]
Check social application keys and access token settings. Callback URL must be set correctly. What social network responds with 500 server error?

**Comment by thari911** [comment]
All of them. Facebook, Google + LinkedIn. All of them returning server
error 500. I have changed the application keys and created new ones and
used them. That's how I got the signing into work. Before It said redirect
url error. But after changing the application keys and signing in its
giving me the server error.

Regards,

Tharindu Gamage

**Comment by sahat** [comment]
Resolved via email conversation.

**Comment by andjosaquino** [comment]
@sahat Hi! I am getting the same error, do you mind sharing what the solution you and @thari911 found?

**Comment by zinzinzan** [comment]
i am getting the same issue, do you mind share the solution please???

**Comment by sahat** [comment]
OP's issue was that he did not add "Website" platform with a valid Site URL after creating a Facebook app.
