### ISSUE TITLE
iOS 9 Chrome doesn't close popup (Facebook)

### ISSUE THREAD

**Issue by calvinlyc** [sahat/satellizer#597]
Hi, we are using 0.12.5 version of the satellizer and under iOS 9 Chrome doesn't close the Facebook popup. The chrome version is 45.0.2454.89 which is the laest version. This functionality does work properly under iOS 9 Safari.

This issue can be reproduced by Facebook button on Satellizer Demo Project (https://satellizer.herokuapp.com/#/login) under iOS 9 Chrome  45.0.2454.89

Anybody has any idea how to fix this issue? Thanks for your help.

**Comment by ootterskog** [comment]
This has been working previously. Has Facebook changed anything?

**Comment by calvinlyc** [comment]
I personally don't think Facebook changed anything. Most likely the latest version of Chrome caused this issue.

**Comment by calvinlyc** [comment]
I think the problem is around line 643 var windowName = config.cordova ? '_blank' : name;
Since I didn't flag the cordova to be true, therefore in Chrome iOS9 it failed since open window needs to be _blank.

**Comment by calvinlyc** [comment]
Please feel free to close this ticket since I know where causes the issue, I am able to workaround it locally and will wait for future release to fix this issue properly. Thanks for your help.

**Comment by guilhermecvm** [comment]
Ain't a problem with facebook, I'm facing the same issue with instagram.
Setting ```$authProvider.cordova = true;``` didn't make chrome closing the tab. But setting ```windowName = config.cordova ? '_blank' : name;``` to ```windowName = '_blank';``` did it, although something is still not working since user didn't logged in on my application. I can't check the logs cause there is no chrome debugging on the iphone :(

**Comment by elhamsarikhani** [comment]
I am facing the same issue. on iOS. 
The window.open and authentication works on Android though.

**Comment by guilhermecvm** [comment]
Did anyone found a solution for this?

**Comment by hendricius** [comment]
Also looking for a fix for this one.

It works for me for all browsers, except when I add the app to the homescreen using mobile Safari. Then the popup window is not being closed properly.

**Comment by sahat** [comment]
Fixed in 0.13.

**Comment by guilhermecvm** [comment]
Thanks a lot :)
