### ISSUE TITLE
POST http://localhost:55591/auth/facebook 404 (Not Found)

### ISSUE THREAD

**Issue by amitsinha559** [sahat/satellizer#598]
getting this error

POST http://localhost:55591/auth/facebook 404 (Not Found)

What can I do ?

**Comment by Chakrakin** [comment]
guess you need a server that handles the authentication process

examples can be looked here: https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js

**Comment by fordg** [comment]
@Chakrakin How to use its ?

**Comment by sahat** [comment]
Duplicate of #632.

**Comment by sahat** [comment]
Are README instructions really that unhelpful that people just skip over server-side examples and just assume authorization will magically work on client-side only?
