### ISSUE TITLE
unclear step in the OAuth 1.0 flow

### ISSUE THREAD

**Issue by swimclan** [sahat/satellizer#601]
What does step 4 in this checklist mean?

https://github.com/sahat/satellizer/wiki/Login-with-OAuth-1.0

Anytime i respond with JSON with `request_token` as the key I get nothing/error in the Twitter popup.

**Comment by sahat** [comment]
I have updated that wiki page. Unlike with OAuth 2.0 you can't go to permissions authorization screen right away, you need that request token. You can only get it on the server. Once server obtains that request token, you send it to the client, at that point Satellizer can show authorization screen inside the popup.

https://github.com/sahat/satellizer/wiki/Authentication-Flow

<img width="1359" alt="screenshot 2015-10-14 22 30 52" src="https://cloud.githubusercontent.com/assets/544954/10503367/3f7c7b2e-72c3-11e5-8521-2307898eed36.png">
