### ISSUE TITLE
Questions on customization

### ISSUE THREAD

**Issue by elhamsarikhani** [sahat/satellizer#605]
Hi,
I tried to add new provider but I'm having these questions:
- How can I add new parameter that is needed for authorization request?
- If I set the responseType to  'token', I get the token as well as expiration time for token and the url for Authentication request is different from Token request but in satellizer there is no settings for this scenario right?
- at which point we set and use client-secret?

**Comment by sahat** [comment]
##### 1. Either via `requiredUrlParams` or `optionalUrlParams`.

For example you want to add a new authorization param called `hd`. In your oauth2 method:
```js
$authProvider.oauth2({
      requiredUrlParams: ['hd'],
      hd: "some value"
});
```

##### Yes I don't remember the exact details with implicit oauth grant, but it does grant you an access token and something like refresh token and expiration time. Satellizer doesn't handle any of the token refresh logic yet, for implicit `(responseType: token)` or explicit `(responseType: code)` grant. This flow wasn't originally supported, but I added it per user's request. It's there if you want to do use implicit grant for whatever reason, but beyond that it's up to you to send it over to the server, verify it, and save the user to database (if needed).

###### You use client secret for explicit grant, and you store it on the server. With implicit grant you use it to verify the validity of the token and user data that you send from client-side. If you are building a pure client-side app using Facebook API, without any back-end, then you don't even need a client-secret.

**Comment by elhamsarikhani** [comment]
Thanks!
