### ISSUE TITLE
Auth with Facebook sdk 2.5 has issues

### ISSUE THREAD

**Issue by neoeahit** [sahat/satellizer#606]
Hello could you please help me resolve this?

Error:

Given URL is not permitted by the Application configuration: One or more of the given URLs is not permitted by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by sahat** [comment]
You have to add the Site URL from App settings to match the same URL where you are running your AngularJS app.

![sshot-2](https://cloud.githubusercontent.com/assets/544954/10840829/c2247a5c-7eb9-11e5-90c8-733b9507363c.png)
