### ISSUE TITLE
Satellizer not sending Authorization token

### ISSUE THREAD

**Issue by TheSachin** [sahat/satellizer#613]
Angular  : 1.4.7
satellizer : ~0.12.5
After Login, I can see the local storage having satellizer token , but unfortunately when sending http requests, Authorization token is not sent.
Though It doesnt work only for a specific directive. Now this directive is basically Select2 ajax call. Now If I manually insert token then it works. 
So I know the workaround, but I am not sure why SatellizerInterceptor didn't work.

**Comment by sahat** [comment]
My guess is, (and I could be wrong), Satellizer's interceptor gets overridden somehow, possibly by Select2. I can't say for sure without further debugging and investigation of this particular issue.

If manual approach works for you then use that. Satellizer's interceptor is more there for convenience. You can even disable it completely:
`$authProvider.httpInterceptor = false`.
