### ISSUE TITLE
Facebook sdk 2.5 not working properly its not returning email and friends but when i use same code its working with facebook sdk 2.4v.

### ISSUE THREAD

**Issue by bharathpendru** [sahat/satellizer#617]
The below code returning all fileds with facebook sdk 2.4 but when i use v2.5 its returning first 3 fields only (id, name, gender). I need all the fields with facebook sdk2.5

FB.api('/me', 'get', { fields: 'id,name,gender,friends,email' }, function (response) {}

Help me ASAP

**Comment by varmint09** [comment]
I'm sorry but that's just beyond lazy, it returns three fields because you are asking for three.

Read the documentation and ask for the fields you require, the API was updated by Facebook to avoid such wastage.

**Comment by bharathpendru** [comment]
Hi Varmint09, thanks for your reply. 
Instead of 5 fields if i want one field email also its  not working. i tried like below
"FB.api('/me', 'get', { fields: 'email' }, function (response) {}"
Its not returning email in sdk 2.5

**Comment by sahat** [comment]
If you are using the Facebook SDK, I can't help you there. You should ask that question on Facebook API/SDK forums, IRC, GitHub.

I demonstrated how to obtain an email with Graph API 2.5 in #615.
