### ISSUE TITLE
isAuthenticated() problem and unlink function

### ISSUE THREAD

**Issue by physio** [sahat/satellizer#621]
Good morning, sorry for my orrible english. I don't know if this is a issue or not, i hope I hope to be in the right place for this alert.

I'm trying to use Satellizer starting from the example, using client code for the client side and PHP code for the server.
I just added the module courses on the server side 'cause I started the server laravel with "php artisan serves" that listens on port 8000 and the client side with "grunt serves" that is listening on port 9000.

I created a facebook application developer and I tried to use the code of Satellizer. I created a new user connecting through Facebook and even creating it through the registration form.

the user is created in the database correctly and releases the token (in resources I find the key "satellier_token") and I am sent back to the "/".

The strange thing is that isAuthenticated () is always null, even if the function loginRequired working properly.

Another strange thing is that if I try to disconnect the user from the client connects to the facebook page "http://localhost:8000/auth/unlink/" instead of "http://localhost:8000/auth/unlink/facebook" as it should be.
The same thing happens in the demo "https://satellizer.herokuapp.com/#/profile"

**Comment by sahat** [comment]
I am not sure why isAuthenticated does not return true for you. Works fine here as you can see.

![sshot-1](https://cloud.githubusercontent.com/assets/544954/10839425/3312208a-7eaa-11e5-8c4d-cb2101d1c2e1.png)

As for your second point, thanks for bringing it to my attention. I need to update `unlinkUrl` settings in the example code.

**Comment by sahat** [comment]
Account unlinking should work correctly on Heroku now. Also I may have found the reason why isAuthenticated was returning false for you. Could be unrelated, but I had set 5 second timeout on JWT expiration in server.js (Node.js example which is also on Heroku), so it would kick you out as soon as you logged in. If you were using the PHP example then it shouldn't matter.

Close this issue if that answers your question.
