### ISSUE TITLE
Not able to setup the code on my local machine

### ISSUE THREAD

**Issue by nagbhushan** [sahat/satellizer#624]
Dear Sahat,
I tried all the possible ways of setting this up, but no success. Not sure what the issue is.
I want to know the exact step by step process of setting this up, which is not explained right now on Github.

I also want to set this up on my shared server. I want to get rid of that server.php file. i don't want to use this command php artisan serv command to run my server.

Please help me to set this up as easily as possible.

It doesn't go beyond below code for now.

$kernel = $app->make('Illuminate\Contracts\Http\Kernel');

$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
);

**Comment by nagbhushan** [comment]
I think its a issue of PHP version. Can i know what should be the exact PHP version for this work??

**Comment by sahat** [comment]
You haven't provided the error you are seeing. How can I possibly know why you cannot start the PHP example?

I have outlined step by step Getting Started steps here:
https://github.com/sahat/satellizer/tree/master/examples/server/php

Beyond that, like setting up a Laravel app on your server you should look into Laravel deployment documentation instead of asking here.

**Comment by nagbhushan** [comment]
Hi,

I am getting below error..
TokenMismatchException in VerifyCsrfToken.php line 46:

It requires a token to be sent when using the POST method, not sure if that is set when when i sign in using facebook, gmail etc.

**Comment by sahat** [comment]
Have you looked at #399?

**Comment by sahat** [comment]
I am going to comment out that middleware so that people stop creating issues about it. It can be a big pain if you just want to check out the Satellizer example.

**Comment by nagbhushan** [comment]
Hey Sahat,

Yes that did the trick. thank you very much. I think you are right, you can comment out that line and can leave it to the user to use the CSRF token for the POST requests.

I really appreciate your help.

**Comment by sahat** [comment]
:+1:
