### ISSUE TITLE
login popup not show if chome browser install Adblock Plus

### ISSUE THREAD

**Issue by truonghoangnguyen** [sahat/satellizer#625]
Login popup not show if  browser (chome) install Adblock Plus

1. chrome browser install Adblock Plus extension
2. run satellizer app from real-host (not local)
3. click login
4. new tab show, expected : popup window -> Cannot login

**Comment by sahat** [comment]
Not sure if it is Adblock Plus related, but I don't have any issues like that with uBlock Origin extension.

**Comment by truonghoangnguyen** [comment]
sorry for my mistake
extension is : `SBRO Safe Browsing`
url https://chrome.google.com/webstore/detail/sbro-safe-browsing/nlmaeipddicgfdbdfhffnocgohodcaig

**Comment by sahat** [comment]
Ok I am closing this issue since this looks like a problem with Chrome extension designed for blocking all popups, not just ads.
