### ISSUE TITLE
Don't throw the errror "Expected a token named 'token'" on 403

### ISSUE THREAD

**Issue by johannesjo** [sahat/satellizer#626]
That would be nice. I'm using 403 to respond to user which has correct credentials, but not yet activated his account by providing a confirmation token.

**Comment by tymondesigns** [comment]
this will be resolved when the next version drops, as it will just warn on the console instead https://github.com/sahat/satellizer/blob/master/satellizer.js#L325

**Comment by johannesjo** [comment]
Thank you very much. Thats good to know.

**Comment by sahat** [comment]
Fixed in 0.13.
