### ISSUE TITLE
token changed event

### ISSUE THREAD

**Issue by ersensen** [sahat/satellizer#627]
Hi,

Is would be excellent to broadcast an event from $auth service when the token is set, changed or removed in the localstorage?

Generally once a user is logged in, his information should probably be displayed somewhere (e.g. in the top-right corner). And generally a label is bound to a varible in the $rootScope or at a scope which is at least somewhere high up in the DOM tree. Also when the user logs out we again need to set this variable. Another case is when the app is bootstrapped and the token exists in the local storage.

We could use the event like this;

$rootScope.$on($auth.TOKEN_CHANGED, function(event, token){
	if(!token)
		$rootScope.currenctUser = null;
	else
		$rootScope.currenctUser = $auth.getPayload().getUserInfoFromPayload;
});

**Comment by sahat** [comment]
See https://github.com/sahat/satellizer/issues/152 and https://github.com/sahat/satellizer/issues/202.

You can do all that yourself at the app level instead of having Satellizer pollute global `$rootScope` with events.
