### ISSUE TITLE
Twitter authentication popup opens but blank!

### ISSUE THREAD

**Issue by tariquewaseem** [sahat/satellizer#633]
When I click on "Sign in with Twitter", it opens blank popup window.
Application Url: http://www.onlinessa.com/ms/#/login

Please help me as it is very urgent.

Note: I am working with only Client folder code not Server and Ionic folder.
 
![image](https://cloud.githubusercontent.com/assets/15666684/10962547/180e288c-83bf-11e5-8ca4-dfd44178b185.png)

**Comment by sahat** [comment]
Hey @tariquewaseem,

1. Saying "please help me, it's urgent" doesn't automatically oblige me to drop everything I am doing and help you with this issue.
2. Have you looked at the README?
3. Have you looked at the demo on Heroku?
4. If you have read the README, you would know that you need to have a server app running.
5. Have you updated it to use your Twitter consumer key and consumer secret?
6. Did you look at the Wiki to learn more about OAuth 1.0 (Twitter sign-in) flow?
