### ISSUE TITLE
Facebook login window cancel button promise

### ISSUE THREAD

**Issue by calvinlyc** [sahat/satellizer#636]
Hi, I think the latest satellizer plugin does not support cancel button callback on Facebook login window at the moment.

I had a look the code and realized around line ```707```

There is a if/else statement around deferred.resolve which prevent error be passed back to controller.
```
if (!qs.error) {
     deferred.resolve(qs);
}
```
By removing the if/else statement here, I am able to handle the error actions (such as cancel button click)   in my controller, just wonder is there any reasons here to only resolve the positive promise?  

Kind regards

**Comment by sahat** [comment]
That's a good point. I will look into adding a `deferred.reject()` to bubble up an error so that users can handle it however they see fit.

**Comment by sahat** [comment]
#635

**Comment by sahat** [comment]
@calvinlyc So you basically want this response in your controller's promise?
```js
Object {error: "access_denied", error_code: "200", error_description: "Permissions+error", error_reason: "user_denied", _: "_"}
```

**Comment by calvinlyc** [comment]
@sahat  Yes, this is what we need :) Thanks

**Comment by sahat** [comment]
Check the code on master branch. It will now return a deferred.reject() with error object when a user hits a cancel button.

**Comment by calvinlyc** [comment]
Thanks. :)
