### ISSUE TITLE
On satellizer logout, logout from respective service provider ?

### ISSUE THREAD

**Issue by nagappan** [sahat/satellizer#637]
Hello, On logging out from satellizer session, how do I logout from the service provider like (google/yahoo) on client side ? I could not find any useful info on my Google search, so created this issue. Thanks

**Comment by sahat** [comment]
@nagappan This feature is unsupported. First, not all OAuth providers may have a concept of log out, e.g. a service that only grants permissions. Second, each "social" provider like Facebook, Google, GitHub have their own way of signing out. To account for each and every provider would be quite difficult.

If these mentioned providers (google, facebook, yahoo) do provide you a log out url, then your best bet would be to do your own $http request:
```
$auth.logout()
  .then(function() {
    // do $http.post() here to log out from oauth provider
  });
```

**Comment by nagappan** [comment]
This could be security breach, if someone logs in a shared computer, assuming that, if they logout from the website this method is used, they will be logged out from Google account as well for example.

I could not find logout for Yahoo / Google through OAuth, the respective website developer doc also doesn't talk about this, strange !
