### ISSUE TITLE
Redirect instead of Popup

### ISSUE THREAD

**Issue by maciossek** [sahat/satellizer#638]
I would like to choose whether to use a popup or go the "long way" with a redirect. Is this possible? I could not find any info regarding the display property.

**Comment by sahat** [comment]
Popup is the only option that's available. Doing page redirect (not sure why you would want to in a single page app) would involve re-writing a lot of parts of Satellizer.

**Comment by metal3d** [comment]
Could anybody tell me why there is a "display" option set to "popup" so ? Thanks :)
