### ISSUE TITLE
Facebook login doesn't return correct scope

### ISSUE THREAD

**Issue by rajanshah** [sahat/satellizer#640]
satellizer.js

    providers: {
        facebook: {
          name: 'facebook',
          url: '/auth/facebook/',
          authorizationEndpoint: 'https://www.facebook.com/v2.3/dialog/oauth',
          redirectUri: (window.location.origin || window.location.protocol + '//' + window.location.host) + '/',
          requiredUrlParams: ['display', 'scope'],
          scope: ['email', 'public_profile', 'user_friends'],
          scopeDelimiter: ',',
          display: 'popup',
          type: '2.0',
          popupOptions: { width: 580, height: 400 }
    },

Facebook graph api access (via python facebook api - facebook-sdk)

FACEBOOK_ACCESS_TOKEN_URL='https://graph.facebook.com/v2.3/oauth/access_token'
FACEBOOK_GRAPH_API_URL='https://graph.facebook.com/v2.3/me'

    def facebook():
          ''' facebook login '''

          access_token_url = app.config.get('FACEBOOK_ACCESS_TOKEN_URL')
          graph_api_url = app.config.get('FACEBOOK_GRAPH_API_URL')

          payload = json.loads(request.data)
          params = {
                'client_id': payload['clientId'],
                'redirect_uri': payload['redirectUri'],
                'client_secret': app.config.get('FACEBOOK_SECRET'),
                'code': payload['code']
         }

        # Step 1. Exchange authorization code for access token.
        res = requests.get(access_token_url, params=params)
        access_token = json.loads(res.text)['access_token']

        # Step 2. Retrieve information about the current user.
        res = requests.get(graph_api_url, params={'access_token':access_token})
        profile = json.loads(res.text)

        # Step 3. Get all friends ids
        graph = fb.GraphAPI(access_token)
        friends = graph.get_connections(id=profile['id'], connection_name='friends')

The above code correctly returns user profile, however when requesting friends it generates following results.

friends
    {'data': [], 'summary': {'total_count': 38}}

I would appreciate any insight into the reason behind such behavior.

**Comment by omegatiger** [comment]
Hi Rajanshah,

Please, read this https://developers.facebook.com/docs/graph-api/reference/v2.5/user/friends

<i>
A user access token with user_friends permission is required to view the current person's friends.

<b><i>This will only return any friends who have used (via Facebook Login) the app making the request</i></b>

If a friend of the person declines the user_friends permission, that friend will not show up in the friend list for this person.
</i>

**Comment by rajanshah** [comment]
Hi,

Thanks for the reply.

Yes, after user accesses the application friend does show up. I am interested in receiving friend's email though. Even though, friend's email is public it doesn't show up.

Is there a separate scope required for accessing email?

With best,
Rajan

**Comment by neslinesli93** [comment]
+1, same problem here

**Comment by sahat** [comment]
Closing as a non-Satellizer issue. 
For Facebook API specifics please refer to their documentation as well as this awesome tool [Graph API Explorer](https://developers.facebook.com/tools/explorer).

I should also note that as of Facebook API 2.4 and 2.5 you now have to explicitly pass fields that you want returned in your Python API call, for example:
```
?fields=id,name
```
