### ISSUE TITLE
satelizer - google+ login and retrieve all members in circle

### ISSUE THREAD

**Issue by rajanshah** [sahat/satellizer#641]
Hi,

I am interested in retrieving all members in google circle via satellizer.

scope:

    google: {
          name: 'google',
          url: '/v1/intellimind/auth/google/',
          authorizationEndpoint: 'https://accounts.google.com/o/oauth2/auth',
          redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host,
          requiredUrlParams: ['scope'],
          optionalUrlParams: ['display'],
          scope: ['profile', 'email'],
          scopePrefix: 'openid',
          scopeDelimiter: ' ',
          display: 'popup',
          type: '2.0',
          popupOptions: { width: 452, height: 633 }
    },

The following code works and it successfully performs login, however at step #3, it generates
401 error. I also tried adding scopes such as plus.me, however it doesn't allow such scope.

          def google():
                ''' google login '''

               access_token_url = app.config.get('GOOGLE_ACCESS_TOKEN_URL')
               people_api_url = app.config.get('GOOGLE_PEOPLE_API_URL')

              request_json = json.loads(request.data)
              payload = dict(client_id=request_json['clientId'],
              redirect_uri=request_json['redirectUri'],
              client_secret=app.config.get('GOOGLE_CLIENT_SECRET'),
              code=request_json['code'],
              grant_type='authorization_code')

              # Step 1. Exchange authorization code for access token.
              res = requests.post(access_token_url, data=payload)
              resp_json = json.loads(res.text)
              headers = {'Authorization': 'Bearer {0}'.format(resp_json['access_token'])}

              # Step 2. Retrieve information about the current user.
              res = requests.get(people_api_url, headers=headers)
              profile = json.loads(res.text)

              # Step 3. Retrieve friends
             response = requests.get(
                  'https://www.googleapis.com/plus/v1/people/me/people/visible',\
                  params={'access_token': resp_json['access_token']}
             )
             friends = response.json()['items']

I would appreciate, if someone can provide insight into what's the best way to retrieve friends from google+ circle.

**Comment by clarle** [comment]
Hi @rajanshah,

Fetching friend information from Google+ is beyond the scope of what Satellizer does - we focus on doing only login well.

The [Google+ documentation](https://developers.google.com/+/web/api/rest/latest/people/list) on fetching people from a specific list or circle should have more information on what you're trying to do.

Let us know if you have any other information, or if we can help out in any other way!
