### ISSUE TITLE
Instagram Platform update

### ISSUE THREAD

**Issue by kukac7** [sahat/satellizer#648]
> Instagram Platform and documentation update. Apps created on or after Nov 17, 2015 will start in Sandbox Mode and function on newly updated API rate-limits and behaviors. Prior to going Live, and being able to be used by people other than the developers of the app, these apps will have to go through a new review process. Please read the [API documentation](http://instagram.com/developer/) or the [Change Log](http://instagram.com/developer/changelog/) for more details.

> Any app created before Nov 17, 2015 will continue to function until June 2016. After June 2016, the app will automatically be moved to Sandbox Mode if it wasn't approved through the review process. The previous version of our documentation is stil available [here](http://instagram.com/developer/deprecated/).

just sayin' :wink:

**Comment by sahat** [comment]
Thanks for the update.
