### ISSUE TITLE
Paypal integration

### ISSUE THREAD

**Issue by LetsDoIt-** [sahat/satellizer#649]
I saw in one issue that Paypal is not supported, is that still true?

**Comment by sahat** [comment]
PayPal documentation is a lot better than last time I checked. Should be possible to do it.

https://developer.paypal.com/docs/api/#grant-token-from-authorization-code

If you want to give it a shot, try implementing a custom oauth2 provider similar to how I implemented Foursquare OAuth:

```js
 $authProvider.oauth2({
      name: 'foursquare',
      url: '/auth/foursquare',
      clientId: 'MTCEJ3NGW2PNNB31WOSBFDSAD4MTHYVAZ1UKIULXZ2CVFC2K',
      redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host,
      authorizationEndpoint: 'https://foursquare.com/oauth2/authenticate'
    });
```

Then write a back-end piece for it, again, similar to how many other providers are written. They all have pretty much the same steps, except Twitter ( OAuth 1.0).

If you manage to do that, I would love a pull request for it.

**Comment by franbueno** [comment]
Any update... :(

I will work on it and update it :)

**Comment by franbueno** [comment]
Hey @sahat,

It works :)

paypal: {
          name: 'paypal',
          url: '/auth/paypal',
          clientId: 'YOUR-CLIENT-ID',
          redirectUri: window.location.origin || window.location.protocol + '//' + window.location.host,
          authorizationEndpoint: 'https://www.sandbox.paypal.com/webapps/auth/protocol/openidconnect/v1/authorize',
          requiredUrlParams: ['scope'],
          scope: ['profile+email+address+phone'],
          scopeDelimiter: ' ',
          oauthType: '2.0',
          popupOptions: { width: 527, height: 582 }
        }

*Remember: Check the scope that you are passing in the request and check your app under https://developer.paypal.com -- Click Applications --- Click App Name --- Log In with PayPal Click Advanced Options --- Expand each of the customize link and check the attributes for the scopes in your request.

**Comment by clarle** [comment]
Thanks for sharing that, @franbueno!

@LetsDoIt-, we would recommend you use @franbueno's implementation.  It's fairly straightforward, and would be the path forward we would suggest for anyone trying to do PayPal integration.

Let us know if you have any other questions.
