### ISSUE TITLE
Google logout

### ISSUE THREAD

**Issue by mrowe122** [sahat/satellizer#650]
Hello, I figured out a problem if someone can help me. I am able to sign in correctly with google, and I have a token to use. But when I'm going to sign-out, the token does get deleted but I'm not completely signed out of Google. For example, I open up Youtube.com (not signed in), I will now sign in on my website using satellizer with Google. I get the ok, now im signed in on my website, I go back to youtube, refresh, im now signed in on youtube with the email i signed in on my website. When I logout out of from my website using $auth.logout(); the token does get removed. But i remain signed into Youtube. anyone have any ideas why and how to fix?? Thank you in advance

PS, im using node

**Comment by ionut-tanasa** [comment]
see #494

**Comment by clarle** [comment]
Hi @mrowe122,

@ionut-tanasa is correct - `$auth.logout()` signs you out of *your* application, not necessarily Google / Facebook / any other identity provider.

Please see #494 for any workarounds if you have any other questions.

Thanks!
