### ISSUE TITLE
is method public Response loginLinkedin(){ return Response.ok().build();} is complete or some code needs to be written, can somebody share the code for linkedin login in server java

### ISSUE THREAD

**Issue by amanlahariya** [sahat/satellizer#654]

**Comment by sahat** [comment]
LinkedIn auth for Java has not been implemented yet. You can look at existing java auth examples, and look at how Node.js Linkedin auth is implemented. There is no magic, no abstractions, if you just follow the code, it should be pretty trivial.

I will get to it eventually, but don't have the bandwidth to do it right now.
