### ISSUE TITLE
Use main browser window instead of popup?

### ISSUE THREAD

**Issue by sunild** [sahat/satellizer#656]
I've been noticing a problem w/Chrome lately where the Satellizer popup window is opening in the background, behind the current browser window.

It's confusing for users, b/c they click the button to login and nothing seems to happen. We're noticing this in Chrome (Version 46.0.2490.86 (64-bit)) on Mac OS. Not an issue with Safari or Firefox.

Chrome also has a pop up blocker enabled by default, and it's easy for users to miss that Chrome has blocked the popup window.

I'm noticing that some sites using social logins are not using pop up windows for social logins (StackOverflow, Buffer, HootSuite).

I also noticed the `display: 'popup'` entry in the configuration options. I tried passing `window` instead of 'popup` but that had no effect. In looking at the code, I don't see this setting being used (I could have missed it). 

Is it possible to not use a pop up window?

**Comment by szahn** [comment]
+1 this

**Comment by sahat** [comment]
> Is it possible to not use a pop up window?
No it is not supported, and there are no plans to add it.

Those sites you've linked are not single page apps. It doesn't matter if you redirect away to facebook, twitter, google and come back. That's not the case for Angular or any other single page apps where redirect/page refresh can reset your app state.

If you do not wish to you use a popup authorization flow, you may just use [passport.js](http://passportjs.org/) (assuming you are running Node on the back-end). 

Personally, I have never run into any issues that you describe and I run Chrome with AdBlocker.

**Comment by sunild** [comment]
Got it, it makes sense... The pop is necessary b/c the SPA needs to maintain state while the redirects are occurring.

I'm at a loss to explain why Chrome is misbehaving in terms of the pop up window not appearing in the foreground.

Given others are not experiencing that, I have hope that it's just an isolated problem with my app and thus can be fixed.

**Comment by sahat** [comment]
@sunild Have you tried using an Incognito Chrome window without any extensions? There was a case a month ago, reported by one of the users here, where authentication was failing because of some Chrome extensions I can't recall anymore. Disabling that extension fixed the problem.

**Comment by metal3d** [comment]
So the question is "why is there a display option" ? 
I also need to use a redirection (or iframe) to display login form of my OAuth2. I thought that there were possibilities to use other way to display form that popup just because I saw that option. Right now, I'm sad because I will stop to use satellizer only because my client asked me to display login form in a new window or in iframe. 
That's really a pitty because satellizer is way better than a lot of other Angular modules I tried...

**Comment by bourgeois247** [comment]
+1

@sahat even if a redirect will reset application state in any case, we[your end users] should be able to choose if we want to use the main browser window regardless, and somehow worry about application state resets if at all it becomes necessary. This is an awesome library, but like @metal3d, my client has  requested main browser redirect implementation....sad.

**Comment by szahn** [comment]
I agree, for some apps the start of the application is when you log in so to be redirected and back is the start of the entire flow of the application. Sometimes an application reset is a good thing, especially if you want to reset the security state. This is more common in business apps I think.

**Comment by metal3d** [comment]
At this time, I made a "workaround": 
I've integrated the iframe url that I get from popup (and manipulate url to integrate some variable information) - then register "satellizer_token" in localStorage when frame redirects with "?code=..." + refresh window.parent (`window.parent.location.reload()`)

On relead, satellizer seems to be ok with my token and that seems to work as expected... So I can confirm that tweaking makes the whole process working.

I really don't know the complexity that satellizer yields to be unable to use an iframe. And I really don't have the time right know to try to propose a PR.

**Comment by vjames-bmc** [comment]
@metal3d I am also facing a similar situation. Could you share the details of the workaround that you mentioned?

**Comment by metal3d** [comment]
_Edited..._
I had to find the popup url to create an iframe inside my own page instead, configure oauth2 callback page to set a GET argument that I can check
Then when the oauth2 page back to my home page (with "?token" argument), I detect this argument, write localstorage value, redirect parent frame to my application...
A way complicated to implement solution, but I can confirm that after a long time of test, we could do it. I'm pretty sure that satellizer team can implement this...

**Comment by vijujames** [comment]
Thanks a lot Patrice. That helps.

**Comment by odravison** [comment]
When I tried to use `window` as a value of display option I got this:

`display must be one of the following values: async, iframe, page, popup, touch, wap`

Maybe this helps someone.
