### ISSUE TITLE
getting reponse unable to process json

### ISSUE THREAD

**Issue by amanlahariya** [sahat/satellizer#657]
@POST
  @Path("linkedin")
  @UnitOfWork
  public Response loginLinkedin(@Valid final Payload payload,
	      @Context final HttpServletRequest request)throws JOSEException, ParseException,
	      JsonParseException, JsonMappingException, IOException {
	  final String accessTokenUrl = "https://www.linkedin.com/uas/oauth2/accessToken";
	    final String peopleApiUrl = "https://api.linkedin.com/v1/people/~:(id,first-name,last-name,email-address,picture-url)";
	    Response response;

	    // Step 1. Exchange authorization code for access token.
	    final MultivaluedMap<String, String> accessData = new MultivaluedHashMap<String, String>();
	    accessData.add(CLIENT_ID_KEY, payload.getClientId());
	    accessData.add(REDIRECT_URI_KEY, payload.getRedirectUri());
	    accessData.add(CLIENT_SECRET, secrets.getLinkedin());
	    accessData.add(CODE_KEY, payload.getCode());
	    accessData.add(GRANT_TYPE_KEY, AUTH_CODE);
	    response = client.target(accessTokenUrl).request().post(Entity.form(accessData));
	    accessData.clear();

	    // Step 2. Retrieve profile information about the current user.
	    Map<String, Object> responseEntity = getResponseEntity(response);
	    response =
	            client.target(peopleApiUrl).queryParam("access_token", responseEntity.get("access_token"))
	                .queryParam("expires_in", responseEntity.get("expires_in")).request("text/plain").get();
	    final Map<String, Object> userInfo = getResponseEntity(response);
	    

	    // Step 3. Process the authenticated the user.
	    return processUser(request, Provider.LINKEDIN, userInfo.get("id").toString(),
	            userInfo.get("firstname").toString());
  }

**Comment by clarle** [comment]
Hi @amanlahariya,

We don't have enough information to help debug your issue. 

Please let us know if there's any other information you can help provide us, such as the error response you're getting back from the server.

You're welcome to re-open this issue if you have any other questions or data you can help provide.

Thank you!
