### ISSUE TITLE
Use Satellizer to authenticate with custom oAuth provider

### ISSUE THREAD

**Issue by ferasodh** [sahat/satellizer#659]
Hi,

I have a django backend application which acts as an oAuth provider. Can I use Satellizer from my front end to authenticate with my custom oAuth server without redirects and popups? Is there any sample on that?

Thanks,

**Comment by sahat** [comment]
@ferasodh I haven't seen yet OAuth that does not require redirect action to the provider. So probably not. Popups is also the only way to go as it is at the core of this module and would require a major rewrite if you wanted a full page redirect.

If you are fine with that, then yes you can certainly use Satellizer with a custom OAuth back-end. I will try to add a Node.js example in the near future that implements a custom OAuth 2.0 provider.
