### ISSUE TITLE
PhoneGap (Cordova) callback issues

### ISSUE THREAD

**Issue by makerepeat** [sahat/satellizer#665]
I'm trying to get PhoneGap working with Satellizer, but I seem to have a issue with the callback. Here is my Satellizer config:

    $authProvider.cordova = true;
    $authProvider.facebook({
        clientId: env.facebook.client_id,
        redirectUri: 'http://localhost'
    });

I've setup the App in Facebook, it works in the desktop browser, but in the PhoneGap App tester, it doesn't quite complete the loop.

1. I click login with facebook, and the popup window opens.
2. I authorize the app, and I think it tries to redirect back to the redirectURI, though I can't confirm that.
3. The popup window closes, leaving me at the auth screen.
Any ideas?

**Comment by sahat** [comment]
@makerepeat Did you set Site URL `http://localhost` in your Facebook app settings? Maybe you already know this but you will need two separate apps, one with `http://localhost:3000/` (default in the examples) and one with `http://localhost/` Site URL.

It would also help you if you could post a screenshot, brief video screen cast, or better yet console output from your phone simulator.

**Comment by makerepeat** [comment]
Thanks for the reply! 

Firstly, I wasn't aware that two separate apps were need. Is that in the documentation? Can you help me understand why that is?

The application (web version) is currently running here: http://dev.gettracer.com, and I'm building a separate dist folder with gulp to drop into Phonegap. Maybe you can spot the issue?

**Comment by makerepeat** [comment]
Figured it out! Just had to set the url field so the app knows about the server, then get the redirects to match. Thanks very much for your time, and great work on this tool.

**Comment by sahat** [comment]
@makerepeat :+1:. I also just noticed today that Ionic example does not have `url` in the Facebook example. It should be there now. (http://localhost:3000/auth/facebook).

As for Callback URLs that's just how all OAuth providers work. They will only redirect back to the URL you specified in their app management page. `localhost` and `localhost:3000` are different callback URLs as far as Facebook is concerned.
