### ISSUE TITLE
$auth.login is not a function

### ISSUE THREAD

**Issue by rozehan** [sahat/satellizer#667]
Hi everyone,

I'm doing everything as written but always get same error:

    angular.js:12450 TypeError: $auth.login is not a function

login.html:
 <form name="form" class="form-validation mt-20" novalidate>

      <div class="form-group">
        <input type="email" class="form-control underline-input" placeholder="Email" ng-model="user.email" required>
      </div>

      <div class="form-group">
        <input type="password" placeholder="Password" class="form-control underline-input" ng-model="user.password" required>
      </div>

      <div class="form-group text-left mt-20">
        <button type="submit" class="btn btn-greensea b-0 br-2 mr-5" ng-click="login()" ng-disabled='form.$invalid'>Login</button>
        <label class="checkbox checkbox-custom checkbox-custom-sm inline-block">
          <input type="checkbox"><i></i> Remember me
        </label>
        <a ui-sref="core.forgotpass" class="pull-right mt-10">Forgot Password?</a>
      </div>

    </form>

Login controller:
 

     .controller('LoginCtrl', function ($scope, $auth) {
    
        $scope.user = {};
        $scope.user.email = 'test@gmail.com';
        $scope.user.password = 'test';
    
        $scope.login = function () {
          $auth.login($scope.user).then (
            function (response) {
              console.log(response);
            },
            function (error) {
              console.log(error);
            }
          )
        }

app.js:
 

         .config(['$stateProvider', '$urlRouterProvider', '$authProvider', function($stateProvider, $urlRouterProvider, $authProvider ) {
        
              $authProvider.loginUrl = '/auth/login';
    ...

I tried different settlements, researched github issues but not found a solution.

Whats my fault? How can I fix it?

  [1]: https://github.com/sahat/satellizer

**Comment by sahat** [comment]
@rozehan Have you tried running the sample app provided in the repo? If it works fine then the issue is on your side.

The only reason I can think of is that you have another module with conflicting `$auth` service (I have never run into such case so not sure how Angular handles it)  or perhaps you yourself have overridden `$auth` variable somewhere.

**Comment by rozehan** [comment]
Yes, it conflict with ng-token-auth. When I uninstall other module, it worked! 
Thanks.

**Comment by chikitovivas** [comment]
Thanks
