### ISSUE TITLE
Question on the flow of Oauth2 authentication

### ISSUE THREAD

**Issue by MichaelFromin** [sahat/satellizer#668]
I have added satellizer to my Angular project.  Its added as a dependency and I have configured satellizer in my app.js:

```
app.config(['$authProvider', function($authProvider) {
        $authProvider.google({
            clientId: 'xxxxxxxxxxxx',
            redirectUri: 'http://localhost:63342'
        });
    }]);
```

I have added a "sign in with Google" link on the home page and when I click it I **do** get a new smaller browser window that asks me to login to my Google account.  So far so good.  

When I type in my Google password the smaller browser window closes and I see this in the JavaScript console: 

`POST http://localhost:63342/auth/google 404 (Not Found)`

I suspect that this means that Google is trying to return the results of the attempt to login to that URL?  In Angular do I need to define this route and do some processing with the response?   I feel like I am at step 10 of the Login with OAuth 2.0 list in the Readme but I am unclear what is meant by "Parse the token and save it to Local Storage for subsequent use after page reload".

Is the token in the response that is sent to `/auth/google`?  Do I simply define a route to grab that token and stick it in local storage and then redirect to the actual home page of the application?

I apologize if this question is "stupid" - I have spent the past hour stuck at this stage and can't figure out what should happen at this point.

**Comment by ryanhca** [comment]
I too am having the same issue but with "github" I hope a work around comes around soon.

**Comment by OleksandrPoltavets** [comment]
The same for me with facebook, I have:
```
POST http://localhost:9000/auth/facebook 404 (Not Found)
```
Seems than route need to be configured to grab the code but not sure if this is correct approach.
Will be glad to hear some advices on this.

**Comment by mikepc** [comment]
Have you implemented the server routes? 

You have to implement token-based authentication in the server logic you're authenticating against. The post to /auth/facebook is an API call that you have written that authenticates your auth Secret against the specific service's API. In the examples folder there are examples for many of the most common server languages, but in most cases the examples will need to be tailored to fit your application's needs. Satellizer provides client-based OAuth to obtain a code that can be traded for an auth token.

It's a multi-stage orchestration that in the end results in your user having an Authorization token stored in DOMStorage on their browser. Your server will then authorize this token on every request. 

The General flow is...

User clicks Facebook link ->
    Satellizer Makes client-based request to get a authorization code from Facebook ->
       Once the authorization code is returned, a POST to YOUR API occurs containing the authorization code ->
          Via a POST, Your API takes the authorization code and your service's Facebook Secret and gets a profile from Facebook (This is the action that is 404'ing I believe) -> Your API then takes that profile, performs the stuff it needs to, serializes the profile into a JavaScript Web Token (JWT) and returns that to Satellizer -> Satellizer Stores that token and then attaches it to the HTTP header for every $http call.

**Comment by jongunter** [comment]
I had this issue as well. You're trying to authenticate your front-end (single page maybe?) app without any sort of backend server that you own? Then you need to use an Oauth2 implicit flow. Just make sure your responseType is configured as `token`, not `code` and satellizer should use the implicit flow. Or at least that's what worked for me.

**Comment by clarle** [comment]
Hi all,

@mikepc and @jongunter are correct.  

If you're trying to authenticate on your client only, you'll need to use the implicit flow.  Otherwise, you'll have to have your own backend as well.

Feel free to re-open this issue if you have any other questions!

**Comment by heshamelmasry77** [comment]
So guys how to solve this problem. I red the comments but still no answer. I wanna get the email and  name on my front-end
