### ISSUE TITLE
How to save objective to token

### ISSUE THREAD

**Issue by kunny171** [sahat/satellizer#669]
![token](https://cloud.githubusercontent.com/assets/3429970/11706112/656770b4-9f28-11e5-8bf9-34d30f3d4f69.png)
Hi, after login success, i want save personal infomation to token (ex : user, company, title, usertoken).
So, how can do that ?
I try to save object to token but not success :(. (image)

**Comment by dsge** [comment]
You cannot modify a JWT token's payload on the frontend, but you can read it, that is the point of using JWT.

I recommend having an api endpoint for reading and modifying user data. Put only non-changing data (like your `Id` field) into the JWT token payload.

**Comment by sahat** [comment]
As @dsge pointed out, you cannot modify JWT. That's the purpose of the signature part in a token structure. (Base64headers . Base64payload . Base64signature)

Plus only server can issue that token.

So if you want to modify the payload, you will need to send new user data to the server, save it in database or whatever else you have to do, then issue a new JWT token with the updated payload.
