### ISSUE TITLE
Facebook iPhone (html5mode)

### ISSUE THREAD

**Issue by mikepc** [sahat/satellizer#674]
I'm running a MEAN stack application in html5mode.

Satellizer is working great, except Facebook (iPhone only) doesn't work (most of the time o.0). It works sometimes, but a third of the time it doesn't finish authenticate(), but just redirects to the website root. I've spent about 8 hours on this problem to no avail :(

The app is behind an nginx reverse proxy, if that might help.
// Configuration.
angular.module(ApplicationConfiguration.applicationModuleName, 
              ApplicationConfiguration.applicationModuleVendorDependencies).config(['$locationProvider', '$authProvider',
  function ($locationProvider,  $authProvider) {

              $locationProvider.html5Mode(true).hashPrefix('!');

               $authProvider.facebook({
                  clientId: window.FACEBOOK_ID
                });

                $authProvider.google({
                  clientId: window.GOOGLE_ID
                });

                $authProvider.twitter({
                  clientId: window.TWITTER_KEY
                });
                
                $authProvider.baseUrl = '/';
                
                $authProvider.loginUrl =  '/auth/login';
                $authProvider.signupUrl = '/auth/signup';
                $authProvider.unlinkUrl = '/auth/unlink/';
                

    

}]);

//Authenticate
    
    $scope.authenticate = function(provider){
     $auth.authenticate(provider)
        .then(function() {
             toastr.success('You have successfully signed in with ' + provider + '!');
            
              /*
              if($state.previous.state.name === 'home' || $state.previous.state.name === 'authentication.signup')
              {
                  $state.go('listPads');
              }else{

               // And redirect to the previous or home page
                $state.go($state.previous.state.name || 'listPads', $state.previous.params);
              }
              */            

             
             $location.path('/pads');

 
        })
        .catch(function(error) {
          if (error.error) {
            // Popup error - invalid redirect_uri, pressed cancel button, etc.
            toastr.error(error.error);
          } else if (error.data) {
            // HTTP response error from server
            toastr.error(error.data.message, error.status);
          } else {
            toastr.error(error);
          }
        });
    };

You'll notice the $state() change has been commented out, that was a result of my troubleshooting to see if the state change was mucking with things. The only considerable difference between my app and the sample app is the fact that html5mode is Enabled. Is this the cause? Any possible workarounds? I need html5mode to work.

Everything works fine on the desktop. On iPhone on Safari and Chrome, facebook doesn't work.

Any help at all would be appreciated. Thanks in advance.

UPDATE: I tried adding an empty route and setting that empty route as the facebook redirect, but it just dumps me at a blank page :(

**Comment by viniciusdacal** [comment]
@mikepc did you try to set config `cordova` as true? I think it could help.

**Comment by barryvdh** [comment]
I'm also having issues in Chrome.
It shows the Facebook login page, it tries to redirect back but never reaches the original page. It now has 2 tabs; 1 waiting for the response and 1 on the homepage with the ?code in the query, but doesn't do anything.

Any ideas?

**Comment by aligajani** [comment]
@barryvdh  Same here.

**Comment by mikepc** [comment]
I will try that tonight, if it works you will be a lifesaver! Thank you!

**Comment by mikepc** [comment]
$authProvider.cordova = true; 

Didn't work :( Now it won't log in at all. Just opens another browser window with the app in it.

**Comment by mikepc** [comment]
Debugging websites on iphone is such a pita :\ My heart sinks for the poor guys debugging this.

**Comment by barryvdh** [comment]
You can connect your Safari dev tools with the iPhone browser.

**Comment by aligajani** [comment]
You can use Web Inspector

On Fri, Dec 18, 2015 at 12:38 PM, Barry vd. Heuvel <notifications@github.com
> wrote:

> You can connect your Safari dev tools with the iPhone browser.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahat/satellizer/issues/674#issuecomment-165703905>.
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by sahat** [comment]
@mikepc I don't think this is html5mode related issue. It works fine here with or without it on Desktop. Haven't tried html5mode with iOS Safari. 

Could this issue be related to https://github.com/sahat/satellizer/issues/680?

**Comment by mikepc** [comment]
Mobile clients are the only problem I have, on droid and iOS. Desktop works
great.  Since it works every time from the demo site and the demo site is
not html5 that's the only difference I can discern.

**Comment by aligajani** [comment]
Desktop works great. Same internet connection. Mobile plays up.

We need to get this fixed or at least figure out where the problem lies exactly.

**Comment by mikepc** [comment]
Yeah, pretty broken.  Debugging it has gotten me nowhere. It's like the
error poofs into the aether.

**Comment by mikepc** [comment]
Anyone able to get anywhere with this? I'm about to try to tackle it again, confidence is low though, my ninja skills have failed me thus far.

**Comment by aligajani** [comment]
Nope, my login success rate with a slow internet connection using iOS 9 Safari is 7/10. 3 times it will not login. I don't know it's a timeout issue with Facebook due to my slow internet connection?

**Comment by mikepc** [comment]
Another thing I wanted to point out is that it's not limited to Facebook, but Google+ has the same issue

**Comment by barryvdh** [comment]
But does the oauth code it reach your server? It could be that the new window isn't closed properly (the empty window to the root url, just used for getting the hash from the location.)
If it doesn't close, but does process, the login is actually complete but not visible because of the pop-up window in front of the app.

**Comment by mikepc** [comment]
It redirects almost immediately to the home page it seems. Right now it's working totally so I'm having a bugger reproducing it, but I had user complaints on my dev server last night, so I know the issue is still happening. My users are going to burn me in effigy if I go to prod with it.

**Comment by aligajani** [comment]
It redirects to the website domain after the Facebook oauth has logged in and redirected , but then it doesn't seem to login .. It stays there..I have to sometimes retry multiple times to actually login to my app..I have a dev setup live so I'll post a URL so you guys can login and reproduce with me!

**Comment by swrocket** [comment]
I had the same issues exactly in the exact same environment and after getting the latest build it is now working 
I'm sure though that it's still going to happen

**Comment by aligajani** [comment]
@swrocket  Is it working 100% fine on the new version? Can @mikepc  confirm please?

**Comment by swrocket** [comment]
It seems to be working...but I only test on my phone (iPhone 5) so I can't be sure of any other devices

**Comment by aligajani** [comment]
I have tested on my iPhone 6S too, using the older version, had the issues
I created the thread for.

 I will retry it on the new version and report back.

On Mon, Jan 18, 2016 at 3:25 PM, Andrei Merisanu <notifications@github.com>
wrote:

> It seems to be working...but I only test on my phone (iPhone 5) so I can't
> be sure of any other devices
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahat/satellizer/issues/674#issuecomment-172560067>.
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by swrocket** [comment]
Update.
So one of the issues I encountered here is related to browser privacy.
If Safari privacy is on then authentication fails.
Does the library fall back if localStorage is unavailable, as it is with privacy mode?

**Comment by mikepc** [comment]
We have fixed the issues that we had with our satellizer implementation.  I wanted to make that clear. The latest build of Satellizer was not at issue.  
What was giving us grief was legacy code that was re-writing urls in the middle of the oauth redirect, clobbering them sometimes, if the timing were right the redirect would land fine but with any latency the url would be rewritten and it would slaughter satellizer.
Make sure you have no code that is fiddling with urls during bootstrap of angular.


Sent from Outlook Mobile




On Wed, Jan 20, 2016 at 7:19 AM -0800, "Andrei Merisanu" <notifications@github.com> wrote:












Update.

So one of the issues I encountered here is related to browser privacy.

If Safari privacy is on then authentication fails.

Does the library fall back if localStorage is unavailable, as it is with privacy mode?

**Comment by swrocket** [comment]
Thanks Mike.
So I should be ok with the current build (0.13.4) if I don't have any code at all touching the urls, which I don't.
If Safari privacy is on, it should still be able to store the Bearer token and use it later yes?

**Comment by aligajani** [comment]
What do you mean by touching the URLs?

On Wed, Jan 20, 2016 at 4:56 PM, Andrei Merisanu <notifications@github.com>
wrote:

> Thanks Mike.
> So I should be ok with the current build (0.13.4) if I don't have any code
> at all touching the urls, which I don't.
> If Safari privacy is on, it should still be able to store the Bearer token
> and use it later yes?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahat/satellizer/issues/674#issuecomment-173271583>.
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by mikepc** [comment]
with privacy turned on it was my understanding localstorage still worked it just got blown away after session, like incognito mode on Chrome.



Sent from Outlook Mobile




On Wed, Jan 20, 2016 at 8:56 AM -0800, "Andrei Merisanu" <notifications@github.com> wrote:












Thanks Mike.

So I should be ok with the current build (0.13.4) if I don't have any code at all touching the urls, which I don't.

If Safari privacy is on, it should still be able to store the Bearer token and use it later yes?

**Comment by swrocket** [comment]
Not on Safari. If privacy is on then you cannot access localStorage at all

**Comment by mikepc** [comment]
I had code that was redirecting if the url contained #_
This was for the old oauth system, which was  mostly incompatible with satellizer, and also totally redundant and useless.
Once the code was removed satellizer is working for all my users in html5mode with facebook, twitter and google.

Sent from Outlook Mobile




On Wed, Jan 20, 2016 at 9:01 AM -0800, "Andrei Merisanu" <notifications@github.com> wrote:












Not on Safari. If privacy is on then you cannot access localStorage at all

**Comment by aligajani** [comment]
@mikepc: But is it working on mobile devices, which is the original issue ..

On Wed, Jan 20, 2016 at 5:23 PM, mikepc <notifications@github.com> wrote:

> I had code that was redirecting if the url contained #_
> This was for the old oauth system, which was  mostly incompatible with
> satellizer, and also totally redundant and useless.
> Once the code was removed satellizer is working for all my users in
> html5mode with facebook, twitter and google.
>
> Sent from Outlook Mobile
>
>
>
>
>
> On Wed, Jan 20, 2016 at 9:01 AM -0800, "Andrei Merisanu" <
> notifications@github.com> wrote:
>
>
>
>
>
>
>
>
>
>
>
>
> Not on Safari. If privacy is on then you cannot access localStorage at all
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahat/satellizer/issues/674#issuecomment-173286028>.
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by swrocket** [comment]
It works perfectly for me as well, except on iOS with Safari in Privacy mode

**Comment by mikepc** [comment]
Yes, that was the original issue and it is working completely.
The site will launch in a few days, I will pass out the url and you guys can check it out.

Sent from Outlook Mobile




On Wed, Jan 20, 2016 at 9:25 AM -0800, "Ali Gajani" <notifications@github.com> wrote:










@mikepc: But is it working on mobile devices, which is the original issue ..



On Wed, Jan 20, 2016 at 5:23 PM, mikepc <notifications@github.com> wrote:



> I had code that was redirecting if the url contained #_

> This was for the old oauth system, which was  mostly incompatible with

> satellizer, and also totally redundant and useless.

> Once the code was removed satellizer is working for all my users in

> html5mode with facebook, twitter and google.

>

> Sent from Outlook Mobile

>

>

>

>

>

> On Wed, Jan 20, 2016 at 9:01 AM -0800, "Andrei Merisanu" <

> notifications@github.com> wrote:

>

>

>

>

>

>

>

>

>

>

>

>

> Not on Safari. If privacy is on then you cannot access localStorage at all

>

>

>

> —

> Reply to this email directly or view it on GitHub.

>

>

>

>

>

>

>

>

>

>

>

>

> —

> Reply to this email directly or view it on GitHub

> <https://github.com/sahat/satellizer/issues/674#issuecomment-173286028>.

>







-- 





Ali Gajani

Founder at Mr. Geek

www.mrgeek.me

www.aligajani.com

**Comment by aligajani** [comment]
Okay looking forward to testing yours. So you are saying the latest most
version fixes it.

How do I update mine if I have satellizer 0.12

On Wed, Jan 20, 2016 at 5:37 PM, mikepc <notifications@github.com> wrote:

> Yes, that was the original issue and it is working completely.
> The site will launch in a few days, I will pass out the url and you guys
> can check it out.
>
> Sent from Outlook Mobile
>
>
>
>
> On Wed, Jan 20, 2016 at 9:25 AM -0800, "Ali Gajani" <
> notifications@github.com> wrote:
>
>
>
>
>
>
>
>
>
>
> @mikepc: But is it working on mobile devices, which is the original issue
> ..
>
>
>
> On Wed, Jan 20, 2016 at 5:23 PM, mikepc <notifications@github.com> wrote:
>
>
>
> > I had code that was redirecting if the url contained #_
>
> > This was for the old oauth system, which was mostly incompatible with
>
> > satellizer, and also totally redundant and useless.
>
> > Once the code was removed satellizer is working for all my users in
>
> > html5mode with facebook, twitter and google.
>
> >
>
> > Sent from Outlook Mobile
>
> >
>
> >
>
> >
>
> >
>
> >
>
> > On Wed, Jan 20, 2016 at 9:01 AM -0800, "Andrei Merisanu" <
>
> > notifications@github.com> wrote:
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> > Not on Safari. If privacy is on then you cannot access localStorage at
> all
>
> >
>
> >
>
> >
>
> > —
>
> > Reply to this email directly or view it on GitHub.
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> >
>
> > —
>
> > Reply to this email directly or view it on GitHub
>
> > <https://github.com/sahat/satellizer/issues/674#issuecomment-173286028>.
>
> >
>
>
>
>
>
>
>
> --
>
>
>
>
>
> Ali Gajani
>
> Founder at Mr. Geek
>
> www.mrgeek.me
>
> www.aligajani.com
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub.
>
>
>
>
>
>
>
>
>
>
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/sahat/satellizer/issues/674#issuecomment-173297972>.
>



-- 


Ali Gajani
Founder at Mr. Geek
www.mrgeek.me
www.aligajani.com

**Comment by kiro64** [comment]
i just try to test on my site again. Testing with iPhone 5s, IOS 9.2
look like using Safari work sometime, "Opera Mini" is not work at all.

refer to satellizer documentation. look like the problem is happen in step 4 
<img width="931" alt="screen shot 2559-01-21 at 8 47 40 pm" src="https://cloud.githubusercontent.com/assets/8982057/12482138/925c5fde-c080-11e5-86a8-e6ecf599292f.png">

there's a problem with popup on mobile and the ```code``` parameter is not send back to parent windows.
So, we need to manually handle the ```code``` parameter that we get on new tab of mobile browser.

here is my work around.
1- make sure you have a valid redirect_uri for facebook return ```code``` parameter 

2- on our redirect_uri, call the facebook authenticate on our server-side including ```code``` parameter which response from facebook. on sucess callback we need to manual call ```  $auth.setToken(token.token);  ```

( here is my controller using ui-router )

![screen shot 2559-01-21 at 8 56 39 pm](https://cloud.githubusercontent.com/assets/8982057/12482312/862675be-c081-11e5-9f71-c7dd4a75c099.png)

3-on server-side call facebook including ```code``` parameter like this ( i'm using laravel Socialite Plug-in )
![screen shot 2559-01-21 at 9 03 53 pm](https://cloud.githubusercontent.com/assets/8982057/12482500/8c7faa9c-c082-11e5-853e-eb9d9bcd6dfd.png)


it's not elegant but better than error and with this, we can wait till @sahat  find a proper way to solve this problem.

this is my site you can try your self
www.ticketdee.com

**Comment by clarle** [comment]
Hi all,

It looks like the original issue has been solved.  I'll follow up with with @kiro64's issue in #645.

We'll add to the documentation that Satellizer will not work with Mobile Safari in incognito mode, since LocalStorage is unavailable, which prevents JWTs from being saved.

Let us know if you have any other questions.

**Comment by jdme** [comment]
@kiro64 I made kind of same workaround and it works!
Only difference is that **I wrapped my ui-router controller in $timeout 1500** to let satellizer work normally in other browsers (if popup with redirect_url doesn't close in 1.5 seconds, that means you need workaround).
