### ISSUE TITLE
WithCredentials option and Local.login

### ISSUE THREAD

**Issue by pierrelouisd4j** [sahat/satellizer#683]
Hi guys !

I was wondering if they were any reason why the withCredentials option is never used during a local login ?

**Comment by sahat** [comment]
I am going to file this under a bug and fix it.

**Comment by sahat** [comment]
FYI, as a temporary workaround you can simply pass `withCredentials` as part of the options object (2nd parameter to `$auth.login`.

```js
$auth.login($scope.user, { withCredentials: true })
  .then(function() {
    // success
  })
```

**Comment by pierrelouisd4j** [comment]
@sahat I saw your update and it should work in the 0.13.3 release. 

Thanks !

**Comment by sahat** [comment]
@pierrelouisd4j 0.13.3 is now out with this fix.
