### ISSUE TITLE
Unable to set 'type' as a custom Url Param 

### ISSUE THREAD

**Issue by joeljoeljoel** [sahat/satellizer#685]
The authorization end point for 37signals requires a URL param of `type=user_agent`.  I'm unable to set type to user_agent since the type param is getting set by satellizer to '2.0' here https://github.com/sahat/satellizer/blob/master/satellizer.js#L231

It ends up generating a URL that looks like  

`https://launchpad.37signals.com/authorization/new?response_type=code&client_id=xxxxxxxxx&redirect_uri=http://example.com&type=2.0`

Is there a way around this?

    $authProvider.oauth2({
        name: '37signals',
        url: '/user/37signals',
        clientId: 'xxxxxxxxxx',
        redirectUri: window.location.origin,
        requiredUrlParams: ['type'],
        type: 'user_agent',
        authorizationEndpoint: 'https://launchpad.37signals.com/authorization/new'
    });

**Comment by joeljoeljoel** [comment]
It looks like type is just used internally so you know whether to instantiate an `Oauth1` or `Oauth2` object.  Changing `type` to `oAuthVersion` fixes my specific problem, but I'm not sure if this is just changing one problem for another.

You can see my change here: https://github.com/joeljoeljoel/satellizer/commit/319a2e615d613d29d3cc60c60fbffe294a13f847

**Comment by sahat** [comment]
Hi @joeljoeljoel,

You are right, `type` is only used internally for Oauth1 and Oauth2 services. I did not realize it would eventually conflict with a potential URL param called `type`. I will rename it to something else in the next update.

**Comment by sahat** [comment]
Fixed in https://github.com/sahat/satellizer/releases/tag/0.13.4.
