### ISSUE TITLE
Twitter Login Issue [Ionic]

### ISSUE THREAD

**Issue by archer3cl** [sahat/satellizer#692]
Im trying to implement login with Twitter on an Ionic app. 

On my app a have 
$authProvider.twitter(angular.extend({}, commonConfig, {
      url: 'http://somedir.com/#/auth/twitter',
    }));

And on my twitter app Callback URL have http://somedir.com/#/auth/twitter 

But when i try to use authenticate('twitter') function, the pop up window opens and shows the next url

https://api.twitter.com/oauth/authenticate?0=%3C&1=!&2=D&3=O&4=C&5=T&6=Y&7=P&8=E&9=%20&10=h&11=t&12=m&13=l&14=%3E&15=%0A&16=%3C&17=h&18=t&19=m&20=l&21=%3E&22=%0A&23=%20&24=%20&25=%3C&26=h&27=e&28=a&29=d&30=%3E&31=%0A&32=%20&33=%20&34=%20&35=%20&36=%3C&37=m&38=e&39=t&40=a&41=%20&42=c&43=h&44=a&45=r&46=s&47=e&48=t&49=%3D&50=%22&51=u&52=t&53=f&54=-... and so on 

Am I missing something?

**Comment by maeishoj** [comment]
same here. No clue about this yet? it works on their demo site...

**Comment by sahat** [comment]
@archer3cl Which back-end example are you using?

**Comment by archer3cl** [comment]
Im no using the examples, i just put the js on my app and set the configuration as the tutorial shows.
I was able to log in with facebook and the simple log in with satellizer and my app but its the twitter log in that fails

**Comment by sahat** [comment]
Just tested it out and works fine here. You do need to have a server app running as well. Can't do Twitter authentication completely on client-side. For Facebook it works only if you use `access_token` response type.

<img width="1328" alt="screen shot 2016-01-07 at 12 44 30 pm" src="https://cloud.githubusercontent.com/assets/544954/12177869/6e4a9baa-b53c-11e5-9064-1e1153a3f020.png">

**Comment by archer3cl** [comment]
On the ionic example you just have 
$authProvider.twitter(angular.extend({}, commonConfig, {
      url: 'http://localhost:3000/#/auth/twitter',
    }));

its the save for me, im just using ionic serve like you did and still the same blank page.

What do you mean by "server app running as well"?

**Comment by archer3cl** [comment]
Im sorry, now i get it. Ill make my server do the logic. Sorry about that. I was confused

**Comment by sahat** [comment]
@archer3cl No problem, I will try to make it more clear in the README that you need a server implementation for authentication to work.

**Comment by sahat** [comment]
Here https://github.com/sahat/satellizer#authentication-flow, hopefully that will help to others who run into the same issue.
