### ISSUE TITLE
Login via Facebook failed in MS Edge browser

### ISSUE THREAD

**Issue by ephremmie** [sahat/satellizer#694]
I have installed MS Edge browser on my Android mobile. On this page "https://alertid.com/v4/Login.aspx?v5=1" when I login via Facebook (Sign in with your Facebook account, button) it successfully logged in but it displayed a blank page. The same works across browsers but only on MS Edge it gets failed.

Please advise.

**Comment by sahat** [comment]
Sorry, I don't have an android device nor a mobile version of Microsoft Edge to debug this issue. I have only tested Satellizer using Edge on Windows 10 and it seems to work fine there.

**Comment by sahat** [comment]
Closing until someone else is willing to pick it up and debug it using an Android and Microsoft Edge.
