### ISSUE TITLE
Revoke access token calls needed

### ISSUE THREAD

**Issue by arjunmitrareddy** [sahat/satellizer#697]
$auth.logout() just clears the local storage. When a new user accesses the application and tries to sign in (using instagram/whatever) the old user's id will be accessed to this new user.

**Comment by sahat** [comment]
Can you provide a more concrete example? I am not sure I understand why a new user will see old user's data. What does new user have anything to do with it?

**Comment by clarle** [comment]
Hi @arjunmitrareddy,

I'm unable to reproduce this issue in the latest build of Satellizer.

Definitely let us know if you see this happening, but the entire authenticated session should be in the JWT, and a new user would not be able to access an old user's data.

Thanks!

**Comment by arjunmitrareddy** [comment]
Hi @sahat @clarle 
First of all @sahat, sorry about the delay I might have missed the notification alert when you commented.
The problem I was having was with the Link Account function. 
Specifically:
When a first user logins (via Google/Facebook etc) and after sometime he logouts. But his google.facebook account are not loggedout from the computer. So, when a second user logins and clicks on link account, the previous users account was getting linked to this new user account.
This is as per the example codes given.
I initially thought it would be better if I could logout from google/facebook when a user clicks logout on my website but I think that is not a good approach.
I removed the link account functionality and implemented just the sign in functionality according to my site requirements.
@clarle I will try it with the lastest build to check if this is happening.
