### ISSUE TITLE
Data only saving one user with MongoDB

### ISSUE THREAD

**Issue by andjosaquino** [sahat/satellizer#699]
When I sign into my account (The developer) my get(api/me) returns the proper response. However, when i choose any other account besides mine. It returns no data. Any hints?

So, this happens when I locally host the Satellizer demo. I was wondering if this is a problem with my authenticator or my setup, etc.
 
Object {data: Object, status: 200, config: Object, statusText: "OK"}
data: Object{
__v: 0
_id: "568d342c1f838615b5cab9a8"
displayName: "Andrew Aquino"
google: "103727224997038097181"
picture: "https://lh5.googleusercontent.com/-88c-pgLtI_k/AAAAAAAAAAI/AAAAAAAAAMY/U4KxmfTh1Dw/photo.jpg?sz=200"}

VS. 

Object {data: "", status: 200, config: Object, statusText: "OK"}
data: ""
headers: (name)
status: 200
statusText: "OK"

**Comment by andjosaquino** [comment]
I did a further investigation with the satellizer demo, and the issue still persists. I am curious as to whether or not this problem is related to my google authentication setup or the fact that this is locally hosted.

Cheers,
Andrew

**Comment by andjosaquino** [comment]
After further further investigation, the issue is with MongoDB, I currently have an issue in trying to solve it! Can anyone shed some light?

Cheers,
Andrew

**Comment by sahat** [comment]
@andjosaquino I have not experienced this issue. Does this occur only with Google, and have you tried other providers, also email and password users?

I suspect it's a MongoDB issue, as you pointed out.

It hasn't happened to me in years, but I vaguely remember back in 2013 something like that happening to me. Usually clearing the database and restarting computer helped.
