### ISSUE TITLE
Not getting email id in login with Facebook 

### ISSUE THREAD

**Issue by deven003** [sahat/satellizer#701]
I am using https://github.com/sahat/satellizer for adding login with facebook functionality in my angular + laravel ( 5.2) application.

Here is the code I am using in php to call the facebook graph api

    $client = new GuzzleHttp\Client();

    $params = [
        'code' => $request->input('code'),
        'client_id' => $request->input('clientId'),
        'redirect_uri' => $request->input('redirectUri'),
        'client_secret' => Config::get('app.facebook_secret')
    ];

    // Step 1. Exchange authorization code for access token.
    $accessTokenResponse = $client->request('GET', 'https://graph.facebook.com/v2.5/oauth/access_token', [
        'query' => $params
    ]);
    $accessToken = json_decode($accessTokenResponse->getBody(), true);

    // Step 2. Retrieve profile information about the current user.
    $profileResponse = $client->request('GET', 'https://graph.facebook.com/v2.5/me', [
        'query' => $accessToken
    ]);
    $profile = json_decode($profileResponse->getBody(), true); 

But it is only return id and name in the response. I have tried adding id,name and email as fields in the url as

     $profileResponse = $client->request('GET', 'https://graph.facebook.com/v2.5/me?fields=id,name,email', [
        'query' => $accessToken
    ]);

Still it is returning only id and name.

I also tried it in Graph API Explorer with the token returned by the above request. It shows proper response. 

![fb_statelizer_crop](https://cloud.githubusercontent.com/assets/360559/12264645/33a433c8-b95e-11e5-8a16-cabdd6503a19.png)

**Comment by sahat** [comment]
PHP example needs to be updated for Graph API 2.5, but you are right, you need to explicitly add those fields you are requesting.

Have you tried revoking app access from your Facebook page and trying to authorize again? I suspect because you have already authorized the app without using any fields, it won't give you user's personal data.

**Comment by deven003** [comment]
@sahat yes I tried explicitly adding fields after revoking app access, but still I am only getting id and name in the response.

**Comment by sahat** [comment]
Post a screenshot of your authorization screen.

**Comment by deven003** [comment]
@sahat 
![good_list_scr_crop](https://cloud.githubusercontent.com/assets/360559/12288962/9a8018a0-b9fe-11e5-9340-6152c79147f0.png)

**Comment by sahat** [comment]
I don't see anything wrong here, so I am not exactly sure why you are not seeing any fields that you specified.

**Comment by sahat** [comment]
I have spent quite a bit of time trying to figure out why it is not returning any fields. I have debugged every line in the Laravel application, everything looks good, and yet it does not return email, first name, last name, link and other fields.

```php
$fields = 'id,email,first_name,last_name,link,name';
        $profileResponse = $client->request('GET', 'https://graph.facebook.com/v2.5/me?fields=' . $fields, [
            'query' => $accessToken
        ]);
```

Not surprisingly it works fine in the Node.js example.

**Comment by sahat** [comment]
Here is the solution. You had to add fields string to the query array:

```php
$fields = 'id,email,first_name,last_name,link,name';
$profileResponse = $client->request('GET', 'https://graph.facebook.com/v2.5/me', [
    'query' => [
        'access_token' => $accessToken['access_token'],
        'fields' => $fields
    ]
]);
```

**Comment by deven003** [comment]
thanks @sahat I am also getting proper response after changing the code as above.

**Comment by niklesh-etruesign** [comment]
Yessss... it working for me also.. Thanks :)
