### ISSUE TITLE
twitter 

### ISSUE THREAD

**Issue by amanlahariya** [sahat/satellizer#702]
hi ,

i have never worked on node.js so i want to know these below parameter i have to pass in get or post method.

  var requestTokenOauth = {
      consumer_key: config.TWITTER_KEY,
      consumer_secret: config.TWITTER_SECRET,
      callback: req.body.redirectUri
    };

https://api.twitter.com/oauth/request_token?consumer_key=config.TWITTER_KEY& consumer_secret= config.TWITTER_SECRET&callback: req.body.redirectUri

will this work or i have to pass a json object of these value or some other format u are using or i have to pass these values in header.

**Comment by sahat** [comment]
@amanlahariya In the future please use Google, StackOverflow and API Reference (http://expressjs.com/en/4x/api.html) for questions like these. This is a place for reporting bugs and issues with the library.

To answer your question, consumer_key and consumer_secret are coming from the server config object - these should not be shared without anyone. On the other hand callback is being sent via POST (req.body) request to /auth/twitter.

I have provided end-to-end examples in the `examples` folder. See https://github.com/sahat/satellizer/blob/9ba8f4b37bece569673bde73657a69c852815daa/examples/server/node/server.js#L668
