### ISSUE TITLE
Facebook login from mobile device (iPhone) not working

### ISSUE THREAD

**Issue by swrocket** [sahat/satellizer#709]
When I try to log in using FB on my iPhone the popup opens and I enter the creds and then it closes but the app never receives the token.
Do I need to include some other JS file or set cordova to true somewhere?
using version 0.12.5 by the way

Thanks,

Andrew

**Comment by swrocket** [comment]
Looks like same issue as: Mobile issue because of urlRouterProvider #696

**Comment by swrocket** [comment]
As an update, I upgraded to the latest build and now it seems to work. I'll keep testing.

**Comment by sahat** [comment]
@swrocket Can I close this issue now?

**Comment by swrocket** [comment]
Yes I guess so
Thanks 

Andrew Merisanu

"Wealth, I said, and poverty; the one is the parent of luxury and indolence, and the other of meanness and viciousness, and both of discontent." Plato, The Republic
