### ISSUE TITLE
Satellizer.Js is not sending the Authorization header to the server

### ISSUE THREAD

**Issue by vinnyA3** [sahat/satellizer#713]
Problem: Satellizer is not sending the Authorization Header to server.

I am trying out Satellizer.Js on a project that I am working on. It's great so far, however, it is not properly sending the Authorization Header in the request to the server (Note: I am using Node for the backend).  In the satellizer source - specifically the httpInterceptor - I made sure that my token was being accessed correctly.  Everything checks out, I have a token that is saved in local storage as satellizer_token, and the interceptor is reaching the line where it is supposed to set the authorization header.  I'm puzzled ... 

Here is the httpInterceptor code in the sourse .. I added console.logs to make sure everything worked: 

    .factory('SatellizerInterceptor', [
      '$q',
      'SatellizerConfig',
      'SatellizerStorage',
      'SatellizerShared',
      function($q, config, storage, shared) {
        return {
          request: function(request) {
            if (request.skipAuthorization) {
              return request;
            }

            if (shared.isAuthenticated() && config.httpInterceptor(request)) {
              var tokenName = config.tokenPrefix ? config.tokenPrefix + '_' + config.tokenName : config.tokenName;
              var token = storage.get(tokenName);

              if (config.authHeader && config.authToken) {
               
                token = config.authToken + ' ' + token;
              }
              console.log('ok, so everything worked... the token is: ' + token);
              request.headers[config.authHeader] = token;
            }

            return request;
          },
          responseError: function(response) {
            return $q.reject(response);
          }
        };
      }])
    .config(['$httpProvider', function($httpProvider) {
      $httpProvider.interceptors.push('SatellizerInterceptor');
    }]);

**Comment by abunour22** [comment]
Did you solve this problem ?!
