### ISSUE TITLE
Twitter authenticacion opens blank

### ISSUE THREAD

**Issue by Nosthertus** [sahat/satellizer#715]
I have a login that will use oauth of `twitter`.. for what i have read from the docs. it does not require configuration in `authProvider`

when i click to authenticate `twitter`.. new window opens but does nothing.. it's all blank

the app is created.. the settings are fine.. what could cause this problem?

**Comment by sahat** [comment]
OAuth 1.0 starts the flow with an empty popup.

```js
popupWindow = popup.open('', defaults.name, defaults.popupOptions, defaults.redirectUri);
```

Next, it will send a POST request to your server, in this case `/auth/twitter` (default). If you haven't launched the server then you will see a blank popup.

The reason why Twitter config is empty because most of the auth happens on the server. 

If you cloned the repository, you can quickly launch a node.js server by running `npm start`, after you install npm dependencies of course.

For other server-side examples check out `examples` directory. Some of them are outdated or incomplete; Node.js is the most up to date.

**Comment by Nosthertus** [comment]
And where is defined this post request to server.. i am using `dietjs` in node server and i would like it to request in another route.. for example `/users/auth/twitter`

**Comment by sahat** [comment]
It is in satellizer.js config object which is outlined in README:

```js
twitter: {
  name: 'twitter',
  url: '/auth/twitter',
  authorizationEndpoint: 'https://api.twitter.com/oauth/authenticate',
  redirectUri: window.location.origin,
  oauthType: '1.0',
  popupOptions: { width: 495, height: 645 }
}
```

You can override any of the above properties.

$authProvider.twitter({
      url: '/auth/twitter' // POST request URL
    });

**Comment by Nosthertus** [comment]
sorry, i just realized it was already explained.. thanks anyways

**Comment by Nosthertus** [comment]
now i have a problem with facebook authentication.. after accepting to allow the app to use my public data.. nothing happens.. popup closes but angular detects nothing

**Comment by sahat** [comment]
Check your Developer Console to see if there were any errors thrown. Also, in your auth controller add a catch handler and print an error value if it indeed throws an exception.

```js
$auth.authenticate(provider, { userId: 'sahat' })
    .then(function() {
          console.log('You have successfully signed in');
          $location.path('/');
    })
    .catch(function(error) {
          console.log('error', error);
    });
```

**Comment by Nosthertus** [comment]
it loosk like this

```javascript
$scope.oauth     = {
	isOpen: false,
	authenticate: function(provider){
		$auth.authenticate(provider)
			.then(function(response){
				console.log(response);
			})
			.catch(function(error){
				console.log(error);
			});
	}
};
```

but still nothing happens

**Comment by Nosthertus** [comment]
this just logs error saying `$apply already in progress`

**Comment by sahat** [comment]
This error seems to be related to your app. Satellizer does not use `$apply` anywhere. This is the first time I am hearing about it too. I am not experienced enough with Angular to know why that is happening but you should be able to figure out why that error is thrown by looking at StackOverflow answers and looking at your code.

**Comment by Nosthertus** [comment]
that's a good question.. just $apply is not within my code. the error shows only when i use authenticate function
