### ISSUE TITLE
Authorization header problems

### ISSUE THREAD

**Issue by 3askaal** [sahat/satellizer#722]
Hi, I'm new to authentication, as I'm also new to server-side stuff.

When I'm logged in and try to reach the current user's data by going `/api/me` I'm getting a 401 and only see defined error:
`"Please make sure your request has an Authorization header".`

I did enable CORS in my server setup, and set up everything like you did in the node example.
On the client-side satellizer should take care of this? Or shouldn't it?

When I manually post my login credentials to `/auth/signin` with postman, it returns the token. So maybe the problem is it doesn't get stored to localStorage?

Sorry if this is already asked. I cant seem to find what i'm missing.

**Comment by keevindoherty** [comment]
When you make your request to `/api/me` make sure you make the request with the header: `Authorization: Bearer mytoken123`. How you do this will depend on what you're using to make the request (language, library, etc). You'll want to look for a way to add headers for your specific web service client / whatever tool you're using to make REST calls.

Hope that helps!
