### ISSUE TITLE
The google provider could better by default enforce the antiforgery state token.

### ISSUE THREAD

**Issue by paulvanbladel** [sahat/satellizer#726]
As a extra security measurement, often in oauth/openidconnect, a kind of (session) state value is sent when requesting the authorization code, the STS simply return the same value. This is to verify that the user is making the request and not a malicious attacker. 
Satellizer has already everything in place to save this state value, and to verify it. The only thing that is missing is a function to generate the state value, and an indication that the state should be encoded in the query string (e.g. via the optionalUrlParams array in the provider config).

So, adding following code in the google provider (in the satellizer config module) is doing the above:
 ``` 
optionalUrlParams: ['display', 'state'],
state: function(){
                var val = ((Date.now() + Math.random()) * Math.random()).toString().replace(".", "");
                return encodeURIComponent(val);
            }
```
More background here:
https://developers.google.com/identity/protocols/OpenIDConnect (see 1. Create an anti forgery state token)

If this make sense for you, I would be happy to submit a PR for this.
Cheers.

**Comment by sahat** [comment]
@paulvanbladel That sounds good to me. This may be a better pseudo-random generator though.

```
> Math.random().toString(36).substr(2);
Output: "tel1ede5l6h9qkt9"
```

**Comment by sahat** [comment]
Any update on this?

**Comment by paulvanbladel** [comment]
Ah OK,  you want me to make the PR.
No problem. Expect it tomorrow.

**Comment by teotwaki** [comment]
@paulvanbladel Any news on this?

**Comment by paulvanbladel** [comment]
Did pr.
#745

**Comment by teotwaki** [comment]
OK, thanks. @sahat, could we close this issue?

**Comment by sahat** [comment]
Yes forgot to close this issue.
