### ISSUE TITLE
GITKIT 

### ISSUE THREAD

**Issue by LunarDevelopment** [sahat/satellizer#729]
Hello! 

I was wondering if satellizer does the job of gitkit, I'm using Google app engines paid for an angularjs project and I need a way of getting and storing a session I'd when users log in Google,  

Not strictly a satellizer issue but I'd appreciate the help!

**Comment by clarle** [comment]
Hi @LunarDevelopment,

The Google Authentication Toolkit (now Firebase Authentication) acts fairly similar to Satellizer, but Satellizer has many more login options in comparison.

You would be able to get and store sessions (including with Google login) from Satellizer without a problem.

Let me know if you have any other questions!
