### ISSUE TITLE
Obtaining Authorization

### ISSUE THREAD

**Issue by joaquinND10** [sahat/satellizer#731]
I have a doubt About Satellizer, with which method authorization is obtained?

1. Grant Authorization Code
2. Implicit Grant
3. Grant Resource Owner Password Credentials
4. Grant Client Credentials

**Comment by NathanVss** [comment]
Satellizer use Grant Authorization Code, then you have to exchange the authorization code for a access token. This prevent to provide the access token on client side for some security reasons .

**Comment by sahat** [comment]
Yes what @NathanVss said. You can however, also use Implicit Grant if that provider supports it, by changing `responseType: 'code'` (default) to `responseType: 'token'`, when configuring an OAuth 2.0 provider. That will not send a subsequent request to the server. Support for implicit token is there, but it was mostly added by someone's request. You will have to obtain user profile, verify access token all yourself.
