### ISSUE TITLE
Facebook popup on ionic, no option to close or go back when failed 

### ISSUE THREAD

**Issue by saqueib** [sahat/satellizer#734]
I am not able to close or go back when i get error from facebook saying

**You are not logged in. Please login and try again.**

There is not back button on iOS and no way to do anything, only you can close app relaunch it.

it will be good if I can open popup in new window, so i can close it if something went wrong on fb.

Here is FB Config i am using

     // Check for Platform
      if (ionic.Platform.isIOS() || ionic.Platform.isAndroid()) {
	      $authProvider.cordova = true;
	      commonConfig.redirectUri = 'http://localhost/';
      }

      // FB
       $authProvider.facebook(angular.extend({}, commonConfig, {
	      clientId: '142XXXXXXXXX',
       }));

**Comment by varmint09** [comment]
I concur that the dialog when the App says the URL is invalid, also assumes full screen and cannot be closed.

Is nobody using FBConnect, Satellizer and Ionic?

**Comment by sahat** [comment]
If you change these to `yes`, you will be able to close the InAppBrowser window.
```js
location: 'no',
toolbar: 'no',
```
https://github.com/sahat/satellizer/blob/master/examples/ionic/www/js/app.js#L24-L25

I'd like to open OAuth flow in a native mobile browser (e.g. Safari), but I don't know how to redirect back to the app with query parameters. I have zero experience with native mobile. Facebook iOS SDK does it somehow, so it should be possible. I looked around for "Ionic OAuth 2.0" tutorials, they all seem to be using the same InAppBrowser flow.

**Comment by saqueib** [comment]
Thanks @sahat it works, at least there is a button now to close it.

about native browser you should check out [inAppBrowser](https://github.com/apache/cordova-plugin-inappbrowser)

<img width="300" alt="fb-shot" src="https://cloud.githubusercontent.com/assets/6937224/13167761/34206130-d6fc-11e5-9c0c-ab6330225bf2.png">

**Comment by RickyGeek** [comment]
How did you fixed the "You are not logged in. Please login and try again." error?
