### ISSUE TITLE
isAuthenticated() remove the token if it is expried

### ISSUE THREAD

**Issue by royipr** [sahat/satellizer#736]
Why does isAuthenticated(line 375) removes the token if it is expired?

Seems to me like and unexpected behavior.. Im using the expired token to create a new one..
and if it is deleted i cannot use it.

Is there a special reason to delete it?

**Comment by sahat** [comment]
No particular reason why it is deleted. At least not anymore. It may have relied on existence of a token in local storage at some point.

I can remove that line in the next update so that it doesn't auto-delete expired tokens.

**Comment by juliancesar** [comment]
+1

**Comment by sahat** [comment]
Fixed in [3377d09453136ce9dd5420dc9605ccb021be6e6c] v0.14.0.
