### ISSUE TITLE
Authorization header not present in API Request

### ISSUE THREAD

**Issue by chrisbratherton** [sahat/satellizer#737]
So I am currently working locally, I have an API (Laravel). Everything is working great, I can login using Facebook, I get a JWT from my API and that is saved in local storage, however, after being logged and API calls do contain the 'Authorization: Bearer + token' header.

From what I understand in the docs, this should be all set up and ready to go without and config in the app side of things? 

Here is my code: 

**app.js**

```
$authProvider.tokenPrefix = '';

// Facebook
$authProvider.facebook({
    clientId: '219883618025157',
     url: APICONFIG.url + APICONFIG.version + 'auth/facebook/callback'
});
```

**Example API Call:**
```
 $http.get(APICONFIG.url + APICONFIG.version + 'auth/logout').then(function(response) {}, function(error) {});
```

**The request headers in the above request:**
```
GET /v1/auth/logout HTTP/1.1
Host: api.myapp.app
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Accept: application/json, text/plain, */*
Origin: http://myapp.app
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.109 Safari/537.36
Referer: http://myapp.app/
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
```

Any ideas what is going on here?

**Comment by royipr** [comment]
Kinda hard to tell when seeing parts of the code.. BUT there are are 3 reasons that could cause the token not to be sent on every request:
1. you have added `skipAuthorization: true`
2. `$auth.isAuthenticated` return false before the request is executed (token missing/expired)
3. You overwritten the `$authProvider.httpInterceptor`

Try to debug it.. you can open the satellizer.js in the browser and put a break point in the `SatellizerInterceptor` (this is line 916).. and check why the header is not being attached.

**Comment by chrisbratherton** [comment]
Right so after a painful few hours debugging I figured out that it was a problem with me (Time for a beer)!

I was using `$auth.logout` before actually making my API Request which obviously isn't going to work cause the token is deleted before the API Request. 

Closing as this is a non-issue with the library, just an issue with me.

**Comment by ghost** [comment]
I know this has been closed but I am facing the exact same issue and can't get my head around it.

To @royipr checklist:

1. Don't use `skipAuthorization`.
2. Token is valid.
3. Blank angular app no changes and only Satellizer installed.

Did the debug and token has been set.
However it will not be send.

![bildschirmfoto 2017-04-03 um 00 23 05](https://cloud.githubusercontent.com/assets/11746412/24591750/eabb62c0-1808-11e7-9066-24a44ed72dd5.png)

**Comment by royipr** [comment]
@salacis  how you are executing the http request?

**Comment by ghost** [comment]
Thanks for your quick response. I missed some htaccess settings in my server side rest API and therefore the header was removed! Truly not a library problem, but my own!
