### ISSUE TITLE
PhoneGap doesnt work

### ISSUE THREAD

**Issue by joehoeller** [sahat/satellizer#740]
In PhoneGap I keep getting this message from Facebook: Given URL is not allowed by the Application configuration: One or more of the given URLs is not allowed by the App's settings. It must match the Website URL or Canvas URL, or the domain must be a subdomain of one of the App's domains.

**Comment by sahat** [comment]
Use my Facebook app settings as a starting point. You will also need to update the code using your Facebook App Client ID and Client Secret.
![capture](https://cloud.githubusercontent.com/assets/544954/13264217/232e6b64-da3b-11e5-8193-34ce8e8dae03.PNG)
