### ISSUE TITLE
Google Auth

### ISSUE THREAD

**Issue by joehoeller** [sahat/satellizer#741]
What would cause this to 404?
POST http://localhost:3000/auth/google 404 (Not Found)

**Comment by sahat** [comment]
You likely forgot to start a server. Please see the README for more details. I have documented it and this question has already been asked multiple times.
https://github.com/sahat/satellizer/issues/598
https://github.com/sahat/satellizer/issues/632

https://github.com/sahat/satellizer/tree/master/examples/server
