### ISSUE TITLE
/auth/facebook not found

### ISSUE THREAD

**Issue by mavillar** [sahat/satellizer#752]
Sorry for my ignorance. i have included **Satellizer** for login purposes and when clicked any of the Social networks setup all run fine only that when receive the response, it tries to get access to an individual URL (http://www.mydomain.com/auth/facebook) in my case.

I do not know what should i do there? What kind of script?

I only need to get Email and basic data from the user. I thought that once response was received I could call to the Account Factory to get such data.

**Comment by ibrahimyu** [comment]
When you successfully logged in, you need to store user's information on your database, right? The script is to get the data from provider (in your case, Facebook) and then store it to your database.

Check server implementations here
https://github.com/sahat/satellizer/tree/master/examples/server

**Comment by mavillar** [comment]
Hi ibrahimyu, thanks. I understand now.

I've been having a look within such directory, in /php, and I do not find anything.

How it's supposed Facebook or any other Social Network send you the data?

Maybe in $_GET method?

**Comment by sahat** [comment]
@mavillar Are you familiar with Laravel framework?

All OAuth handlers are located in the *AuthController.php*: https://github.com/sahat/satellizer/blob/master/examples/server/php/app/Http/Controllers/AuthController.php

One line 100 is where you will find implementation of the URL handler for **POST /auth/facebook**.

**Comment by sahat** [comment]
Satellizer (client-side library) only helps you with launching the popup window and obtaining **code** (authorization code) parameter, the rest of the OAuth flow happens on the back-end. That's where you exchange that authorization code for access token, then use that access token to obtain user's profile information, save it to database, and return JSON web token back to the client -side that keeps you authenticated. JSON Web Token is specific to your app, it keeps users logged in. Access token you get from Facebook on the other hand is a unique time-sensitive token used for Facebook's Graph API to obtain profile information and perform Facebook actions on user's behalf.

**Comment by mavillar** [comment]
@sahat I've never used such framework, even it's the first time heard. I'll have a look but too late to be used in my actual project.

I just need to get the basic data from the user and nothing else.

**Comment by sahat** [comment]
Closing this issue since it's not a problem with Satellizer.

**Comment by ibrahimyu** [comment]
@mavillar the key is at line 100 in this file:  https://github.com/sahat/satellizer/blob/master/examples/server/php/app/Http/Controllers/AuthController.php

Basically:
1. Satellizer gives you the code parameter to /auth/facebook. Use it to send GET request to facebook (line 112).
2. From that, facebook gives you an access token. Use this access token to get whatever you want. For example, take user's basic data (line 119).
3. Save that data to database (line 140).
4. After gathering user data, make token based on your user's data.
5. Return that token to satellizer. You're logged in!

Please adapt it to your needs.
Cheers!

**Comment by digitlimit** [comment]
@ibrahimyu I have been battling with this for long seems Satellizer is not posting to /auth/facebook after authentication and access is granted from facebook.com

Any suggestion?

When the popup closes I get this 
access_token
:
"EAAJsVunI6ecBAFd8S9BFr7E0X85EBp7buSP1ZCeggjmpCJnvppXdRlZBqUo59fVGWNKoZClAg55qiY2jOJC1uRg5qZCChqWPFKKuLO9ivNQmvte2ZC3jlk5EndOL0j8g8PrGbeOuJtpZCt09p9gD1hAUMKc4ZBoC268aw422YbAG8uwmZBR21N9m"
expires_in
:
"5220"

from $auth.authenticate('facebook') promise
