### ISSUE TITLE
Disable log warnings

### ISSUE THREAD

**Issue by ivoviz** [sahat/satellizer#754]
I could've missed it and if so, I'm sorry. Is there a way to disable the warnings?

For example, there is the link method, which for some reason expects a token. Even an empty token string does a $log.warn. I know I could just send back the original JWT which was sent with the request and then the warning goes away, but it feels a bit silly to do so.

**Comment by sahat** [comment]
@ivoviz There is no way to disable warnings. They are there for a reason. In this case, I am assumine you are talking about `$log.warn('Can\'t set token without passing a value')` or `$log.warn('Expecting a token named "' + tokenPath)`?

The link() method is just an alias for authenticate(). So the flow for the link() method will be identical, and it expects a token from the server at the end of the flow, as if you are signing in for the first time.

Maybe I am misunderstanding you, but that's all I was able to infer from your brief description of your use case.

Satellizer has obviously grown a lot

**Comment by ivoviz** [comment]
@sahat Yup, I was talking about `$log.warn('Expecting a token named "' + tokenPath)`

I know it's an alias for authenticate(), I'm just assuming that one would use link() when the user is already logged in, therefor this warning is a bit misleading since there is no need to send back any token.

**Comment by sahat** [comment]
@ivoviz I see. But are you using different endpoints for initial authentication and account linking? If API endpoints are the same, then they both should return a new JWT token right?

**Comment by ivoviz** [comment]
I'm using the same endpoint, but that's just a matter of server side implementation. I might be misunderstanding the average use case then, but basically here is what I'm doing:
Guest user uses authenticate() for logging in. Gets back a JWT from the server and stores it wherever (localStorage). Now that the user is signed in he has options to link his account with other providers. For that, I'm using link(). The point is, at this point the user already had a JWT stored and used for the request, so there is no need to give him a new one imo.

**Comment by sahat** [comment]
I know I am a few months late, but I ended up removing warnings after considering multiple solutions. 9d3acd1a3527c3f51bb33f4697a53835682e45e9

It will be in the next version, either`0.15.5` or `0.16.0`.
