### ISSUE TITLE
[$injector:modulerr] Error

### ISSUE THREAD

**Issue by iotaweb** [sahat/satellizer#77]
Hello, 
I'm trying to get this working locally with the node.js example, but I am getting a client error:

```
Uncaught Error: [$injector:modulerr] Failed to instantiate module MyApp due to:
Error: [$injector:nomod] Module 'Satellizer' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
```

I think this is because in `app.js` the injected **Satellizer** module is capitalized, e.g.

```
angular.module('MyApp', ['ngResource', 'ngMessages', 'ngRoute', 'Satellizer', 'mgcrea.ngStrap'])
```

If I use **satellizer**, It works, i.e.

```
angular.module('MyApp', ['ngResource', 'ngMessages', 'ngRoute', 'satellizer', 'mgcrea.ngStrap'])
```

Is this just a typo?
P.S. thanks so much for your work on this!

**Comment by ravinleague** [comment]
I would like to comment on this issue,

I had a similar problem while using Satellizer. I have installed Satellizer using Bower. When we install with bower (bower install satellizer --save), an entry should be added to the bower.json file "satellizer": "^0.15.5"
This is the reference where the app checks for I guesss..

However, during my satellizer installation, I noticed that when I keep the bower.json file open in my editor or didn't provide the --save switch (bower install satellizer --save), satellizer was not getting installed. When I provided the switch, an entry was added to the bower.json and my app was able to detect satellizer module.
Hope this helps someone..
