### ISSUE TITLE
Salesforce and Trello Auth Support

### ISSUE THREAD

**Issue by jdrew1303** [sahat/satellizer#774]
Hi @sahat 

Thanks for the great lib :+1: 

I'm using Satellizer with Salesforce and Trello. Would you like me to open a pull request to add these as options for providers?

**Comment by sahat** [comment]
Hi @jdrew1303, thanks but I believe what we have right now is plenty.

I'd imagine most people only use the big three: Facebook, Google and Twitter.

More than adding more providers, I want to migrate Node.js auth code to other languages; Python, Java, Ruby haven't been updated in ages.

**Comment by jonathanwiesel** [comment]
I'm trying to build a custom OAuth 2.0 provider for Salesforce to launch from a Chrome Extension but when the popup navigates to redirect URI nothing happens, the `$auth.authenticate().then()` block is not fired.

This is my my code 

```
$authProvider.oauth2({
	name: 'salesforce',
	url: '/auth/salesforce',
	clientId: 'MY_CLIENT_ID',
	redirectUri: 'https://login.salesforce.com/services/oauth2/success',
	authorizationEndpoint: 'https://login.salesforce.com/services/oauth2/authorize',
	scope: ['full'],
	responseType: 'token'
});

$auth.authenticate('salesforce')
   .then(function(response) {
          console.log(response); //never fired
    })
   .catch(function(response) {
          console.log(response);
   });
```

Am I doing something wrong?

**Comment by jonathanwiesel** [comment]
Noticed I'm getting `DOMException: Blocked a frame with origin "null" from accessing a cross-origin frame.(…)` but no idea why or what should I do

**Comment by revmischa** [comment]
This fork supports chrome extensions: https://github.com/jetbridge/satellizer
