### ISSUE TITLE
Unable to sign in with Instagram.

### ISSUE THREAD

**Issue by vovochka86** [sahat/satellizer#776]
Unable to sign in with Instagram.
angular.js:11442 POST http://localhost:8000/auth/instagram 405 (Method Not Allowed)
Web server used: https://github.com/indexzero/http-server
CORS was enabled

**Comment by sahat** [comment]
Not an issue with Satellizer itself. You will have to research how `http-server` is adding CORS. There are about 4 headers you need to set if you are manually adding CORS support. With Express I just use [cors](https://www.npmjs.com/package/cors) to make my life easier.

```js
  res.header 'Access-Control-Allow-Origin', '*'
  res.header 'Access-Control-Allow-Credentials', true
  res.header 'Access-Control-Allow-Methods', 'POST, GET, PUT, DELETE, OPTIONS'
  res.header 'Access-Control-Allow-Headers', 'Content-Type'
```
