### ISSUE TITLE
$auth.signup doesn't save token

### ISSUE THREAD

**Issue by thohoh** [sahat/satellizer#778]
v0.14.0

$auth.signup  doesn't save a token to local storage when I receive a proper response from api.

**In RegisterCtrl**
```
    $scope.submit = function () {
      $auth.signup({
        email: $scope.email,
        password: $scope.password
      })
        .then(function (res) { [[ my logic ]] })
        .catch(function (err) { [[ my logic ]] });
    }
```
**API response: **
> {"user":{ // user info },"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.**********************"}

**Comment by sahat** [comment]
You are correct, signup method does not save token, because it **does not** automatically sign you in after successful registration.

You will need to manually do that yourself:

```js
$auth.signup($scope.user)
  .then(function(response) {
    $auth.setToken(response.token); //save token to local storage, essentially signs you in
    $location.path('/'); // redirect somewhere
  })
  .catch(function(response) {
    console.error(response.data.message);
  });
```
