### ISSUE TITLE
Error if users don't have email on node.js

### ISSUE THREAD

**Issue by Lazymondaysunday** [sahat/satellizer#781]
So took me forever to figure this out as there was no error handling on the user.save(). But if someone logs in with facebook or twitter. They don't get an email unless you request it specifically. So my users were getting null for the email. 

Here is the error I was getting.
```
{ [MongoError: E11000 duplicate key error index: test.users.$email_1 dup key: { : null }]
  name: 'MongoError',
  message: 'E11000 duplicate key error index: test.users.$email_1 dup key: { : null }',
  driver: true,
  code: 11000,
  index: 0,
  errmsg: 'E11000 duplicate key error index: test.users.$email_1 dup key: { : null }',
  getOperation: [Function],
  toJSON: [Function],
  toString: [Function] }
```

And because there was a unique index on the email, it was silently failing. So to get it to work I had to turn off the unique on: 

```email: { type: String, unique: false, lowercase: true },```

**Comment by clarle** [comment]
Thanks @Lazymondaysunday!

We'll add this information to a FAQ, though this seems like more of an issue with setting up the social networking services rather than something inherent to Satellizer.

Let us know if there's anything else we can do from the framework side. Appreciate the help!
