### ISSUE TITLE
Issue with twitter login

### ISSUE THREAD

**Issue by ajeesh13** [sahat/satellizer#782]
Hi All,
We have tried the satelizer with ionic hybrid application.Both the facebook and google has been working perfectly. But the twitter returns the error as mentioned below

There is no request token for this page. That's the special key we need from applications asking to use your Twitter account. Please go back to the site or application that sent you here and try again; it was probably just a mistake.

We have set up the twitter application as described in the site.
and the url is a web api link which can access from the external url.

Please help.

Thanks in advance

Thanks & Regards
Ajeesh KS

**Comment by Sandgrouse** [comment]
We are having this same issue.

**Comment by FebriPratama** [comment]
have you been setting up return from the back-end correctly ? I had that too, then i realized that the server must return json.

im using laravel as back-end

`
// return to twitter login url
return Response::json(array('oauth_token' => 'YOUR TOKEN HERE');
`

**Comment by ajeesh13** [comment]
@FebriPratama 
Thanks for your help.
I have missed this step
