### ISSUE TITLE
OPTIONS method return nothing

### ISSUE THREAD

**Issue by nowis-st** [sahat/satellizer#788]
Hi all !

I'm trying to used satellizer on AngularJS for the front-end and Laraval for the back-end.
I've followed the examples, but I've an issue: AngularJS sending an OPTIONS method to Laravel. This request returns nothing.

The route:
`Route::post('/auth/google','AuthController@google');`

The method in controller is the same than the exemple. For tests, I just add the return at the very start:

`/**
     * Login with Google.
     */
    public function google(Request $request)
    {
        return json_encode($request);
        $client = new GuzzleHttp\Client();

        $params = [
            'code' => $request->input('code'),
            'client_id' => $request->input('clientId'),
            'client_secret' => Config::get('app.google_secret'),
            'redirect_uri' => $request->input('redirectUri'),
            'grant_type' => 'authorization_code',
        ];

        // Step 1. Exchange authorization code for access token.
        $accessTokenResponse = $client->request('POST', 'https://accounts.google.com/o/oauth2/token', [
            'form_params' => $params
        ]);
        $accessToken = json_decode($accessTokenResponse->getBody(), true);

        // Step 2. Retrieve profile information about the current user.
        $profileResponse = $client->request('GET', 'https://www.googleapis.com/plus/v1/people/me/openIdConnect', [
            'headers' => array('Authorization' => 'Bearer ' . $accessToken['access_token'])
        ]);
        $profile = json_decode($profileResponse->getBody(), true);

        // Step 3a. If user is already signed in then link accounts.
        if ($request->header('Authorization'))
        {
            $user = User::where('google', '=', $profile['sub']);

            if ($user->first())
            {
                return response()->json(['message' => 'There is already a Google account that belongs to you'], 409);
            }

            $token = explode(' ', $request->header('Authorization'))[1];
            $payload = (array) JWT::decode($token, Config::get('app.token_secret'), array('HS256'));

            $user = User::find($payload['sub']);
            $user->google = $profile['sub'];
            $user->displayName = $user->displayName ?: $profile['name'];
            $user->save();

            return response()->json(['token' => $this->createToken($user)]);
        }
        // Step 3b. Create a new user account or return an existing one.
        else
        {
            $user = User::where('google', '=', $profile['sub']);

            if ($user->first())
            {
                return response()->json(['token' => $this->createToken($user->first())]);
            }

            $user = new User;
            $user->google = $profile['sub'];
            $user->displayName = $profile['name'];
            $user->save();

            return response()->json(['token' => $this->createToken($user)]);
        }
    }`

With Postman pluging, I sent a POST request on URL http://localhost:8080/laravel/index.php/auth/google. 
This request returns:
`{"attributes":{},"request":{},"query":{},"server":{},"files":{},"cookies":{},"headers":{}}`

The same request with OPTIONS, like AngularJS do, returns nothing with status code 200.

Why OPTIONS returns nothing ?

**Comment by clarle** [comment]
Hi @nowis-st,

This is due to how CORS works - it requires a pre-flight OPTIONS request to be sent in order for "approval" to be given by the server to perform a cross-domain HTTP request.

You can find more information about the process here:

https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS#Overview

Let me know if you have any other questions, or feel free to re-open this issue if you think it may be a problem in the framework.

Thanks!
