### ISSUE TITLE
The server responded with a status of 500 (Internal Server Error) 

### ISSUE THREAD

**Issue by zinzinzan** [sahat/satellizer#790]
i always get this error after y try to loging using $auth.login method, the logs of the server seems to be clean, i saw another post with the same issue but is closed and looks like there is a solutions but was not shared or posted.

**Comment by sahat** [comment]
Check Chrome network tab requests. It should contain the data of for that 500 error.

**Comment by zinzinzan** [comment]
hello sahat thx for the reply, after check the log from the rails server it was a server problem, a null mising string, i apologies for make the post  without check the server log, but maybe u can help me with another issue.

new issue:

the ionic app use angular and make request to two servers, through and api from rails server and the app make use of  satellizer module to loging in the other server for some credentials (lest call it client servers (PHP) )  everything was working with rails server until i add satellizer module i get this error when i make rails api request:

XMLHttpRequest cannot load ......url... A wildcard '*' >cannot be used in the 'Access-Control-Allow-Origin' header when the credentials >flag is true. Origin '....url....' is therefore not allowed access.

soo i set this value in the app.config  $authProvider.httpInterceptor = false;

and rails api request start working again, but now i cant get successful request to client server PHP.
