### ISSUE TITLE
token security

### ISSUE THREAD

**Issue by ersensen** [sahat/satellizer#798]
hi sahat,

i am using this wonderful model for a while. My question is how can we protect the bearer token across the wire? what are the possible attacks and the possible solutions for these attack?

**Comment by drGrove** [comment]
@ersensen,

SSL is one way to handle security for end-to-end communication. Google, Linkedin, etc. also tend to do token refreshing and expiration at specific times and well as a way to delete all instances of tokens associated with a user. In most cases I write my own whitelist table in my database mapping user ids to valid tokens and refresh tokens. If you want to go all out, you could also log IPs, devcies and such for added security. There's no full-proof way of securing anything, but those tend to help.

On a deeper dive note: I believe the standard token refresh for Github and Google is a couple of days. For server to server it's even lower (or longer). Googles server to server JWT by default is 14 hours with a long life token of 14 days.

**Comment by ersensen** [comment]
@drGrove thanks for the explanation.

**Comment by guillaumegarcia13** [comment]
Hi,
I have seen people implementing signing & encrypting of JWT: https://auth0.com/blog/json-web-token-signing-algorithms-overview/
