### ISSUE TITLE
Could you please update it to laravel 5.2.. i will be very thankful

### ISSUE THREAD

**Issue by Rahul-Giri** [sahat/satellizer#804]
Hello, actually i tried to install all the dependency and all of it get installed but the problem is on artisan command it's not working.. don't know why tried many times.. and yeah i'm using laravel 5.2 now to build my project.. could you please update this to laravel 5.2 or give me some instructions how to set in laravel 5.2.. please help me as soon as possible ,i will be thankful for this a lot.

**Comment by clarle** [comment]
Hi @Rahul-Giri,

The project was updated to Laravel 5.2 in https://github.com/sahat/satellizer/commit/c9e3c688ad2c1da3fcd5992d57cfbbca0a3170af.  

Hope that helps!
