### ISSUE TITLE
LocalStorageService not defined

### ISSUE THREAD

**Issue by yeluolei** [sahat/satellizer#807]
LocalStorageService not defined  on line 900 so the check localstorage will never success.

```javascript
          if (supported) {
            var key = Math.random().toString(36).substring(7);
            LocalStorageService.setItem(key, '');
            $window[config.storageType].removeItem(key);
          }
```

**Comment by clarle** [comment]
Hi @yeluolei,

This should be fixed in the latest build of Satellizer.

Feel free to reach out to us if you're still having any issues!

**Comment by yeluolei** [comment]
@clarle thank you~
