### ISSUE TITLE
$auth.authenticate(provider).catch() not working

### ISSUE THREAD

**Issue by achezzoh** [sahat/satellizer#811]
I am trying to implement Oauth2 login with github which works fine. However, whenever there is an error on my server, the catch() method doesnt get fired. I have even tried to throw an error manually on the server side,  which is reflected on the console, but only the then() method gets fired. Is there some additional configuration that I need to add or what?

```
On the server (using laravel):
//this method is part of my AuthController on the php server side
public function github(){
    //just for testing
    abort(500, 'Something went wrong');
}
```
```
On the client side controller
//this method is part of the controller on the js client, with all dependencies injected
github(){
    this.$auth.authenticate('github')
          .then((data) => {console.log('success response', data)})
          .catch((err) => {alert('something went wrong')});
}
```

Looking at the console, the request was sent to the url mapped to that AuthController method with the correct payload ie clientId, code and redirectUri, the server response is also logged in the console as 500. However, also logged in the console is `success response undefined` meaning the callback passed to then() was fired despite the server error, but not the one passed to catch(), confirmed by the fact that I did not see the alert. What could I be doing wrong? Please help...

**Comment by achezzoh** [comment]
Ignore this, I had an issue with my interceptor for error responses. Its amazing what a simple return can do.

**Comment by christo4b** [comment]
I'm also using this to auth github, and I get a pop-up window, which brings me to a 404. Nothing else happens in the main window, no then or catch is invoked.
