### ISSUE TITLE
TypeError: Cannot set property 'apiToken' of undefined when running a Ionic app with Protractor

### ISSUE THREAD

**Issue by 4mp3R** [sahat/satellizer#823]
When running my Ionic app with Protractor I have the following error:
```
ionic.bundle.js:26771 TypeError: Cannot set property 'apiToken' of undefined
    at Object.request (http://localhost:8100/lib/satellizer/satellizer.js:947:50)
```
This error only happens with Protractor; the app runs cleanly in the browser and on devices.
It seems like the `headers` property of an HTTP request isn't set, so this line of code crashes the app: https://github.com/sahat/satellizer/blob/master/satellizer.js#L953
The fix should be very simple; we just need to make sure the `headers` property exists, like `request.headers = request.headers || {}`

**Comment by clarle** [comment]
Hi @4mp3R,

This is a Protractor issue and not something we could fix easily in Satellizer. If we don't set the header, then it's likely something on the authentication provider side would break.

I'd add your thoughts to the Protractor issue here: https://github.com/angular/protractor/issues/740

Feel free to let us know if there's anything we can help answer, or anything we can do.
