### ISSUE TITLE
It is great if we have separate oAuth2 package for angular2 like satellizer2

### ISSUE THREAD

**Issue by umasgn** [sahat/satellizer#825]

**Comment by sahat** [comment]
@umasgn Satellizer is currently being re-written in TypeScript (https://github.com/sahat/satellizer/tree/typescript/src). Once that is done, I will have two separate wrappers - ng1 and ng2 for AngularJS 1.x and Angular 2 respectively.

**Comment by mackelito** [comment]
Is there any support for angular 2+ yet?

**Comment by niemyjski** [comment]
I'm also curious about this.
