### ISSUE TITLE
Issue with having oauth server on same domain that runs frontend too

### ISSUE THREAD

**Issue by kkogovsek** [sahat/satellizer#830]
My setup looks like this:

* Meanjs server
    * Oauth Backend Mechanizm
 * Oauth config Backend
 * Oauth config frontent

On frontend I use satellizer and it gives me folowing issue:

When I call *$auth.authenticate* it closes window immediately after loading content. My guess and after testing discovery was that if oauth server is on the same domain as app using satellizer it produces an abnormal behavior. I'm positive of that, because I used the same config to thest and changed just authorization point from domain to ip and it worked perfectly.

The error that is thrown into console after premature dialog closing:

```
angular.js:13550 TypeError: Cannot read property 'token' of undefined
    at Object.a.setToken (ng-oauthsmartis.min.js:93) // I have sattelizer in minified and concatenated file
    at ng-oauthsmartis.min.js:93
    at processQueue (angular.js:15961)
    at angular.js:15977
    at Scope.$eval (angular.js:17229)
    at Scope.$digest (angular.js:17045)
    at Scope.$apply (angular.js:17337)
    at tick (angular.js:12357)
```

Thanks for your time looking into it, and before you ask why the hell do I have to do it this way, let's just say it's a lot more easier to use existing permission mechanizm than writing new one just for one project.

**Comment by kkogovsek** [comment]
Bump.

**Comment by kkogovsek** [comment]
Bump 2.

**Comment by sosguthorpe** [comment]
This issue is fixed in the latest version. Can we get this issue closed.

**Comment by kkogovsek** [comment]
Hey thanks for fix, it works perfectly. I really appreciate your work.
