### ISSUE TITLE
I got this issue can I get help ? 

### ISSUE THREAD

**Issue by rullymartanto** [sahat/satellizer#837]
![untitled](https://cloud.githubusercontent.com/assets/5577057/15647494/17f21814-268e-11e6-82f6-088743563dc6.png)

**Comment by clarle** [comment]
Hi @rullymartanto,

It looks like you're opening up the app with the path of `/satellizer`, but you need to make sure the root is at `/` in order for the client to find the correct locations for the files.

Let me know if that solves your problem.  Please feel free to re-open this issue if it doesn't.

Thanks!
