### ISSUE TITLE
How does the official Facebook SDK javascript flow relates to satellizer's flow ?

### ISSUE THREAD

**Issue by lapinvert** [sahat/satellizer#843]
Facebook seems to recommend using its SDK for implementing Facebook Login :
https://developers.facebook.com/docs/facebook-login/web

Facebook makes no reference to Oauth 2.0, so I found it quite unclear which flow they talk about.

Is all of this all about Implicit Grant ? Or is it something else ?

If it is Implicit Grant, then satellizer already has it, and we could say facebook recommends Implicit Grant in its official SDK which is less secure than server side / authorization grant flow.
But I asked because I am no sure whether all of this is about Implicit Grant or is it some facebook special new security workflow that makes the server-side flow useless.

PS : It looks like their SDK includes a solution to always know if user is logged in in facebook or not, which I guess could be a feature of satellizer as well. Did you notice about that feature / what do you think ?

**Comment by clarle** [comment]
Hi @lapinvert,

The flow you're looking at is specific to Facebook's JavaScript SDK.

The one that Satellizer uses is [this flow](https://developers.facebook.com/docs/facebook-login/manually-build-a-login-flow), which is meant for users creating a manual login flow.  

This one has more information about OAuth and how it works with login methods that don't use the Facebook SDK.

For your last note, you can use `$auth.isAuthenticated()` to determine if a user is already authenticated.

Let me know if there's any other questions I can answer!

**Comment by lapinvert** [comment]
Thank you @clarle for your answer.

I am aware that facebook also allows you to implement the flow in the url you mentioned. Which in Oauth 2.0 terms refers to the "authorization code grant flow" (satellizer implements it, yes).

My question was more about if the Facebook's Javascript SDK implements something that Satellizer already implements with the "Implicit Grant" option, or if it is something else ?

For the `$auth.isAuthenticated()` thing, I guess that Satellizer returns `true` if access token is stored on local storage. Which is not the same thing Facebook is doing because they actually check if you are still logged in your actual Facebook account.

**Comment by sahat** [comment]
@lapinvert The only common thing between Facebook SDK and Satellizer (server-side implementation) is that they both obtain access token and retrieve profile information. That's where their similarities end. Satellizer does not concern itself with the signed-in state of a user in Facebook, likewise `$auth.logout()` will not sign you out from Facebook.

With "implicit grant" option in Satellizer, you are simply bypassing server-side implementation and obtaining access_token from Facebook directly. This is more of a special case use requested by some users. Satellizer was intended to be used with authorization code and JWT on the server.

**Comment by lapinvert** [comment]
@sahat Thank you for your answer !

Actually I think you may be misunderstanding what Facebook is actually doing with their Javascript SDK (which is when you look for "Facebook Login" or walk through their docs is clearly the solution they seem to recommend). Let me explain.

Facebook allows you to get access token directly, thus bypassing server-side implementation. Satellizer (on frontend) allows you to get a "code", not the access token, unless you use implicit grant option, to which, funny thing, you refer to as a "special use case", when Facebook is unapologetically putting it forward through its SDK in its official docs.

I just wanted to be sure that's why I asked : ) But if you think I am misunderstanding something, please enlighten me : )
I find it just really "WTF" that facebook is promoting the implicit grant flow like that... unless I missed something and what they do is actually "as secured as" the authorization code grant flow... (If anybody has a clue on that please tell us !)

As for your comment about `$auth.logout()`, it confirmed what I thought. Hence it may be a future feature for satellizer to check if user is still logged on Facebook... Its a suggestion, nothing more ! I use satellizer and truely like it. So I think it might be good to stay aware of what other SDKs and libraries are actually achieving and keep up with it when possible / desirable.
