### ISSUE TITLE
facebook redirect uri error

### ISSUE THREAD

**Issue by harryy2510** [sahat/satellizer#845]
this is the error while i am trying to login through facebook.
using laravel 5.2 socialite package

```
"message : "{"error":{"message":"Invalid redirect_uri: Can't Load URL","type":"OAuthException","code":191,"fbtrace_id":"AgymQmU7tL4"}}"

**Comment by sahat** [comment]
The Site URL you specified in developers.facebook.com does not match the redirect uri specified by Satellizer. Satellizer users current location as its default redirect uri, or `window.location.origin`. If you are using any Site URL other than root location, you will have to set it explicitly via:

```js
$authProvider.facebook({
  clientId: '........',
  redirectUri: 'absolute url where facebook redirects to, i.e. your Site URL in Facebook dashboard'

});

**Comment by harryy2510** [comment]
This is what my code looks like

``` 
$authProvider.facebook({
    redirectUri: window.location.origin + '/'
});
```

in my facebook account, site url is mentioned as ```http://officebus.com/```

In my laravel services.php file redirectUri is mentioned as ```url('/')```
It still gives the same error :(
