### ISSUE TITLE
Whoa there!  The request token for this page is invalid. It may have already been used, or expired because it is too old. Please go back to the site or application that sent you here and try again; it was probably just a mistake.

### ISSUE THREAD

**Issue by apur** [sahat/satellizer#847]
Hi,

We are using satellizer and trying to connect to twitter.
Following is the code.
We get
> Whoa there!  The request token for this page is invalid. It may have already been used, or expired because it is too old. Please go back to the site or application that sent you here and try again; it was probably just a mistake.

```js
    $authProvider.authHeader = 'x-access-token';
    $authProvider.httpInterceptor = false; // Add Authorization header to HTTP request
    $authProvider.tokenPrefix = 'twitterAuth'; // Local Storage name prefix
    $authProvider.loginRedirect = false;

$authProvider.twitter({
      url: "someurl",
      authorizationEndpoint: 'https://api.twitter.com/oauth/authenticate',
      redirectUri: window.location.origin,
      type: '1.0',
      popupOptions: { width: 495, height: 645 }
    });
```

**Comment by sahat** [comment]
Hi @apur, I can tell you it's not the issue with Satellizer but with your configuration. I would need to see your code to find out why you are getting that error.

**Comment by apur** [comment]
Hi @sahat Could please help me to run your example code run and check?
I want to run both the front end and the PHP back end, what should I do?

**Comment by indranilatwork** [comment]
Hi @sahat , my twitter login config is set as:

  $authProvider.twitter({
    clientId: 'XXX', (Twitter app Owner ID)
    redirectUri: 'http://away-nation-api.herokuapp.com',
    responseType: 'token'
  })

But I'm getting the above mentioned error. Can you please tell me what other config I need to add?
I've also added Facebook, Google, Instagram login in the same way and those works properly.

@apur  : Did you got the solution of this issue?
