### ISSUE TITLE
Demo site is not working

### ISSUE THREAD

**Issue by bora89** [sahat/satellizer#848]
Hi, 
it seems like most of the providers do not work anymore. I have tried, Google (redirect_uri_mismatch), Facebook, Github. 
![](http://joxi.ru/jgmvBxoH8w4yma?d=1)

**Comment by sahat** [comment]
Yeah, I need to update all Redirect URIs now that Satellizer is hosted on OpenShift instead of Heroku.

**Comment by justinzelinsky** [comment]
Any update on this? Thanks :)

**Comment by sahat** [comment]
All demos (except possibly Twitch) should be working now on https://satellizer-sahat.rhcloud.com.
