### ISSUE TITLE
using native facebook app

### ISSUE THREAD

**Issue by icernn03** [sahat/satellizer#863]
can satellizer authenticate Facebook users in android/ios using native Facebook app ?

**Comment by Giegling** [comment]
No, it can't.

**Comment by icernn03** [comment]
well..can I make it do login using the native app?
Is there an API function I can use if I can provide auth details from native app ?

**Comment by sahat** [comment]
Satellizer is a JavaScript library for AngularJS. As long as your app is inside Cordova/Phonegap/Ionic container, you can make it work. It will not work with native apps.
