### ISSUE TITLE
Add reject of popupWindow on the exit event in version 0.14.1

### ISSUE THREAD

**Issue by diegopedro94** [sahat/satellizer#876]
The following the lines could be added to SatellizerPopup in version 0.14.1, in order to prevent the full upgrade of satellizer: 

```javascript
Popup.popupWindow.addEventListener('exit', function() {
          	deferred.reject('The popup window was closed');
  });
```

These lines allow the manipulation of closing cordova popup.

**Comment by sahat** [comment]
@diegopedro94 Satellizer 0.15 is a TypeScript rewrite but it's pretty much the same library as before (`0.14.1`) with a few minor changes to the configuration API. The version number only moves forward to `0.15.1`, `0.15.2`. I do not have any plans to go back and release updates to version `0.14.x`.
