### ISSUE TITLE
this.$q is not a function message in ionic project

### ISSUE THREAD

**Issue by AntonioFernandezFernandez** [sahat/satellizer#897]
I Include satellizer on a ionic project, but when i click on login button, chrome console display me this error:

`ionic.bundle.js:16989 TypeError: this.$q is not a function
    at OAuth.authenticate (oauth.ts:38)
    at Object.authenticate (authProvider.ts:109)
    at Scope.$scope.authenticate (controllers.js:363)
    at ionic.bundle.js:17774
    at ionic.bundle.js:37048
    at Scope.$eval (ionic.bundle.js:19531)
    at Scope.$apply (ionic.bundle.js:19631)
    at HTMLButtonElement.<anonymous> (ionic.bundle.js:37047)
    at ionic.bundle.js:10170
    at forEach (ionic.bundle.js:7864)`

Steps i made:

1 - install satellizer with bower.

2 - Include satellizer in index.html:

    <script src="lib/satellizer/dist/satellizer.js"></script>
    <script src="cordova.js"></script>

    
    <script `src="js/app.js"></script>

3 - modifiy app.js file:

angular.module('starter', ['ionic', 'starter.controllers', 'starter.directives','satellizer'])

.run(function($ionicPlatform) 
{
  $ionicPlatform.ready(function() 
  {
    if(window.StatusBar) {
      StatusBar.styleDefault();
    }
  });

})

.config(function($authProvider) 
{

	$authProvider.google({
	      clientId: 'clientId'
	    });
})

4 - Modify controllers.js

angular.module('starter.controllers',[])

.controller('MapCtrl', function($scope,$http, $ionicLoading, $ionicModal,$ionicPopup,$auth)
 {
$scope.authenticate = function(provider) {
      $auth.authenticate(provider)
        .then(function() {
          $ionicPopup.alert({
            title: 'Success',
            content: 'You have successfully logged in!'
          })
        })
        .catch(function(response) {
          $ionicPopup.alert({
            title: 'Error',
            content: response.data ? response.data || response.data.message : response
          })

        });
    };

});

Any suggestions???

**Comment by fieyr** [comment]
Did you ever figure this out? I'm getting the same error message also trying to login via google.

**Comment by sahat** [comment]
Judging by many StackOverflow posts and @fieyr's observations it looks like you are using an older version of Angular. Satellizer officially supports version range `"1.3.0 - 1.5.x"`.
