### ISSUE TITLE
How to set offline access

### ISSUE THREAD

**Issue by devmakk** [sahat/satellizer#898]
how to i set offline access in url parameter  to solve this issue

http://stackoverflow.com/questions/10508557/why-does-google-oauth2-re-ask-user-for-permission-when-i-send-them-to-auth-url-a

**Comment by sahat** [comment]
```js
$authProvider.google({
  optionalUrlParams: ['access_type'],
  accessType: 'offline'
});
```

**Comment by devmakk** [comment]
and another problem with your demo

in laravel


[2016-07-27 09:11:38] lumen.ERROR: exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://accounts.google.com/o/oauth2/token` resulted in a `400 Bad Request` response:
{
  "error" : "invalid_request",
  "error_description" : "Could not determine client ID from request."
}
' in /Applications/XAMPP/xamppfiles/htdocs/social/api/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:

**Comment by sahat** [comment]
@devmakk Did you set Google client id in your Angular app?

**Comment by devmakk** [comment]
ya

**Comment by dayanramly** [comment]
@sahat I have the same issue like this 
`0 : "invalid_request: Could not determine client ID from request." `
`1 : "Daily Limit for Unauthenticated Use Exceeded. Continued use requires signup."`

any update ?

**Comment by 0xmtn** [comment]
Any update on this? I'm having issues when I try to use "refreshAccessToken" function, e.g `invalid_request`. So after so many hours wasted on this I tried to use the private "refreshToken_" function, which returned the main reason why it is an invalid request: `Could not determine client ID from request.`

Here is the code I'm trying:

```
    var auth = new google_auth();   
    var oauth2Client = new auth.OAuth2(conf.cliend_id, conf.client_secret, conf.red_url);
    var creds = {access_token: accessToken,  // **I tried without this too**
                refresh_token: refreshToken};
    oauth2Client.setCredentials(creds);
    oauth2Client.refreshToken_(refreshToken, function(err, tokens, response){
      console.log("ERR: ", err); // keeps saying invalid_request 400 and nothing more.
      console.log("RESPONSE: ", response); //bunch of stuff here, where I found the reason for the error
      console.log("TOKENS: ", tokens); // NULL
```
I am on server side using `google-auth-library` and `googleapis`.

How can I solve this? Any help is appreciated!
