### ISSUE TITLE
Is it possible to login with username/password only

### ISSUE THREAD

**Issue by Rankel** [sahat/satellizer#899]
Hello,

Is it possible to authenticate with only a username/password without any emails?

Thank you

**Comment by sahat** [comment]
You will need to update your server example, but yes it's possible. Basically you need to update all references from `email` to `username` in this Node.js example app: https://github.com/sahat/satellizer/blob/master/examples/server/node/server.js#L182

**Comment by Rankel** [comment]
Great thank you for help.
