### ISSUE TITLE
Expecting a token named

### ISSUE THREAD

**Issue by chrissom** [sahat/satellizer#914]
**Problem:**

When I set ```$authProvider.tokenName``` whith an other value of ```token```, for example ```user```, It's impossible to get authenticated and I get this error: ```Expecting a token named "user```.

Did i miss something? 

**Version used:**

- satellizer 0.15.4
- Angularjs 1.4.4

**Comment by sahat** [comment]
Looks like a bug.

**Comment by sahat** [comment]
Sorry, I was thinking of `tokenPrefix`. It's not a bug. It's the JWT token name sent from the server. Example server app is sending `{ token: '......' }` that's why the default `tokenName` is `"token"`. If you want to use `user`, you will have to send that object from the server.
