### ISSUE TITLE
Pop up window does not close

### ISSUE THREAD

**Issue by freshdev1** [sahat/satellizer#915]
Hello everybody. I cannot get my pop up window closed despite getting `code` in my query string from my OAuth 2.0 provider. It keeps on fetching new code from my provider. Basically it keeps on making the `Authorize Request`. I cannot solve this, and its been 2 days since I am trying to solve this. This is what my implementation looks like:

# $authProvider configurations:
```
sgsApp.config(['$authProvider', function ($authProvider) {
    $authProvider.httpInterceptor = function () { return true; },
    $authProvider.withCredentials = false;
    $authProvider.tokenRoot = null;
    $authProvider.baseUrl = 'http://localhost:62266/identity/connect';
    $authProvider.loginUrl = '/token';
    //$authProvider.signupUrl = '/auth/signup';
    //$authProvider.unlinkUrl = '/auth/unlink/';
    $authProvider.tokenName = 'token';
    $authProvider.tokenPrefix = 'satellizer';
    $authProvider.tokenHeader = 'Authorization';
    $authProvider.tokenType = 'Bearer';
    $authProvider.storageType = 'localStorage';

    // Generic OAuth 2.0
    $authProvider.oauth2({
        name: 'QMSIdentitySrv',
        url: window.location.protocol + "//" + window.location.host + "/#/login",
        clientId: 'Test',
        redirectUri: encodeURIComponent(window.location.protocol + "//" + window.location.host + "/#/login"),
        authorizationEndpoint: "http://localhost:62266/identity/connect/authorize",
        defaultUrlParams: ['client_id', 'scope', 'response_type', 'redirect_uri', 'state', 'nonce'],
        requiredUrlParams: null,
        optionalUrlParams: null,
        scope: 'openid profile email',
        scopePrefix: null,
        scopeDelimiter: null,
        state: function () {
            return (Date.now() + "" + Math.random()).replace(".", "");
        },
        nonce: function () {
            return (Date.now() + "" + Math.random()).replace(".", "");
        },
        oauthType: '2.0',
        popupOptions: null,
        responseType: 'code',
        responseParams: {
            code: 'code'
        }
    });
}]);
```
### the above lines goes in the app.js

This is how things are invoked in Login Controller:
```
$auth.authenticate('QMSIdentitySrv')
              .then(function (succeess) {
            //toastr.success('You have successfully signed in with ' + provider + '!');
            //$location.path('/');
                  console.log(succeess);
        })
              .catch(function (error) {
                  console.log(error);

                  if (error.error) {
            // Popup error - invalid redirect_uri, pressed cancel button, etc.
            //toastr.error(error.error);
                  } else if(error.data) {
                          // HTTP response error from server
                              //toastr.error(error.data.message, error.status);
                  } else {
                      //toastr.error(error);
                  }
                  });
```

Please someone help me from the community. I have been now frustrated by not being able to solve this problem. :disappointed:

**Comment by freshdev1** [comment]
The URL which receives the code parameter:
```
http://localhost:61991/#/login?code=0397ea45ace0f1dfb9f917de3109df66&state=147103521559504504141016528538&session_state=Dr7scon0gXa1Bxseos6fY2NPcZp1JlTfBl6C2-BH7qM.7608f99eb1d943fb1dc39b281773e98d
```

**Comment by freshdev1** [comment]
Guys, I have solved the issue. I modified the `satellizer` to adapt to my OAuth provider. :smile:
Will be posting my fix for others. The change was done specifically to accept Identity Server OAuth 2.0 provider and AngularJS as a front end.

**Comment by vincentius** [comment]
I think this must be related. In IE, when trying to authenticate with code below: 

```
function authenticate() {
			$auth.authenticate('identityServerForMyProject')
				.then(function () {
					console.log('You have successfully signed in with identityServerForMyProject!');
					$state.go('stateThatGoesAfterLogin');
				})
				.catch(function (error) {
					if (error.message) {
						console.log('Error message: ' + error.message);
					} else if (error.data) {
						console.log('Error message: ' + error.data.message, error.status);
					} else {
						console.log('Error message: ' + error);
					}
				});
		}
```
When redirectUri is set to a valid page i get the following output immediately after the popup opens: `Error message: The popup window was closed` 
When redirectUri is set to something that will return 404, there'll be no output, and after logging in, the popup window won't close.

This is on Angluar 1.5.8 & Satellizer 0.15.4

**Comment by wmalevski** [comment]
@freshdev1 could you please give a link or something? I have an issue, that facebook popup is not closing.. It's about an Ionic project..

**Comment by deliverymanager** [comment]
+1

**Comment by qdequippe** [comment]
+1 @freshdev1 for a link or a piece of code. I have also an issue with an Ionic project as @wmalevski , the redirectUri is not taking into account. In my app.js I have:
```
if (ionic.Platform.is('ios') || ionic.Platform.is('android')) {
      $authProvider.cordova = true;
      commonConfig.redirectUri = 'http://localhost/';
}
```
but the facebook popup is not closing.
The code is commented here https://github.com/sahat/satellizer/blob/master/dist/satellizer.js#L542

**Comment by LuisUrrutia** [comment]
Someone has an update on this? The popup close isn't working either. (Facebook)

**Comment by freshdev1** [comment]
Sorry Guys, got extremely busy on the projects. Please know I have performed the hack in v0.14.1.

So there were a few problems that I was facing. After a lot of hacks, I got it to working.

This is how my `app.js` looks like:
```
//Satellizer configuration, to handle JWT tokens in our application.
sgsApp.config(['$authProvider', function ($authProvider) {
    $authProvider.httpInterceptor = function () { return true; },
    $authProvider.withCredentials = false;
    $authProvider.tokenName = 'token';
    $authProvider.tokenPrefix = 'access';
    $authProvider.tokenHeader = 'Authorization';
    $authProvider.tokenType = 'Bearer';
    $authProvider.storageType = 'localStorage';

    // Generic OAuth 2.0
    $authProvider.oauth2({
        name: 'QMSIdentitySrv',
        url: null,
        clientId: 'Test',
        redirectUri: encodeURIComponent(window.location.protocol + "//" + window.location.host + "/#/"),
        authorizationEndpoint: "http://localhost:62266/identity/connect/authorize",
        defaultUrlParams: ['client_id', 'scope', 'response_type', 'redirect_uri', 'state', 'nonce'],
        requiredUrlParams: null,
        optionalUrlParams: null,
        scope: 'openid profile email',
        scopePrefix: null,
        scopeDelimiter: null,
        state: function () {
            return (Date.now() + "" + Math.random()).replace(".", "");
        },
        nonce: function () {
            return (Date.now() + "" + Math.random()).replace(".", "");
        },
        oauthType: '2.0',
        popupOptions: null,
        responseType: 'id_token token',
        responseParams: {
            code: 'code',
            token: 'access_token',
            state: 'state',
            sessionState: "session_state",
            clientId: 'clientId',
            redirectUri: 'redirectUri'
        }
    });
}]);
```

As per my R&D, I found [this function](https://github.com/sahat/satellizer/blob/0.14.1/satellizer.js#L753) to be making problem. It has the responsibility of closing the pop up when the response is found.

What I changed was:

* [Line # 759](https://github.com/sahat/satellizer/blob/0.14.1/satellizer.js#L759) was altered to look like this:
`var redirectUriPath = decodeURIComponent(redirectUri);`
* [Line # 768](https://github.com/sahat/satellizer/blob/0.14.1/satellizer.js#L768) was altered to look like this:
`var popupWindowPath = utils.getFullUrlPath(Popup.popupWindow.location) + Popup.popupWindow.location.hash;`
* [Line # 771](https://github.com/sahat/satellizer/blob/0.14.1/satellizer.js#L771) was altered to look like this:
`if (popupWindowPath.indexOf(redirectUriPath) >= 0) {`
* [Line # 531](https://github.com/sahat/satellizer/blob/0.14.1/satellizer.js#L531) was altered to look like this:
`if (defaults.responseType === 'id_token token' || !defaults.url) {`

The last point is mainly Identity Server - my OpenId and OAuth 2.0 provider - related tweaking, not everybody would be requiring this I believe.

Cheers! :smile:  Hope my solution would help someone. :smile:
