### ISSUE TITLE
Can't add drive scope

### ISSUE THREAD

**Issue by tlacan** [sahat/satellizer#937]
When I am trying to add/change the google scope, my angular app doesn't work anymore.
I must add google drive scope.
I have tried since my app.js

as followed:
`angular.module('MyApp', ['ngResource', 'ngMessages', 'ngAnimate', 'toastr', 'ui.router', 'satellizer'])
  .config(function($stateProvider, $urlRouterProvider, $authProvider) {

    /**
     * Helper auth functions
     */
    var skipIfLoggedIn = function($q, $auth) {
      var deferred = $q.defer();
      if ($auth.isAuthenticated()) {
        deferred.reject();
      } else {
        deferred.resolve();
      }
      return deferred.promise;
    };

    var loginRequired = function($q, $location, $auth) {
      var deferred = $q.defer();
      if ($auth.isAuthenticated()) {
        deferred.resolve();
      } else {
        $location.path('/login');
      }
      return deferred.promise;
    };

    /**
     * App routes
     */
    $stateProvider
      .state('home', {
        url: '/',
        controller: 'HomeCtrl',
        templateUrl: 'partials/home.html'
      })
      .state('login', {
        url: '/login',
        templateUrl: 'partials/login.html',
        controller: 'LoginCtrl',
        resolve: {
          skipIfLoggedIn: skipIfLoggedIn
        }
      })
      .state('signup', {
        url: '/signup',
        templateUrl: 'partials/signup.html',
        controller: 'SignupCtrl',
        resolve: {
          skipIfLoggedIn: skipIfLoggedIn
        }
      })
      .state('logout', {
        url: '/logout',
        template: null,
        controller: 'LogoutCtrl'
      })
      .state('profile', {
        url: '/profile',
        templateUrl: 'partials/profile.html',
        controller: 'ProfileCtrl',
        resolve: {
          loginRequired: loginRequired
        }
      });
    $urlRouterProvider.otherwise('/');

    $authProvider.google({
            scope: ['email', 'profile', 'https://www.googleapis.com/auth/drive.readonly'],
            clientId: "734937359727-4fdq18iibob4mscor2gve8jqm5j462iv.apps.googleusercontent.com"
    });
    
  });
`
Even when I am modifying sattelizer.js, I am having an issue.
Without this scope modification it works well.

**Comment by sahat** [comment]
From the documentation:

Scopes that conform to the OpenID Connect standard have full names that are
short: profile, email and openid—they are not in the form of a URI. On the
other hand, Google-specific scopes are in the form of a URI, such as
https://www.googleapis.com/auth/plus.login.

Satellizer uses Openid connect. Try shortening that scope name to drive or
drive.readonly.

**Comment by tlacan** [comment]
Thanks for your answer.
it doesn't fix the issue but I think I may have a configuration issue on the ngninx server which may cause troubles with angular. I am going to try on another environment.

**Comment by sahat** [comment]
@tlacan Ok, it looks like it works with full scope URL. I am using the demo app included with this repo.

<img width="646" alt="screenshot 2016-09-04 11 39 55" src="https://cloud.githubusercontent.com/assets/544954/18233163/7d58d45c-7294-11e6-9237-d3343185b660.png">

![screenshot 2016-09-04 11 39 49](https://cloud.githubusercontent.com/assets/544954/18233165/848330e2-7294-11e6-9bff-bf73f5791b8f.png)

 So please check the code and Google app settings on your end.

**Comment by tlacan** [comment]
Thanks for your answer I am on vacation.
I haven't tried on another configuration.
I am closing the issue
