### ISSUE TITLE
How to get user email address with twitter

### ISSUE THREAD

**Issue by thatisuday** [sahat/satellizer#938]
Twitter has enable email address inclusion support using `include_email=true` query string parameter. How to implement it with satellizer?

**Comment by sahat** [comment]
Does it need to be included on the authorization url, similar to scope with comma separated strings in OAuth 2? And could you provide a link to where they announced this change?

**Comment by thatisuday** [comment]
It's Here https://dev.twitter.com/rest/reference/get/account/verify_credentials

**Comment by thatisuday** [comment]
They say, "Requesting a user’s email address requires your application to be whitelisted by Twitter. ", but it's not mandatory anymore.

**Comment by thatisuday** [comment]
@sahat If you know how this can be done, please let me know ASAP. I will give it a shot.

**Comment by sahat** [comment]
This can be done on the server. If you look at back-end implementation of Twitter auth handling, right around Step 4 when you fetch user's profile information, you can make another request to this verification url to obtain an email address.

**Comment by sahat** [comment]
I have updated the Node.js Twitter example here: https://github.com/sahat/satellizer/commit/4d53d834833836e588d2a860d679ba7956d6cdf8

Tested, works great! Thanks for this tip.

I will update the Twitter auth in [hackathon-starter](https://github.com/sahat/hackathon-starter) as well to include email address support.

**Comment by thatisuday** [comment]
Cheers :)

**Comment by thatisuday** [comment]
@sahat Just to mention, updated api endpoint url `https://api.twitter.com/1.1/account/verify_credentials.json` have only 15 request per minute rate limit while old one `https://api.twitter.com/1.1/users/show.json` had 180. So, this may cause some problem for high traffic web services.

**Comment by sahat** [comment]
@thatisuday Thanks good to know. For this demo app it definitely won't be a problem. 15 requests every 60 seconds should be fine. For high traffic web sites, usually you reach out to API partners and ask them to increase the rate limit on a case by case, just like with any other API that has rate limiting features.

**Comment by thatisuday** [comment]
@sahat Good to know. :+1:
