### ISSUE TITLE
reset password not working, invalid token

### ISSUE THREAD

**Issue by lulzimfazlija** [sahat/satellizer#964]
I am using satellizer with Laravel, for some reason the reset function is returning invalid token.. Any way I can solve this?

**Comment by sahat** [comment]
I don't believe password reset works with any examples. It has not been implemented. You are probably talking about Laravel's built-in authentication that might include a password reset functionality.

You could also implement it yourself using general guidelines from http://sahatyalkabov.com/how-to-implement-password-reset-in-nodejs/ and github.com/sahat/hackathon-starter.

Closing this issue as it is currently outside the scope of the project.
