### ISSUE TITLE
Go example

### ISSUE THREAD

**Issue by proglottis** [sahat/satellizer#97]
I started hacking together a more standard Go example. It's still pretty ugly, but the JWT stuff works. Not so sure about using Martini as an example - it sure does make pretty code but I think the community tends to put emphasis on using the standard library. I think this code could be cleaned up a lot with a good MUX.

https://gist.github.com/proglottis/cfa82d15c0ad22b73199

I can make this into a pull request if there's interest.

**Comment by seminice** [comment]
Any news about the beego example?

**Comment by owentran** [comment]
@seminice - I was holding off for the goji one. Sorry.

**Comment by seminice** [comment]
@owentran What goji one, I thought it was beego on the todo list.

**Comment by seminice** [comment]
@owentran can you share your beego example?

**Comment by owentran** [comment]
@seminice it's not in a shareable state (too tied to my app right now) with gomniauth. I plan to refactor and use http://metabates.com/2014/10/15/goth-multi-provider-authentication-for-go/.
