### ISSUE TITLE
Popup window not closing (Facebook)

### ISSUE THREAD

**Issue by ravivit9** [sahat/satellizer#99]
Tried to implement facebook authorization and noticed the following things.
1. The facebook popup window is not closing and stays there.
2. In facebook developers site when creating the token if I mention the url with sub-directories the token doesn't work and if I mention just as a localhost or www.example.com then it works but then it redirects to the mentioned url within the popup instead of redirecting in the main window.

Not sure how to solve this.

Thanks.

**Comment by lozadaOmr** [comment]
I have experienced the same thing after following the server example provided for PHP.

One thing I noticed is that when I try to do it in incognito the pop-up works fine.

**Comment by Bmkaradia** [comment]
Hello All

1. The facebook popup window is not closing and stays there in web-app. 

have you got any solution? 

I am using original satellizer.js file

Thanks

**Comment by unknownfix** [comment]
@Bmkaradia Your Site URL in facebook must match the server url (http://127.0.0.1:8000 !=  http://localhost:8000)
