### ISSUE TITLE
Two tokens, Refresh Token and Access Token

### ISSUE THREAD

**Issue by michaelcyyuen** [sahat/satellizer#999]
Hi all,

I would like to know does satellizer supports two tokens in a single web app?
So I could use one as refresh token, the another as access token.

Cheers,
Michael

**Comment by johnjspiteri** [comment]
@michaelcyyuen can you create two unique tokens for your server response?

```javascript
res.send({
    accessToken: createJWT(data),
    refreshToken: createJWT(data),
});
```
Then use "accessToken" to be set as your Satellizer token?

```javascript
}).then(function(response) {
    $auth.setToken(response.accessToken);
    $state.go('home');
});
````

**Comment by smurfyuen** [comment]
@johnjspiteri 
I've decided to store in httponly cookies after evaluating the whole design, which I feel much easier and less vulnerable.

**Comment by johnjspiteri** [comment]
@michaelcyyuen all good.

**Comment by MattiJarvinen** [comment]
Refresh tokens would be really nice in Ionic & Cordova projects.
